// Code generated by vexilc. DO NOT EDIT.
// Source: test.unions

use vexil_runtime::*;

pub const SCHEMA_HASH: [u8; 32] = [0x2f, 0x63, 0x8f, 0x3e, 0x17, 0x8f, 0x50, 0x9c, 0x8f, 0x7b, 0xfb, 0x6d, 0x38, 0xa8, 0x56, 0x8f, 0x6e, 0x8c, 0xc9, 0xad, 0xe3, 0xf0, 0xa5, 0x06, 0x9a, 0x5c, 0x9d, 0x97, 0x97, 0x71, 0xa7, 0xb9];

// ── Shape ──
#[derive(Debug, Clone, PartialEq)]
pub enum Shape {
    Circle { radius: f32 },
    Rectangle { width: f32, height: f32 },
    Point {},
}

impl vexil_runtime::Pack for Shape {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.flush_to_byte_boundary();
        match self {
            Self::Circle { radius } {
                w.write_leb128(0_u64);
                let mut payload_w = vexil_runtime::BitWriter::new();
                payload_w.write_f32(radius);
                payload_w.flush_to_byte_boundary();
                let payload = payload_w.finish();
                w.write_leb128(payload.len() as u64);
                w.write_raw_bytes(&payload);
            }
            Self::Rectangle { width, height } {
                w.write_leb128(1_u64);
                let mut payload_w = vexil_runtime::BitWriter::new();
                payload_w.write_f32(width);
                payload_w.write_f32(height);
                payload_w.flush_to_byte_boundary();
                let payload = payload_w.finish();
                w.write_leb128(payload.len() as u64);
                w.write_raw_bytes(&payload);
            }
            Self::Point {} {
                w.write_leb128(2_u64);
                w.write_leb128(0_u64);
            }
        }
        Ok(())
    }
}

impl vexil_runtime::Unpack for Shape {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        r.flush_to_byte_boundary();
        let disc = r.read_leb128(10_u8)?;
        let len = r.read_leb128(10_u8)? as usize;
        match disc {
            0_u64 {
                let payload = r.read_raw_bytes(len)?;
                let mut pr = vexil_runtime::BitReader::new(&payload);
                let radius = pr.read_f32()?;
                pr.flush_to_byte_boundary();
                Ok(Self::Circle { radius })
            }
            1_u64 {
                let payload = r.read_raw_bytes(len)?;
                let mut pr = vexil_runtime::BitReader::new(&payload);
                let width = pr.read_f32()?;
                let height = pr.read_f32()?;
                pr.flush_to_byte_boundary();
                Ok(Self::Rectangle { width, height })
            }
            2_u64 {
                let _skip = r.read_raw_bytes(len)?;
                Ok(Self::Point {})
            }
            _ {
                let _skip = r.read_raw_bytes(len)?;
                Err(vexil_runtime::DecodeError::UnknownUnionVariant { type_name: "Shape", discriminant: disc })
            }
        }
    }
}


// ── Color ──
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub enum Color {
    Ansi { code: u8 },
    Rgb { r: u8, g: u8, b: u8 },
    Reset {},
    Unknown { discriminant: u64, data: Vec<u8> },
}

impl vexil_runtime::Pack for Color {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.flush_to_byte_boundary();
        match self {
            Self::Ansi { code } {
                w.write_leb128(0_u64);
                let mut payload_w = vexil_runtime::BitWriter::new();
                payload_w.write_u8(code);
                payload_w.flush_to_byte_boundary();
                let payload = payload_w.finish();
                w.write_leb128(payload.len() as u64);
                w.write_raw_bytes(&payload);
            }
            Self::Rgb { r, g, b } {
                w.write_leb128(1_u64);
                let mut payload_w = vexil_runtime::BitWriter::new();
                payload_w.write_u8(r);
                payload_w.write_u8(g);
                payload_w.write_u8(b);
                payload_w.flush_to_byte_boundary();
                let payload = payload_w.finish();
                w.write_leb128(payload.len() as u64);
                w.write_raw_bytes(&payload);
            }
            Self::Reset {} {
                w.write_leb128(2_u64);
                w.write_leb128(0_u64);
            }
            Self::Unknown { discriminant, data } {
                w.write_leb128(*discriminant);
                w.write_leb128(data.len() as u64);
                w.write_raw_bytes(data);
            }
        }
        Ok(())
    }
}

impl vexil_runtime::Unpack for Color {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        r.flush_to_byte_boundary();
        let disc = r.read_leb128(10_u8)?;
        let len = r.read_leb128(10_u8)? as usize;
        match disc {
            0_u64 {
                let payload = r.read_raw_bytes(len)?;
                let mut pr = vexil_runtime::BitReader::new(&payload);
                let code = pr.read_u8()?;
                pr.flush_to_byte_boundary();
                Ok(Self::Ansi { code })
            }
            1_u64 {
                let payload = r.read_raw_bytes(len)?;
                let mut pr = vexil_runtime::BitReader::new(&payload);
                let r = pr.read_u8()?;
                let g = pr.read_u8()?;
                let b = pr.read_u8()?;
                pr.flush_to_byte_boundary();
                Ok(Self::Rgb { r, g, b })
            }
            2_u64 {
                let _skip = r.read_raw_bytes(len)?;
                Ok(Self::Reset {})
            }
            other {
                let data = r.read_raw_bytes(len)?;
                Ok(Self::Unknown { discriminant: other, data })
            }
        }
    }
}


// ── Event ──
// REMOVED @1 (since unknown): Hover events moved to separate stream
pub const EVENT_REMOVED_ORDINALS: &[(u16, &str, &str)] = &[
    (1, "unknown", "Hover events moved to separate stream"),
];
#[derive(Debug, Clone, PartialEq)]
pub enum Event {
    Click { x: u16, y: u16 },
    Scroll { delta: i16 },
}

impl vexil_runtime::Pack for Event {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.flush_to_byte_boundary();
        match self {
            Self::Click { x, y } {
                w.write_leb128(0_u64);
                let mut payload_w = vexil_runtime::BitWriter::new();
                payload_w.write_u16(x);
                payload_w.write_u16(y);
                payload_w.flush_to_byte_boundary();
                let payload = payload_w.finish();
                w.write_leb128(payload.len() as u64);
                w.write_raw_bytes(&payload);
            }
            Self::Scroll { delta } {
                w.write_leb128(2_u64);
                let mut payload_w = vexil_runtime::BitWriter::new();
                payload_w.write_i16(delta);
                payload_w.flush_to_byte_boundary();
                let payload = payload_w.finish();
                w.write_leb128(payload.len() as u64);
                w.write_raw_bytes(&payload);
            }
        }
        Ok(())
    }
}

impl vexil_runtime::Unpack for Event {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        r.flush_to_byte_boundary();
        let disc = r.read_leb128(10_u8)?;
        let len = r.read_leb128(10_u8)? as usize;
        match disc {
            0_u64 {
                let payload = r.read_raw_bytes(len)?;
                let mut pr = vexil_runtime::BitReader::new(&payload);
                let x = pr.read_u16()?;
                let y = pr.read_u16()?;
                pr.flush_to_byte_boundary();
                Ok(Self::Click { x, y })
            }
            2_u64 {
                let payload = r.read_raw_bytes(len)?;
                let mut pr = vexil_runtime::BitReader::new(&payload);
                let delta = pr.read_i16()?;
                pr.flush_to_byte_boundary();
                Ok(Self::Scroll { delta })
            }
            _ {
                let _skip = r.read_raw_bytes(len)?;
                Err(vexil_runtime::DecodeError::UnknownUnionVariant { type_name: "Event", discriminant: disc })
            }
        }
    }
}

