// Code generated by vexilc. DO NOT EDIT.
// Source: test.newtypes

use vexil_runtime::*;


// ── SessionId ──
#[derive(Debug, Clone, PartialEq)]
pub struct SessionId(pub u64);

impl vexil_runtime::Pack for SessionId {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_u64(self.0);
        w.flush_to_byte_boundary();
        Ok(())
    }
}

impl vexil_runtime::Unpack for SessionId {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let value = r.read_u64()?;
        r.flush_to_byte_boundary();
        Ok(Self(value))
    }
}


// ── PaneId ──
#[derive(Debug, Clone, PartialEq)]
pub struct PaneId(pub u64);

impl vexil_runtime::Pack for PaneId {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_u64(self.0);
        w.flush_to_byte_boundary();
        Ok(())
    }
}

impl vexil_runtime::Unpack for PaneId {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let value = r.read_u64()?;
        r.flush_to_byte_boundary();
        Ok(Self(value))
    }
}


// ── ExitCode ──
#[derive(Debug, Clone, PartialEq)]
pub struct ExitCode(pub i32);

impl vexil_runtime::Pack for ExitCode {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_i32(self.0);
        w.flush_to_byte_boundary();
        Ok(())
    }
}

impl vexil_runtime::Unpack for ExitCode {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let value = r.read_i32()?;
        r.flush_to_byte_boundary();
        Ok(Self(value))
    }
}


// ── Name ──
#[derive(Debug, Clone, PartialEq)]
pub struct Name(pub String);

impl vexil_runtime::Pack for Name {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_string(&self.0);
        w.flush_to_byte_boundary();
        Ok(())
    }
}

impl vexil_runtime::Unpack for Name {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let value = r.read_string()?;
        r.flush_to_byte_boundary();
        Ok(Self(value))
    }
}


// ── Payload ──
#[derive(Debug, Clone, PartialEq)]
pub struct Payload(pub Vec<u8>);

impl vexil_runtime::Pack for Payload {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_bytes(&self.0);
        w.flush_to_byte_boundary();
        Ok(())
    }
}

impl vexil_runtime::Unpack for Payload {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let value = r.read_bytes()?;
        r.flush_to_byte_boundary();
        Ok(Self(value))
    }
}


// ── Color ──
#[derive(Debug, Clone, PartialEq)]
pub struct Color(pub (u8, u8, u8));

impl vexil_runtime::Pack for Color {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_u8(self.0.0);
        w.write_u8(self.0.1);
        w.write_u8(self.0.2);
        w.flush_to_byte_boundary();
        Ok(())
    }
}

impl vexil_runtime::Unpack for Color {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let value_0 = r.read_u8()?;
        let value_1 = r.read_u8()?;
        let value_2 = r.read_u8()?;
        let value = (value_0, value_1, value_2);
        r.flush_to_byte_boundary();
        Ok(Self(value))
    }
}

