// Code generated by vexilc. DO NOT EDIT.
// Source: test.config

use vexil_runtime::*;

pub const SCHEMA_HASH: [u8; 32] = [0xb8, 0x14, 0xe7, 0xba, 0x3c, 0xac, 0xbf, 0xb6, 0xa4, 0xb8, 0xe2, 0xb1, 0x38, 0x37, 0xef, 0xa9, 0x67, 0x83, 0x81, 0xb1, 0x6f, 0x68, 0x3a, 0xf8, 0xc0, 0x75, 0x30, 0x79, 0x2b, 0x8b, 0x7c, 0x6e];

// ── LogLevel ──
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u64)]
pub enum LogLevel {
    Debug = 0_u64,
    Info = 1_u64,
    Warn = 2_u64,
    Error = 3_u64,
}

impl vexil_runtime::Pack for LogLevel {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        let disc: u64 = match self {
            Self::Debug => 0_u64,
            Self::Info => 1_u64,
            Self::Warn => 2_u64,
            Self::Error => 3_u64,
        };
        w.write_bits(disc, 2_u8);
        Ok(())
    }
}

impl vexil_runtime::Unpack for LogLevel {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let disc = r.read_bits(2_u8)?;
        match disc {
            0_u64 => Ok(Self::Debug),
            1_u64 => Ok(Self::Info),
            2_u64 => Ok(Self::Warn),
            3_u64 => Ok(Self::Error),
            _ => Err(vexil_runtime::DecodeError::UnknownEnumVariant { type_name: "LogLevel", value: disc }),
        }
    }
}


// ── ServerConfig ──
#[derive(Debug, Clone, PartialEq)]
pub struct ServerConfig {
    pub max_sessions: u32,
    pub timeout_ms: u64,
    pub enable_tls: bool,
    pub log_level: String,
    pub bind_port: u16,
    pub pi_approx: f64,
}

impl Default for ServerConfig {
    fn default() -> Self {
        Self {
            max_sessions: 1024,
            timeout_ms: 30000,
            enable_tls: false,
            log_level: String::from("info"),
            bind_port: 8080,
            pi_approx: 3.14159,
        }
    }
}


// ── WithOptional ──
#[derive(Debug, Clone, PartialEq)]
pub struct WithOptional {
    pub nickname: Option<String>,
    pub greeting: Option<String>,
}

impl Default for WithOptional {
    fn default() -> Self {
        Self {
            nickname: None,
            greeting: Some(String::from("hello")),
        }
    }
}


// ── WithArrays ──
#[derive(Debug, Clone, PartialEq)]
pub struct WithArrays {
    pub tags: Vec<String>,
    pub ports: Vec<u16>,
    pub empty: Vec<bool>,
}

impl Default for WithArrays {
    fn default() -> Self {
        Self {
            tags: vec![],
            ports: vec![80, 443, 8080],
            empty: vec![],
        }
    }
}


// ── Nested ──
#[derive(Debug, Clone, PartialEq)]
pub struct Nested {
    pub level: LogLevel,
}

impl Default for Nested {
    fn default() -> Self {
        Self {
            level: LogLevel::Info,
        }
    }
}

