// Code generated by vexilc. DO NOT EDIT.
// Source: test.primitives

package primitives

import vexil "github.com/vexil-lang/vexil/packages/runtime-go"

var SchemaHash = [32]byte{0x7c, 0x63, 0xe0, 0x11, 0xba, 0x5b, 0x99, 0xab, 0x88, 0x41, 0x02, 0xf3, 0x55, 0xed, 0x30, 0x4a, 0xd3, 0x38, 0xbe, 0x28, 0x8e, 0x69, 0xac, 0x3e, 0xdf, 0x8b, 0x61, 0x99, 0x49, 0x20, 0x41, 0x01}

// ── AllPrimitives ──
type AllPrimitives struct {
	A bool
	B uint8
	C uint16
	D uint32
	E uint64
	F int8
	G int16
	H int32
	I int64
	J float32
	K float64
	L struct{}
	Unknown []byte
}

func (m *AllPrimitives) Pack(w *vexil.BitWriter) error {
	w.WriteBool(m.A)
	w.WriteU8(m.B)
	w.WriteU16(m.C)
	w.WriteU32(m.D)
	w.WriteU64(m.E)
	w.WriteI8(m.F)
	w.WriteI16(m.G)
	w.WriteI32(m.H)
	w.WriteI64(m.I)
	w.WriteF32(m.J)
	w.WriteF64(m.K)
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *AllPrimitives) Unpack(r *vexil.BitReader) error {
	{
		v, err := r.ReadBool()
		if err != nil {
			return err
		}
		m.A = v
	}
	{
		v, err := r.ReadU8()
		if err != nil {
			return err
		}
		m.B = v
	}
	{
		v, err := r.ReadU16()
		if err != nil {
			return err
		}
		m.C = v
	}
	{
		v, err := r.ReadU32()
		if err != nil {
			return err
		}
		m.D = v
	}
	{
		v, err := r.ReadU64()
		if err != nil {
			return err
		}
		m.E = v
	}
	{
		v, err := r.ReadI8()
		if err != nil {
			return err
		}
		m.F = v
	}
	{
		v, err := r.ReadI16()
		if err != nil {
			return err
		}
		m.G = v
	}
	{
		v, err := r.ReadI32()
		if err != nil {
			return err
		}
		m.H = v
	}
	{
		v, err := r.ReadI64()
		if err != nil {
			return err
		}
		m.I = v
	}
	{
		v, err := r.ReadF32()
		if err != nil {
			return err
		}
		m.J = v
	}
	{
		v, err := r.ReadF64()
		if err != nil {
			return err
		}
		m.K = v
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}

