// Code generated by vexilc. DO NOT EDIT.
// Source: test.sub_byte

package sub_byte

import vexil "github.com/vexil-lang/vexil/packages/runtime-go"

var SchemaHash = [32]byte{0xa9, 0xc6, 0x2a, 0x4b, 0xfc, 0xfb, 0x2a, 0xa6, 0x5a, 0xe5, 0x6e, 0xd3, 0x03, 0x51, 0xc4, 0xca, 0xaf, 0x02, 0x47, 0x4b, 0x04, 0xdb, 0x21, 0x05, 0xb5, 0x3c, 0x1e, 0xb0, 0x36, 0x31, 0xd2, 0x5b}

// ── SubByteUnsigned ──
type SubByteUnsigned struct {
	A uint8
	B uint8
	C uint8
	D uint8
	E uint8
	F uint8
	G uint8
	H uint8
	I uint8
	J uint8
	K uint8
	L uint8
	M uint8
	Unknown []byte
}

func (m *SubByteUnsigned) Pack(w *vexil.BitWriter) error {
	w.WriteBits(uint64(m.A), 1)
	w.WriteBits(uint64(m.B), 2)
	w.WriteBits(uint64(m.C), 3)
	w.WriteBits(uint64(m.D), 4)
	w.WriteBits(uint64(m.E), 5)
	w.WriteBits(uint64(m.F), 6)
	w.WriteBits(uint64(m.G), 7)
	w.WriteBits(uint64(m.H), 9)
	w.WriteBits(uint64(m.I), 15)
	w.WriteBits(uint64(m.J), 17)
	w.WriteBits(uint64(m.K), 31)
	w.WriteBits(uint64(m.L), 33)
	w.WriteBits(uint64(m.M), 63)
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *SubByteUnsigned) Unpack(r *vexil.BitReader) error {
	{
		v, err := r.ReadBits(1)
		if err != nil {
			return err
		}
		m.A = uint8(v)
	}
	{
		v, err := r.ReadBits(2)
		if err != nil {
			return err
		}
		m.B = uint8(v)
	}
	{
		v, err := r.ReadBits(3)
		if err != nil {
			return err
		}
		m.C = uint8(v)
	}
	{
		v, err := r.ReadBits(4)
		if err != nil {
			return err
		}
		m.D = uint8(v)
	}
	{
		v, err := r.ReadBits(5)
		if err != nil {
			return err
		}
		m.E = uint8(v)
	}
	{
		v, err := r.ReadBits(6)
		if err != nil {
			return err
		}
		m.F = uint8(v)
	}
	{
		v, err := r.ReadBits(7)
		if err != nil {
			return err
		}
		m.G = uint8(v)
	}
	{
		v, err := r.ReadBits(9)
		if err != nil {
			return err
		}
		m.H = uint8(v)
	}
	{
		v, err := r.ReadBits(15)
		if err != nil {
			return err
		}
		m.I = uint8(v)
	}
	{
		v, err := r.ReadBits(17)
		if err != nil {
			return err
		}
		m.J = uint8(v)
	}
	{
		v, err := r.ReadBits(31)
		if err != nil {
			return err
		}
		m.K = uint8(v)
	}
	{
		v, err := r.ReadBits(33)
		if err != nil {
			return err
		}
		m.L = uint8(v)
	}
	{
		v, err := r.ReadBits(63)
		if err != nil {
			return err
		}
		m.M = uint8(v)
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}


// ── SubByteSigned ──
type SubByteSigned struct {
	A uint8
	B uint8
	C uint8
	D uint8
	E uint8
	F uint8
	G uint8
	H uint8
	I uint8
	J uint8
	K uint8
	L uint8
	Unknown []byte
}

func (m *SubByteSigned) Pack(w *vexil.BitWriter) error {
	w.WriteBits(uint64(m.A), 2)
	w.WriteBits(uint64(m.B), 3)
	w.WriteBits(uint64(m.C), 4)
	w.WriteBits(uint64(m.D), 5)
	w.WriteBits(uint64(m.E), 6)
	w.WriteBits(uint64(m.F), 7)
	w.WriteBits(uint64(m.G), 9)
	w.WriteBits(uint64(m.H), 15)
	w.WriteBits(uint64(m.I), 17)
	w.WriteBits(uint64(m.J), 31)
	w.WriteBits(uint64(m.K), 33)
	w.WriteBits(uint64(m.L), 63)
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *SubByteSigned) Unpack(r *vexil.BitReader) error {
	{
		v, err := r.ReadBits(2)
		if err != nil {
			return err
		}
		m.A := int8((uint64(v) << 62) >> 62)
	}
	{
		v, err := r.ReadBits(3)
		if err != nil {
			return err
		}
		m.B := int8((uint64(v) << 61) >> 61)
	}
	{
		v, err := r.ReadBits(4)
		if err != nil {
			return err
		}
		m.C := int8((uint64(v) << 60) >> 60)
	}
	{
		v, err := r.ReadBits(5)
		if err != nil {
			return err
		}
		m.D := int8((uint64(v) << 59) >> 59)
	}
	{
		v, err := r.ReadBits(6)
		if err != nil {
			return err
		}
		m.E := int8((uint64(v) << 58) >> 58)
	}
	{
		v, err := r.ReadBits(7)
		if err != nil {
			return err
		}
		m.F := int8((uint64(v) << 57) >> 57)
	}
	{
		v, err := r.ReadBits(9)
		if err != nil {
			return err
		}
		m.G := int8((uint64(v) << 55) >> 55)
	}
	{
		v, err := r.ReadBits(15)
		if err != nil {
			return err
		}
		m.H := int8((uint64(v) << 49) >> 49)
	}
	{
		v, err := r.ReadBits(17)
		if err != nil {
			return err
		}
		m.I := int8((uint64(v) << 47) >> 47)
	}
	{
		v, err := r.ReadBits(31)
		if err != nil {
			return err
		}
		m.J := int8((uint64(v) << 33) >> 33)
	}
	{
		v, err := r.ReadBits(33)
		if err != nil {
			return err
		}
		m.K := int8((uint64(v) << 31) >> 31)
	}
	{
		v, err := r.ReadBits(63)
		if err != nil {
			return err
		}
		m.L := int8(v & ((1 << 63) - 1))
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}

