// Code generated by vexilc. DO NOT EDIT.
// Source: test.semantic_types

package semantic_types

import vexil "github.com/vexil-lang/vexil/packages/runtime-go"

var SchemaHash = [32]byte{0x39, 0xb0, 0x6f, 0xca, 0x22, 0x4d, 0x88, 0x38, 0x78, 0xf8, 0x98, 0xaf, 0x9a, 0x78, 0x83, 0x90, 0x14, 0x32, 0x7e, 0x02, 0x1f, 0x50, 0x44, 0x0b, 0xa7, 0xf3, 0xee, 0xc0, 0xd8, 0x9e, 0x64, 0x99}

// ── AllSemantic ──
type AllSemantic struct {
	A string
	B []byte
	C [3]uint8
	D [16]byte
	E int64
	F [32]byte
	Unknown []byte
}

func (m *AllSemantic) Pack(w *vexil.BitWriter) error {
	w.WriteString(m.A)
	w.WriteBytes(m.B)
	w.WriteU8(m.C[0])
	w.WriteU8(m.C[1])
	w.WriteU8(m.C[2])
	w.WriteRawBytes(m.D[:])
	w.WriteI64(m.E)
	w.WriteRawBytes(m.F[:])
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *AllSemantic) Unpack(r *vexil.BitReader) error {
	{
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.A = v
	}
	{
		v, err := r.ReadBytes()
		if err != nil {
			return err
		}
		m.B = v
	}
	{
		r0, err := r.ReadU8()
		if err != nil {
			return err
		}
		r1, err := r.ReadU8()
		if err != nil {
			return err
		}
		r2, err := r.ReadU8()
		if err != nil {
			return err
		}
		m.C = [3]uint8{r0, r1, r2}
	}
	{
		v, err := r.ReadRawBytes(16)
		if err != nil {
			return err
		}
		copy(m.D[:], v)
	}
	{
		v, err := r.ReadI64()
		if err != nil {
			return err
		}
		m.E = v
	}
	{
		v, err := r.ReadRawBytes(32)
		if err != nil {
			return err
		}
		copy(m.F[:], v)
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}

