// Code generated by vexilc. DO NOT EDIT.
// Source: test.config

package config

import vexil "github.com/vexil-lang/vexil/packages/runtime-go"

var SchemaHash = [32]byte{0xb8, 0x14, 0xe7, 0xba, 0x3c, 0xac, 0xbf, 0xb6, 0xa4, 0xb8, 0xe2, 0xb1, 0x38, 0x37, 0xef, 0xa9, 0x67, 0x83, 0x81, 0xb1, 0x6f, 0x68, 0x3a, 0xf8, 0xc0, 0x75, 0x30, 0x79, 0x2b, 0x8b, 0x7c, 0x6e}

// ── LogLevel ──
type LogLevel int

const (
	LogLevelDebug LogLevel = 0
	LogLevelInfo LogLevel = 1
	LogLevelWarn LogLevel = 2
	LogLevelError LogLevel = 3
)

func (s LogLevel) Pack(w *vexil.BitWriter) error {
	w.WriteBits(uint64(s), 2)
	return nil
}

func (s *LogLevel) Unpack(r *vexil.BitReader) error {
	v, err := r.ReadBits(2)
	if err != nil {
		return err
	}
	*s = LogLevel(v)
	return nil
}


// ── ServerConfig ──
type ServerConfig struct {
	MaxSessions uint32
	TimeoutMs uint64
	EnableTLS bool
	LogLevel string
	BindPort uint16
	PiApprox float64
}


// ── WithOptional ──
type WithOptional struct {
	Nickname *string
	Greeting *string
}


// ── WithArrays ──
type WithArrays struct {
	Tags []string
	Ports []uint16
	Empty []bool
}


// ── Nested ──
type Nested struct {
	Level LogLevel
}

