// Code generated by vexilc. DO NOT EDIT.
// Source: test.keywords_as_fields

package keywords_as_fields

import vexil "github.com/vexil-lang/vexil/packages/runtime-go"

var SchemaHash = [32]byte{0x3c, 0xe1, 0x7c, 0x93, 0x58, 0x63, 0xae, 0xa0, 0x6f, 0x76, 0x53, 0xdc, 0xb8, 0x11, 0xe3, 0x87, 0x34, 0x2a, 0x85, 0x1c, 0x0a, 0xcd, 0xee, 0x7e, 0xa2, 0x86, 0x73, 0x7c, 0x3e, 0x03, 0xe7, 0x41}

// ── KeywordFields ──
type KeywordFields struct {
	Flags uint8
	Type uint16
	Hash []byte
	String uint32
	Message uint64
	Enum uint8
	Union uint8
	Config bool
	Import uint32
	Namespace string
	Array uint8
	Map uint8
	Result uint8
	Optional uint8
	From uint8
	As uint8
	Void uint8
	None uint8
	True uint8
	False uint8
	Unknown []byte
}

func (m *KeywordFields) Pack(w *vexil.BitWriter) error {
	w.WriteU8(m.Flags)
	w.WriteU16(m.Type)
	w.WriteBytes(m.Hash)
	w.WriteU32(m.String)
	w.WriteU64(m.Message)
	w.WriteU8(m.Enum)
	w.WriteU8(m.Union)
	w.WriteBool(m.Config)
	w.WriteU32(m.Import)
	w.WriteString(m.Namespace)
	w.WriteU8(m.Array)
	w.WriteU8(m.Map)
	w.WriteU8(m.Result)
	w.WriteU8(m.Optional)
	w.WriteU8(m.From)
	w.WriteU8(m.As)
	w.WriteU8(m.Void)
	w.WriteU8(m.None)
	w.WriteU8(m.True)
	w.WriteU8(m.False)
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *KeywordFields) Unpack(r *vexil.BitReader) error {
	{
		v, err := r.ReadU8()
		if err != nil {
			return err
		}
		m.Flags = v
	}
	{
		v, err := r.ReadU16()
		if err != nil {
			return err
		}
		m.Type = v
	}
	{
		v, err := r.ReadBytes()
		if err != nil {
			return err
		}
		m.Hash = v
	}
	{
		v, err := r.ReadU32()
		if err != nil {
			return err
		}
		m.String = v
	}
	{
		v, err := r.ReadU64()
		if err != nil {
			return err
		}
		m.Message = v
	}
	{
		v, err := r.ReadU8()
		if err != nil {
			return err
		}
		m.Enum = v
	}
	{
		v, err := r.ReadU8()
		if err != nil {
			return err
		}
		m.Union = v
	}
	{
		v, err := r.ReadBool()
		if err != nil {
			return err
		}
		m.Config = v
	}
	{
		v, err := r.ReadU32()
		if err != nil {
			return err
		}
		m.Import = v
	}
	{
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Namespace = v
	}
	{
		v, err := r.ReadU8()
		if err != nil {
			return err
		}
		m.Array = v
	}
	{
		v, err := r.ReadU8()
		if err != nil {
			return err
		}
		m.Map = v
	}
	{
		v, err := r.ReadU8()
		if err != nil {
			return err
		}
		m.Result = v
	}
	{
		v, err := r.ReadU8()
		if err != nil {
			return err
		}
		m.Optional = v
	}
	{
		v, err := r.ReadU8()
		if err != nil {
			return err
		}
		m.From = v
	}
	{
		v, err := r.ReadU8()
		if err != nil {
			return err
		}
		m.As = v
	}
	{
		v, err := r.ReadU8()
		if err != nil {
			return err
		}
		m.Void = v
	}
	{
		v, err := r.ReadU8()
		if err != nil {
			return err
		}
		m.None = v
	}
	{
		v, err := r.ReadU8()
		if err != nil {
			return err
		}
		m.True = v
	}
	{
		v, err := r.ReadU8()
		if err != nil {
			return err
		}
		m.False = v
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}

