// Code generated by vexilc. DO NOT EDIT.
// Source: test.recursive

package recursive

import (
	"fmt"

	vexil "github.com/vexil-lang/vexil/packages/runtime-go"
)

var SchemaHash = [32]byte{0xa1, 0x25, 0xcb, 0x50, 0x29, 0x3e, 0xa3, 0x25, 0x60, 0x73, 0x08, 0x42, 0x52, 0xc5, 0xca, 0xf0, 0x83, 0xf5, 0xdd, 0xf7, 0x30, 0x18, 0xf8, 0x51, 0x8e, 0x54, 0xa9, 0xfd, 0xbe, 0xeb, 0x91, 0xae}

// ── TreeNode ──
type TreeNode struct {
	Value int32
	Children []TreeNode
	Unknown []byte
}

func (m *TreeNode) Pack(w *vexil.BitWriter) error {
	w.WriteI32(m.Value)
	w.WriteLeb128(uint64(len(m.Children)))
	for _, item := range m.Children {
		if err := w.EnterRecursive(); err != nil {
			return err
		}
		if err := item.Pack(w); err != nil {
			return err
		}
		w.LeaveRecursive()
	}
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *TreeNode) Unpack(r *vexil.BitReader) error {
	{
		v, err := r.ReadI32()
		if err != nil {
			return err
		}
		m.Value = v
	}
	{
		arrLen, err := r.ReadLeb128(4)
		if err != nil {
			return err
		}
		m.Children = make([]TreeNode, arrLen)
		for i := uint64(0); i < arrLen; i++ {
			{
				if err := r.EnterRecursive(); err != nil {
					return err
				}
				if err := m.Children[i].Unpack(r); err != nil {
					return err
				}
				r.LeaveRecursive()
			}
		}
	}
	r.FlushToByteBoundary()
	m.Unknown = r.ReadRemaining()
	return nil
}


// ── LinkedList ──
type LinkedList struct {
	Value string
	Next *LinkedList
	Unknown []byte
}

func (m *LinkedList) Pack(w *vexil.BitWriter) error {
	w.WriteString(m.Value)
	w.WriteBool(m.Next != nil)
	w.FlushToByteBoundary()
	if m.Next != nil {
		if err := w.EnterRecursive(); err != nil {
			return err
		}
		if err := m.Next.Pack(w); err != nil {
			return err
		}
		w.LeaveRecursive()
	}
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *LinkedList) Unpack(r *vexil.BitReader) error {
	{
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Value = v
	}
	{
		present, err := r.ReadBool()
		if err != nil {
			return err
		}
		r.FlushToByteBoundary()
		if present {
			var optVal LinkedList
			{
				if err := r.EnterRecursive(); err != nil {
					return err
				}
				if err := optVal.Unpack(r); err != nil {
					return err
				}
				r.LeaveRecursive()
			}
			m.Next = &optVal
		}
	}
	r.FlushToByteBoundary()
	m.Unknown = r.ReadRemaining()
	return nil
}


// ── Expr ──
type Expr struct {
	Kind ExprKind
	Unknown []byte
}

func (m *Expr) Pack(w *vexil.BitWriter) error {
	if err := PackExprKind(m.Kind, w); err != nil {
		return err
	}
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *Expr) Unpack(r *vexil.BitReader) error {
	{
		v, err := UnpackExprKind(r)
		if err != nil {
			return err
		}
		m.Kind = v
	}
	r.FlushToByteBoundary()
	m.Unknown = r.ReadRemaining()
	return nil
}


// ── ExprKind ──
type ExprKind interface {
	isExprKind()
}

type ExprKindLiteral struct {
	Value int64
	Unknown []byte
}

func (ExprKindLiteral) isExprKind() {
}

type ExprKindBinary struct {
	Left Expr
	Op uint8
	Right Expr
	Unknown []byte
}

func (ExprKindBinary) isExprKind() {
}

func PackExprKind(v ExprKind, w *vexil.BitWriter) error {
	w.FlushToByteBoundary()
	switch t := v.(type) {
		case *ExprKindLiteral: {
			w.WriteLeb128(0)
			pw := vexil.NewBitWriter()
			pw.WriteI64(t.Value)
			pw.FlushToByteBoundary()
			payload := pw.Finish()
			w.WriteLeb128(uint64(len(payload)))
			w.WriteRawBytes(payload)
		}
		case *ExprKindBinary: {
			w.WriteLeb128(1)
			pw := vexil.NewBitWriter()
			if err := pw.EnterRecursive(); err != nil {
				return err
			}
			if err := t.Left.Pack(pw); err != nil {
				return err
			}
			pw.LeaveRecursive()
			pw.WriteU8(t.Op)
			if err := pw.EnterRecursive(); err != nil {
				return err
			}
			if err := t.Right.Pack(pw); err != nil {
				return err
			}
			pw.LeaveRecursive()
			pw.FlushToByteBoundary()
			payload := pw.Finish()
			w.WriteLeb128(uint64(len(payload)))
			w.WriteRawBytes(payload)
		}
	}
	return nil
}

func UnpackExprKind(r *vexil.BitReader) (ExprKind, error) {
	r.FlushToByteBoundary()
	disc, err := r.ReadLeb128(10)
	if err != nil {
		return nil, err
	}
	length, err := r.ReadLeb128(4)
	if err != nil {
		return nil, err
	}
	switch disc {
		case 0: {
			payloadBytes, err := r.ReadRawBytes(int(length))
			if err != nil {
				return nil, err
			}
			pr := vexil.NewBitReader(payloadBytes)
			result := &ExprKindLiteral{}
			{
				v, err := pr.ReadI64()
				if err != nil {
					return nil, err
				}
				result.Value = v
			}
			pr.FlushToByteBoundary()
			result.Unknown = pr.ReadRemaining()
			return result, nil
		}
		case 1: {
			payloadBytes, err := r.ReadRawBytes(int(length))
			if err != nil {
				return nil, err
			}
			pr := vexil.NewBitReader(payloadBytes)
			result := &ExprKindBinary{}
			{
				if err := pr.EnterRecursive(); err != nil {
					return nil, err
				}
				if err := result.Left.Unpack(pr); err != nil {
					return nil, err
				}
				pr.LeaveRecursive()
			}
			{
				v, err := pr.ReadU8()
				if err != nil {
					return nil, err
				}
				result.Op = v
			}
			{
				if err := pr.EnterRecursive(); err != nil {
					return nil, err
				}
				if err := result.Right.Unpack(pr); err != nil {
					return nil, err
				}
				pr.LeaveRecursive()
			}
			pr.FlushToByteBoundary()
			result.Unknown = pr.ReadRemaining()
			return result, nil
		}
		default: {
			{
				_, err := r.ReadRawBytes(int(length))
				if err != nil {
					return nil, err
				}
			}
			return nil, fmt.Errorf("unknown discriminant %d", disc)
		}
	}
}

