// Code generated by vexilc. DO NOT EDIT.
// Source: test.escapes

package escapes

import vexil "github.com/vexil-lang/vexil/packages/runtime-go"

var SchemaHash = [32]byte{0xea, 0xf3, 0xe6, 0x0a, 0x27, 0xa7, 0xed, 0x56, 0x7c, 0xf6, 0xd7, 0x08, 0x9b, 0x74, 0x29, 0xd4, 0xd2, 0xad, 0x95, 0x7a, 0xfb, 0xe7, 0x08, 0x80, 0x18, 0x01, 0x5e, 0x8d, 0x0d, 0x96, 0xf7, 0xd2}

// ── Escapes ──
type Escapes struct {
	A string
	Unknown []byte
}

func (m *Escapes) Pack(w *vexil.BitWriter) error {
	w.WriteString(m.A)
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *Escapes) Unpack(r *vexil.BitReader) error {
	{
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.A = v
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}


// ── EmptyDoc ──
type EmptyDoc struct {
	B uint8
	Unknown []byte
}

func (m *EmptyDoc) Pack(w *vexil.BitWriter) error {
	w.WriteU8(m.B)
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *EmptyDoc) Unpack(r *vexil.BitReader) error {
	{
		v, err := r.ReadU8()
		if err != nil {
			return err
		}
		m.B = v
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}

