// Code generated by vexilc. DO NOT EDIT.
// Source: test.evolution.append

package append

import vexil "github.com/vexil-lang/vexil/packages/runtime-go"

var SchemaHash = [32]byte{0xf8, 0xb1, 0xdc, 0x0f, 0x53, 0xff, 0x64, 0x6e, 0xd7, 0x81, 0xc9, 0xf7, 0x39, 0x2a, 0x31, 0x85, 0xe6, 0x21, 0xa7, 0xd7, 0x2a, 0xc8, 0x70, 0x9f, 0x25, 0xd1, 0x21, 0x89, 0xa4, 0x69, 0x71, 0x3a}
const SchemaVersion = "1.0.0"

// ── HeaderV1 ──
type HeaderV1 struct {
	Kind uint8
	Status uint8
	Unknown []byte
}

func (m *HeaderV1) Pack(w *vexil.BitWriter) error {
	w.WriteU8(m.Kind)
	w.WriteU8(m.Status)
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *HeaderV1) Unpack(r *vexil.BitReader) error {
	{
		v, err := r.ReadU8()
		if err != nil {
			return err
		}
		m.Kind = v
	}
	{
		v, err := r.ReadU8()
		if err != nil {
			return err
		}
		m.Status = v
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}


// ── HeaderV2 ──
type HeaderV2 struct {
	Kind uint8
	Status uint8
	Flags uint16
	Unknown []byte
}

func (m *HeaderV2) Pack(w *vexil.BitWriter) error {
	w.WriteU8(m.Kind)
	w.WriteU8(m.Status)
	w.WriteU16(m.Flags)
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *HeaderV2) Unpack(r *vexil.BitReader) error {
	{
		v, err := r.ReadU8()
		if err != nil {
			return err
		}
		m.Kind = v
	}
	{
		v, err := r.ReadU8()
		if err != nil {
			return err
		}
		m.Status = v
	}
	{
		v, err := r.ReadU16()
		if err != nil {
			return err
		}
		m.Flags = v
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}

