// Code generated by vexilc. DO NOT EDIT.
// Source: test.empty.optionals

package optionals

import vexil "github.com/vexil-lang/vexil/packages/runtime-go"

var SchemaHash = [32]byte{0x97, 0x11, 0x67, 0xf9, 0x7a, 0xc2, 0x7a, 0xdd, 0xd0, 0x04, 0xd9, 0xee, 0x7f, 0x28, 0x66, 0xd8, 0x38, 0x00, 0x0b, 0xd8, 0x04, 0xc1, 0x61, 0xc5, 0x34, 0x53, 0xe8, 0x35, 0x51, 0x01, 0x42, 0x60}

// ── WithOptionals ──
type WithOptionals struct {
	Name *string
	Value *uint32
	Flag *bool
	Unknown []byte
}

func (m *WithOptionals) Pack(w *vexil.BitWriter) error {
	w.WriteBool(m.Name != nil)
	w.FlushToByteBoundary()
	if m.Name != nil {
		w.WriteString(*m.Name)
	}
	w.WriteBool(m.Value != nil)
	w.FlushToByteBoundary()
	if m.Value != nil {
		w.WriteU32(*m.Value)
	}
	w.WriteBool(m.Flag != nil)
	if m.Flag != nil {
		w.WriteBool(*m.Flag)
	}
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *WithOptionals) Unpack(r *vexil.BitReader) error {
	{
		present, err := r.ReadBool()
		if err != nil {
			return err
		}
		r.FlushToByteBoundary()
		if present {
			var optVal string
			{
				v, err := r.ReadString()
				if err != nil {
					return err
				}
				optVal = v
			}
			m.Name = &optVal
		}
	}
	{
		present, err := r.ReadBool()
		if err != nil {
			return err
		}
		r.FlushToByteBoundary()
		if present {
			var optVal uint32
			{
				v, err := r.ReadU32()
				if err != nil {
					return err
				}
				optVal = v
			}
			m.Value = &optVal
		}
	}
	{
		present, err := r.ReadBool()
		if err != nil {
			return err
		}
		if present {
			var optVal bool
			{
				v, err := r.ReadBool()
				if err != nil {
					return err
				}
				optVal = v
			}
			m.Flag = &optVal
		}
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}


// ── NestedOptional ──
type NestedOptional struct {
	Inner **uint32
	Unknown []byte
}

func (m *NestedOptional) Pack(w *vexil.BitWriter) error {
	w.WriteBool(m.Inner != nil)
	w.FlushToByteBoundary()
	if m.Inner != nil {
		w.WriteBool(*m.Inner != nil)
		w.FlushToByteBoundary()
		if *m.Inner != nil {
			w.WriteU32(**m.Inner)
		}
	}
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *NestedOptional) Unpack(r *vexil.BitReader) error {
	{
		present, err := r.ReadBool()
		if err != nil {
			return err
		}
		r.FlushToByteBoundary()
		if present {
			var optVal *uint32
			{
				present, err := r.ReadBool()
				if err != nil {
					return err
				}
				r.FlushToByteBoundary()
				if present {
					var optVal uint32
					{
						v, err := r.ReadU32()
						if err != nil {
							return err
						}
						optVal = v
					}
					optVal = &optVal
				}
			}
			m.Inner = &optVal
		}
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}


// ── AllEmpty ──
type AllEmpty struct {
	A *string
	B *uint32
	C *bool
	Unknown []byte
}

func (m *AllEmpty) Pack(w *vexil.BitWriter) error {
	w.WriteBool(m.A != nil)
	w.FlushToByteBoundary()
	if m.A != nil {
		w.WriteString(*m.A)
	}
	w.WriteBool(m.B != nil)
	w.FlushToByteBoundary()
	if m.B != nil {
		w.WriteU32(*m.B)
	}
	w.WriteBool(m.C != nil)
	if m.C != nil {
		w.WriteBool(*m.C)
	}
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *AllEmpty) Unpack(r *vexil.BitReader) error {
	{
		present, err := r.ReadBool()
		if err != nil {
			return err
		}
		r.FlushToByteBoundary()
		if present {
			var optVal string
			{
				v, err := r.ReadString()
				if err != nil {
					return err
				}
				optVal = v
			}
			m.A = &optVal
		}
	}
	{
		present, err := r.ReadBool()
		if err != nil {
			return err
		}
		r.FlushToByteBoundary()
		if present {
			var optVal uint32
			{
				v, err := r.ReadU32()
				if err != nil {
					return err
				}
				optVal = v
			}
			m.B = &optVal
		}
	}
	{
		present, err := r.ReadBool()
		if err != nil {
			return err
		}
		if present {
			var optVal bool
			{
				v, err := r.ReadBool()
				if err != nil {
					return err
				}
				optVal = v
			}
			m.C = &optVal
		}
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}

