// Code generated by vexilc. DO NOT EDIT.
// Source: test.nested.schemas

package schemas

import vexil "github.com/vexil-lang/vexil/packages/runtime-go"

var SchemaHash = [32]byte{0x11, 0x4e, 0x60, 0xd2, 0x61, 0x98, 0x1e, 0xde, 0x1b, 0x91, 0xfc, 0x98, 0x11, 0x18, 0xaa, 0xa3, 0x93, 0xe2, 0xc9, 0x29, 0x15, 0xad, 0x63, 0xcd, 0x51, 0xa5, 0x3d, 0x96, 0xdf, 0x59, 0x93, 0xd5}

// ── Coord ──
type Coord struct {
	X int32
	Y int32
	Unknown []byte
}

func (m *Coord) Pack(w *vexil.BitWriter) error {
	w.WriteI32(m.X)
	w.WriteI32(m.Y)
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *Coord) Unpack(r *vexil.BitReader) error {
	{
		v, err := r.ReadI32()
		if err != nil {
			return err
		}
		m.X = v
	}
	{
		v, err := r.ReadI32()
		if err != nil {
			return err
		}
		m.Y = v
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}


// ── Rect ──
type Rect struct {
	Origin Coord
	Size Coord
	Unknown []byte
}

func (m *Rect) Pack(w *vexil.BitWriter) error {
	if err := w.EnterRecursive(); err != nil {
		return err
	}
	if err := m.Origin.Pack(w); err != nil {
		return err
	}
	w.LeaveRecursive()
	if err := w.EnterRecursive(); err != nil {
		return err
	}
	if err := m.Size.Pack(w); err != nil {
		return err
	}
	w.LeaveRecursive()
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *Rect) Unpack(r *vexil.BitReader) error {
	{
		if err := r.EnterRecursive(); err != nil {
			return err
		}
		if err := m.Origin.Unpack(r); err != nil {
			return err
		}
		r.LeaveRecursive()
	}
	{
		if err := r.EnterRecursive(); err != nil {
			return err
		}
		if err := m.Size.Unpack(r); err != nil {
			return err
		}
		r.LeaveRecursive()
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}


// ── Canvas ──
type Canvas struct {
	Bounds Rect
	Name string
	Layers []Rect
	Unknown []byte
}

func (m *Canvas) Pack(w *vexil.BitWriter) error {
	if err := w.EnterRecursive(); err != nil {
		return err
	}
	if err := m.Bounds.Pack(w); err != nil {
		return err
	}
	w.LeaveRecursive()
	w.WriteString(m.Name)
	w.WriteLeb128(uint64(len(m.Layers)))
	for _, item := range m.Layers {
		if err := w.EnterRecursive(); err != nil {
			return err
		}
		if err := item.Pack(w); err != nil {
			return err
		}
		w.LeaveRecursive()
	}
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *Canvas) Unpack(r *vexil.BitReader) error {
	{
		if err := r.EnterRecursive(); err != nil {
			return err
		}
		if err := m.Bounds.Unpack(r); err != nil {
			return err
		}
		r.LeaveRecursive()
	}
	{
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Name = v
	}
	{
		arrLen, err := r.ReadLeb128(4)
		if err != nil {
			return err
		}
		m.Layers = make([]Rect, arrLen)
		for i := uint64(0); i < arrLen; i++ {
			{
				if err := r.EnterRecursive(); err != nil {
					return err
				}
				if err := m.Layers[i].Unpack(r); err != nil {
					return err
				}
				r.LeaveRecursive()
			}
		}
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}

