// Code generated by vexilc. DO NOT EDIT.
// Source: test.recursive.depth

package depth

import vexil "github.com/vexil-lang/vexil/packages/runtime-go"

var SchemaHash = [32]byte{0x4f, 0x25, 0x39, 0x5a, 0x3e, 0x94, 0xda, 0xf1, 0x8a, 0xee, 0xff, 0x59, 0x90, 0x93, 0x11, 0xaa, 0x20, 0x39, 0xa6, 0x36, 0x6b, 0xe5, 0x3c, 0xb0, 0x16, 0x54, 0x23, 0x6c, 0x09, 0x44, 0x4d, 0x73}

// ── TreeNode ──
type TreeNode struct {
	Value uint32
	Children []TreeNode
	Unknown []byte
}

func (m *TreeNode) Pack(w *vexil.BitWriter) error {
	w.WriteU32(m.Value)
	w.WriteLeb128(uint64(len(m.Children)))
	for _, item := range m.Children {
		if err := w.EnterRecursive(); err != nil {
			return err
		}
		if err := item.Pack(w); err != nil {
			return err
		}
		w.LeaveRecursive()
	}
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *TreeNode) Unpack(r *vexil.BitReader) error {
	{
		v, err := r.ReadU32()
		if err != nil {
			return err
		}
		m.Value = v
	}
	{
		arrLen, err := r.ReadLeb128(4)
		if err != nil {
			return err
		}
		m.Children = make([]TreeNode, arrLen)
		for i := uint64(0); i < arrLen; i++ {
			{
				if err := r.EnterRecursive(); err != nil {
					return err
				}
				if err := m.Children[i].Unpack(r); err != nil {
					return err
				}
				r.LeaveRecursive()
			}
		}
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}


// ── LinkedList ──
type LinkedList struct {
	Value int64
	Next *LinkedList
	Unknown []byte
}

func (m *LinkedList) Pack(w *vexil.BitWriter) error {
	w.WriteI64(m.Value)
	w.WriteBool(m.Next != nil)
	w.FlushToByteBoundary()
	if m.Next != nil {
		if err := w.EnterRecursive(); err != nil {
			return err
		}
		if err := m.Next.Pack(w); err != nil {
			return err
		}
		w.LeaveRecursive()
	}
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *LinkedList) Unpack(r *vexil.BitReader) error {
	{
		v, err := r.ReadI64()
		if err != nil {
			return err
		}
		m.Value = v
	}
	{
		present, err := r.ReadBool()
		if err != nil {
			return err
		}
		r.FlushToByteBoundary()
		if present {
			var optVal LinkedList
			{
				if err := r.EnterRecursive(); err != nil {
					return err
				}
				if err := optVal.Unpack(r); err != nil {
					return err
				}
				r.LeaveRecursive()
			}
			m.Next = &optVal
		}
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}

