// Code generated by vexilc. DO NOT EDIT.
// Source: test.evolution.deprecate

package deprecate

import vexil "github.com/vexil-lang/vexil/packages/runtime-go"

var SchemaHash = [32]byte{0x9c, 0x01, 0x2f, 0x63, 0xdf, 0x9c, 0xe2, 0x4a, 0xc7, 0xf3, 0xe8, 0xf3, 0xb9, 0xae, 0xf9, 0xfd, 0xe8, 0xca, 0x7d, 0x82, 0x0b, 0x60, 0xd0, 0x8b, 0x23, 0x72, 0xdb, 0x8e, 0x8c, 0x1f, 0xa3, 0x80}
const SchemaVersion = "2.0.0"

// ── Config ──
type Config struct {
	Name string
	OldName string
	Timeout uint32
	Unknown []byte
}

func (m *Config) Pack(w *vexil.BitWriter) error {
	w.WriteString(m.Name)
	w.WriteString(m.OldName)
	w.WriteU32(m.Timeout)
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *Config) Unpack(r *vexil.BitReader) error {
	{
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Name = v
	}
	{
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.OldName = v
	}
	{
		v, err := r.ReadU32()
		if err != nil {
			return err
		}
		m.Timeout = v
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}

