// Code generated by vexilc. DO NOT EDIT.
// Source: test.delta.message

package message

import vexil "github.com/vexil-lang/vexil/packages/runtime-go"

var SchemaHash = [32]byte{0x07, 0x20, 0xc0, 0x79, 0x18, 0xe4, 0x24, 0xcf, 0xdb, 0xde, 0x48, 0xe0, 0xdb, 0x86, 0xb5, 0xb2, 0x2e, 0x55, 0x23, 0x7f, 0xf9, 0x9c, 0xe5, 0xd7, 0x95, 0x14, 0x35, 0x9e, 0x8f, 0xab, 0x99, 0x67}

// ── Telemetry ──
type Telemetry struct {
	Timestamp int64
	Value float32
	Label string
	Count uint32
	Unknown []byte
}

func (m *Telemetry) Pack(w *vexil.BitWriter) error {
	w.WriteZigZag(int64(m.Timestamp), 64)
	w.WriteF32(m.Value)
	w.WriteString(m.Label)
	w.WriteLeb128(uint64(m.Count))
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *Telemetry) Unpack(r *vexil.BitReader) error {
	{
		raw, err := r.ReadZigZag(64, 10)
		if err != nil {
			return err
		}
		m.Timestamp = int64(raw)
	}
	{
		v, err := r.ReadF32()
		if err != nil {
			return err
		}
		m.Value = v
	}
	{
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Label = v
	}
	{
		raw, err := r.ReadLeb128(5)
		if err != nil {
			return err
		}
		m.Count = uint32(raw)
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}

type TelemetryEncoder struct {
	prevTimestamp int64
	prevValue float32
	prevCount uint32
}

func NewTelemetryEncoder() *TelemetryEncoder {
	return &TelemetryEncoder{}
}

func (e *TelemetryEncoder) Pack(val *Telemetry, w *vexil.BitWriter) error {
	deltaTimestamp := int64(val.Timestamp - e.prevTimestamp)
	w.WriteZigZag(int64(deltaTimestamp), 64)
	e.prevTimestamp = val.Timestamp
	deltaValue := float32(val.Value - e.prevValue)
	w.WriteF32(deltaValue)
	e.prevValue = val.Value
	w.WriteString(val.Label)
	deltaCount := uint32(val.Count - e.prevCount)
	w.WriteLeb128(uint64(deltaCount))
	e.prevCount = val.Count
	w.FlushToByteBoundary()
	if len(val.Unknown) > 0 {
		w.WriteRawBytes(val.Unknown)
	}
	return nil
}

func (e *TelemetryEncoder) Reset() {
	e.prevTimestamp = 0
	e.prevValue = 0.0
	e.prevCount = 0
}

type TelemetryDecoder struct {
	prevTimestamp int64
	prevValue float32
	prevCount uint32
}

func NewTelemetryDecoder() *TelemetryDecoder {
	return &TelemetryDecoder{}
}

func (d *TelemetryDecoder) Unpack(r *vexil.BitReader) (*Telemetry, error) {
	m := &Telemetry{}
	var deltaTimestamp int64
	{
		raw, err := r.ReadZigZag(64, 10)
		if err != nil {
			return nil, err
		}
		deltaTimestamp = int64(raw)
	}
	m.Timestamp = int64(d.prevTimestamp + deltaTimestamp)
	d.prevTimestamp = m.Timestamp
	var deltaValue float32
	{
		v, err := r.ReadF32()
		if err != nil {
			return nil, err
		}
		deltaValue = v
	}
	m.Value = float32(d.prevValue + deltaValue)
	d.prevValue = m.Value
	{
		v, err := r.ReadString()
		if err != nil {
			return nil, err
		}
		m.Label = v
	}
	var deltaCount uint32
	{
		raw, err := r.ReadLeb128(5)
		if err != nil {
			return nil, err
		}
		deltaCount = uint32(raw)
	}
	m.Count = uint32(d.prevCount + deltaCount)
	d.prevCount = m.Count
	r.FlushToByteBoundary()
	m.Unknown = nil
	return m, nil
}

func (d *TelemetryDecoder) Reset() {
	d.prevTimestamp = 0
	d.prevValue = 0.0
	d.prevCount = 0
}

