// Code generated by vexilc. DO NOT EDIT.
// Source: test.newtype_map_key

package newtype_map_key

import (
	"sort"

	vexil "github.com/vexil-lang/vexil/packages/runtime-go"
)

var SchemaHash = [32]byte{0x18, 0xfd, 0xc9, 0xe0, 0x68, 0x83, 0x2d, 0x02, 0x03, 0x88, 0x9a, 0x40, 0x58, 0x69, 0xe8, 0xd5, 0xf3, 0xc4, 0x44, 0xec, 0x31, 0xe3, 0x08, 0x0b, 0x7b, 0x3b, 0x56, 0x02, 0x9d, 0xc1, 0x41, 0x81}
const SchemaVersion = "1.0.0"

// ── UserId ──
type UserId uint32

func PackUserId(v UserId, w *vexil.BitWriter) error {
	w.WriteU32(uint32(v))
	return nil
}

func UnpackUserId(r *vexil.BitReader) (UserId, error) {
	var inner uint32
	{
		v, err := r.ReadU32()
		if err != nil {
			return UserId(inner), err
		}
		inner = v
	}
	return UserId(inner), nil
}


// ── Label ──
type Label string

func PackLabel(v Label, w *vexil.BitWriter) error {
	w.WriteString(string(v))
	return nil
}

func UnpackLabel(r *vexil.BitReader) (Label, error) {
	var inner string
	{
		v, err := r.ReadString()
		if err != nil {
			return Label(inner), err
		}
		inner = v
	}
	return Label(inner), nil
}


// ── UserProfile ──
type UserProfile struct {
	ID UserId
	Friends map[UserId]string
	Tags map[Label]uint32
	Unknown []byte
}

func (m *UserProfile) Pack(w *vexil.BitWriter) error {
	PackUserId(m.ID, w)
	w.WriteLeb128(uint64(len(m.Friends)))
	mapKeysmFriends := make([]UserId, 0, len(m.Friends))
	for key := range m.Friends {
		mapKeysmFriends = append(mapKeysmFriends, key)
	}
	sort.Slice(mapKeysmFriends, func(i, j int) bool {
		return mapKeysmFriends[i] < mapKeysmFriends[j]
	})
	for _, mapK := range mapKeysmFriends {
		mapV := m.Friends[mapK]
		PackUserId(mapK, w)
		w.WriteString(mapV)
	}
	w.WriteLeb128(uint64(len(m.Tags)))
	mapKeysmTags := make([]Label, 0, len(m.Tags))
	for key := range m.Tags {
		mapKeysmTags = append(mapKeysmTags, key)
	}
	sort.Slice(mapKeysmTags, func(i, j int) bool {
		return mapKeysmTags[i] < mapKeysmTags[j]
	})
	for _, mapK := range mapKeysmTags {
		mapV := m.Tags[mapK]
		PackLabel(mapK, w)
		w.WriteU32(mapV)
	}
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *UserProfile) Unpack(r *vexil.BitReader) error {
	{
		v, err := UnpackUserId(r)
		if err != nil {
			return err
		}
		m.ID = v
	}
	{
		mapLen, err := r.ReadLeb128(4)
		if err != nil {
			return err
		}
		m.Friends = make(map[UserId]string, mapLen)
		for i := uint64(0); i < mapLen; i++ {
			var mapKey UserId
			var mapVal string
			{
				v, err := UnpackUserId(r)
				if err != nil {
					return err
				}
				mapKey = v
			}
			{
				v, err := r.ReadString()
				if err != nil {
					return err
				}
				mapVal = v
			}
			m.Friends[mapKey] = mapVal
		}
	}
	{
		mapLen, err := r.ReadLeb128(4)
		if err != nil {
			return err
		}
		m.Tags = make(map[Label]uint32, mapLen)
		for i := uint64(0); i < mapLen; i++ {
			var mapKey Label
			var mapVal uint32
			{
				v, err := UnpackLabel(r)
				if err != nil {
					return err
				}
				mapKey = v
			}
			{
				v, err := r.ReadU32()
				if err != nil {
					return err
				}
				mapVal = v
			}
			m.Tags[mapKey] = mapVal
		}
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}

