// Code generated by vexilc. DO NOT EDIT.
// Source: test.reserved_variants

package reserved_variants

import vexil "github.com/vexil-lang/vexil/packages/runtime-go"

var SchemaHash = [32]byte{0xaa, 0x41, 0xda, 0x90, 0xb9, 0xc2, 0xcb, 0xbb, 0x8d, 0x92, 0x3f, 0xbf, 0x43, 0xde, 0xe2, 0x73, 0xe8, 0xfd, 0x96, 0x6b, 0x8d, 0x0b, 0x0c, 0x60, 0x02, 0xb2, 0xeb, 0x1d, 0x8e, 0xcd, 0xe1, 0x7a}
const SchemaVersion = "1.0.0"

// ── ImageProtocol ──
type ImageProtocol int

const (
	ImageProtocolNone ImageProtocol = 0
	ImageProtocolSixel ImageProtocol = 1
	ImageProtocolKitty ImageProtocol = 2
)

func (s ImageProtocol) Pack(w *vexil.BitWriter) error {
	w.WriteBits(uint64(s), 2)
	return nil
}

func (s *ImageProtocol) Unpack(r *vexil.BitReader) error {
	v, err := r.ReadBits(2)
	if err != nil {
		return err
	}
	*s = ImageProtocol(v)
	return nil
}


// ── ParseResult ──
type ParseResult int

const (
	ParseResultOk ParseResult = 0
	ParseResultErr ParseResult = 1
	ParseResultSome ParseResult = 2
	ParseResultNone ParseResult = 3
)

func (s ParseResult) Pack(w *vexil.BitWriter) error {
	w.WriteBits(uint64(s), 2)
	return nil
}

func (s *ParseResult) Unpack(r *vexil.BitReader) error {
	v, err := r.ReadBits(2)
	if err != nil {
		return err
	}
	*s = ParseResult(v)
	return nil
}

