// Code generated by vexilc. DO NOT EDIT.
// Source: test.aliases

package aliases

import vexil "github.com/vexil-lang/vexil/packages/runtime-go"

var SchemaHash = [32]byte{0x9d, 0xa2, 0x96, 0xfe, 0x02, 0xb6, 0x44, 0xb6, 0xb4, 0x94, 0xa1, 0x48, 0x5d, 0xa7, 0xd5, 0xab, 0xb4, 0xa8, 0x59, 0xb6, 0xf5, 0xba, 0xf9, 0x50, 0xb3, 0x21, 0x93, 0x65, 0xbf, 0xfd, 0x49, 0x29}

// ── GameState ──
type GameState struct {
	PlayerID uint64
	Score int32
	Unknown []byte
}

func (m *GameState) Pack(w *vexil.BitWriter) error {
	w.WriteU64(m.PlayerID)
	w.WriteI32(m.Score)
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}
func (m *GameState) Unpack(r *vexil.BitReader) error {
	{
		v, err := r.ReadU64()
		if err != nil {
			return err
		}
		m.PlayerID = v
	}
	{
		v, err := r.ReadI32()
		if err != nil {
			return err
		}
		m.Score = v
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}
