// Code generated by vexilc. DO NOT EDIT.
// Source: test.set

package set

import vexil "github.com/vexil-lang/vexil/packages/runtime-go"

var SchemaHash = [32]byte{0x86, 0x3c, 0x08, 0x4e, 0x75, 0x4f, 0x2a, 0xdf, 0x37, 0x16, 0x57, 0x6e, 0xe8, 0xfa, 0xd1, 0x44, 0xd1, 0xfb, 0xb4, 0xe7, 0xce, 0x9a, 0x1e, 0xa8, 0x6c, 0x80, 0x95, 0x96, 0xe9, 0x25, 0x78, 0x1e}

// ── Tags ──
type Tags struct {
	Names map[string]struct{}
	Unknown []byte
}

func (m *Tags) Pack(w *vexil.BitWriter) error {
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *Tags) Unpack(r *vexil.BitReader) error {
	{
		setLen, err := r.ReadLeb128(4)
		if err != nil {
			return err
		}
		m.Names = make(map[string]struct{}, setLen)
		for i := uint64(0); i < setLen; i++ {
			var item string
			{
				v, err := r.ReadString()
				if err != nil {
					return err
				}
				item = v
			}
			m.Names[item] = struct{}{}
		}
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}

