// Code generated by vexilc. DO NOT EDIT.
// Source: test.bits

package bits

import vexil "github.com/vexil-lang/vexil/packages/runtime-go"

var SchemaHash = [32]byte{0x99, 0x52, 0xae, 0x70, 0x6e, 0x9b, 0xdc, 0x5d, 0x2d, 0x89, 0x5e, 0xc4, 0x65, 0x9d, 0x40, 0x0b, 0xc3, 0xd4, 0xb8, 0xc7, 0x49, 0x0b, 0xc0, 0x32, 0x8f, 0xce, 0xfc, 0x99, 0x47, 0xc9, 0x0f, 0x1d}

// ── Header ──
type Header struct {
	Perms uint8
	Unknown []byte
}

func (m *Header) Pack(w *vexil.BitWriter) error {
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *Header) Unpack(r *vexil.BitReader) error {
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}

