// Code generated by vexilc. DO NOT EDIT.
// Source: test.concrete_type_aliases

package concrete_type_aliases

import (
	"sort"

	vexil "github.com/vexil-lang/vexil/packages/runtime-go"
)

var SchemaHash = [32]byte{0x34, 0xf7, 0x2b, 0xbd, 0x77, 0x6a, 0x0f, 0x2d, 0xcb, 0x4a, 0xae, 0xea, 0xf9, 0xe3, 0xbc, 0x15, 0xed, 0x6b, 0xa6, 0x81, 0xac, 0x4d, 0x35, 0xbe, 0x2f, 0xf5, 0xa3, 0x4d, 0x8f, 0x0e, 0xb2, 0x34}

// ── Item ──
type Item struct {
	ID uint32
	Unknown []byte
}

func (m *Item) Pack(w *vexil.BitWriter) error {
	w.WriteU32(m.ID)
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *Item) Unpack(r *vexil.BitReader) error {
	{
		v, err := r.ReadU32()
		if err != nil {
			return err
		}
		m.ID = v
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}


// ── AliasUser ──
type AliasUser struct {
	Count uint32
	Label string
	Direction [3]float32
	Permissions uint8
	Item Item
	Names []string
	Grid [4]uint16
	Lookup map[string]*uint32
	Tags map[string]struct{}
	Outcome struct { Ok *[]string; Err *string }
	Unknown []byte
}

func (m *AliasUser) Pack(w *vexil.BitWriter) error {
	w.WriteU32(m.Count)
	w.WriteString(m.Label)
	for _, item := range m.Direction {
		w.WriteF32(item)
	}
	w.WriteBits(uint64(m.Permissions), 2)
	if err := w.EnterRecursive(); err != nil {
		return err
	}
	if err := m.Item.Pack(w); err != nil {
		return err
	}
	w.LeaveRecursive()
	w.WriteLeb128(uint64(len(m.Names)))
	for _, item := range m.Names {
		w.WriteString(item)
	}
	for _, item := range m.Grid {
		w.WriteU16(item)
	}
	w.WriteLeb128(uint64(len(m.Lookup)))
	mapKeysmLookup := make([]string, 0, len(m.Lookup))
	for key := range m.Lookup {
		mapKeysmLookup = append(mapKeysmLookup, key)
	}
	sort.Slice(mapKeysmLookup, func(i, j int) bool {
		return mapKeysmLookup[i] < mapKeysmLookup[j]
	})
	for _, mapK := range mapKeysmLookup {
		mapV := m.Lookup[mapK]
		w.WriteString(mapK)
		w.WriteBool(mapV != nil)
		if mapV != nil {
			w.FlushToByteBoundary()
			w.WriteU32((*mapV))
		}
	}
	w.WriteLeb128(uint64(len(m.Tags)))
	setKeysmTags := make([]string, 0, len(m.Tags))
	for key := range m.Tags {
		setKeysmTags = append(setKeysmTags, key)
	}
	sort.Slice(setKeysmTags, func(i, j int) bool {
		return setKeysmTags[i] < setKeysmTags[j]
	})
	for _, item := range setKeysmTags {
		w.WriteString(item)
	}
	if m.Outcome.Ok != nil {
		w.WriteBool(true)
		w.WriteLeb128(uint64(len((*m.Outcome.Ok))))
		for _, item := range (*m.Outcome.Ok) {
			w.WriteString(item)
		}
	} else {
		w.WriteBool(false)
		w.WriteString((*m.Outcome.Err))
	}
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *AliasUser) Unpack(r *vexil.BitReader) error {
	{
		v, err := r.ReadU32()
		if err != nil {
			return err
		}
		m.Count = v
	}
	{
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Label = v
	}
	m.Direction = [3]float32{}
	for i := 0; i < 3; i++ {
		{
			v, err := r.ReadF32()
			if err != nil {
				return err
			}
			m.Direction[i] = v
		}
	}
	{
		v, err := r.ReadBits(2)
		if err != nil {
			return err
		}
		m.Permissions = uint8(v)
	}
	{
		if err := r.EnterRecursive(); err != nil {
			return err
		}
		if err := m.Item.Unpack(r); err != nil {
			return err
		}
		r.LeaveRecursive()
	}
	{
		arrLen, err := r.ReadLeb128(4)
		if err != nil {
			return err
		}
		m.Names = make([]string, arrLen)
		for i := uint64(0); i < arrLen; i++ {
			{
				v, err := r.ReadString()
				if err != nil {
					return err
				}
				m.Names[i] = v
			}
		}
	}
	m.Grid = [4]uint16{}
	for i := 0; i < 4; i++ {
		{
			v, err := r.ReadU16()
			if err != nil {
				return err
			}
			m.Grid[i] = v
		}
	}
	{
		mapLen, err := r.ReadLeb128(4)
		if err != nil {
			return err
		}
		m.Lookup = make(map[string]*uint32, mapLen)
		for i := uint64(0); i < mapLen; i++ {
			var mapKey string
			var mapVal *uint32
			{
				v, err := r.ReadString()
				if err != nil {
					return err
				}
				mapKey = v
			}
			{
				present, err := r.ReadBool()
				if err != nil && err != vexil.ErrUnexpectedEOF {
					return err
				}
				if err == nil {
					if present {
						r.FlushToByteBoundary()
						var optVal uint32
						{
							v, err := r.ReadU32()
							if err != nil {
								return err
							}
							optVal = v
						}
						mapVal = &optVal
					}
				}
			}
			m.Lookup[mapKey] = mapVal
		}
	}
	{
		setLen, err := r.ReadLeb128(4)
		if err != nil {
			return err
		}
		m.Tags = make(map[string]struct{}, setLen)
		for i := uint64(0); i < setLen; i++ {
			var item string
			{
				v, err := r.ReadString()
				if err != nil {
					return err
				}
				item = v
			}
			m.Tags[item] = struct{}{}
		}
	}
	{
		isOk, err := r.ReadBool()
		if err != nil {
			return err
		}
		if isOk {
			var m_OutcomeOk []string
			{
				arrLen, err := r.ReadLeb128(4)
				if err != nil {
					return err
				}
				m_OutcomeOk = make([]string, arrLen)
				for i := uint64(0); i < arrLen; i++ {
					{
						v, err := r.ReadString()
						if err != nil {
							return err
						}
						m_OutcomeOk[i] = v
					}
				}
			}
			m.Outcome.Ok = &m_OutcomeOk
		} else {
			var m_OutcomeErr string
			{
				v, err := r.ReadString()
				if err != nil {
					return err
				}
				m_OutcomeErr = v
			}
			m.Outcome.Err = &m_OutcomeErr
		}
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}
