// Code generated by vexilc. DO NOT EDIT.
// Source: test.trait_function_unused_local

package trait_function_unused_local

import vexil "github.com/vexil-lang/vexil/packages/runtime-go"

var SchemaHash = [32]byte{0x72, 0x35, 0x4d, 0xb8, 0xe4, 0x75, 0x16, 0xfd, 0xbb, 0xa5, 0x3a, 0xbc, 0x5f, 0x81, 0xc2, 0x7d, 0x55, 0xa2, 0x6e, 0x58, 0x1a, 0xea, 0xa7, 0x43, 0xcc, 0x5c, 0xbe, 0xf8, 0xe8, 0x5b, 0x96, 0x0d}

// ── Identity ──
type Identity interface {
	Identity(input int32) int32
}

// ── Counter ──
type Counter struct {
	Value int32
	Unknown []byte
}

func (m *Counter) Pack(w *vexil.BitWriter) error {
	w.WriteI32(m.Value)
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *Counter) Unpack(r *vexil.BitReader) error {
	{
		v, err := r.ReadI32()
		if err != nil {
			return err
		}
		m.Value = v
	}
	r.FlushToByteBoundary()
	m.Unknown = nil
	return nil
}


func (m *Counter) Identity(input int32) int32 {
	var unused int32 = input
	_ = unused
	return input
}
var _ Identity = (*Counter)(nil)
