pub mod annotations;
pub mod boxing;
pub mod config;
pub mod delta;
pub mod emit;
pub mod enum_gen;
pub mod flags;
pub mod message;
pub mod newtype;
pub mod types;
pub mod union_gen;

use vexil_lang::ir::{CompiledSchema, ResolvedType, TypeDef, TypeId};

#[derive(Debug, Clone, PartialEq, thiserror::Error)]
pub enum CodegenError {
    #[error("unresolved type {type_id:?} referenced by {referenced_by}")]
    UnresolvedType {
        type_id: TypeId,
        referenced_by: String,
    },
}

pub fn generate(compiled: &CompiledSchema) -> Result<String, CodegenError> {
    // Step 1: Detect recursive types that need Box<T> wrapping.
    let needs_box = boxing::detect_boxing(compiled);

    // Step 2: Create the code writer.
    let mut w = emit::CodeWriter::new();

    // Step 3: Emit header.
    w.line("// Code generated by vexilc. DO NOT EDIT.");
    let ns = compiled.namespace.join(".");
    w.line(&format!("// Source: {ns}"));

    // Step 4: Emit blank line.
    w.blank();

    // Step 5: Check if any type uses Map → emit BTreeMap import.
    if schema_uses_map(compiled) {
        w.line("use std::collections::BTreeMap;");
    }
    w.line("use vexil_runtime::*;");

    // Step 7: Emit blank line.
    w.blank();

    // Step 8: Emit schema version constant if set.
    if let Some(ref version) = compiled.annotations.version {
        w.line(&format!("pub const SCHEMA_VERSION: &str = \"{version}\";"));
    }

    // Step 9: For each declared type, emit the appropriate code.
    for &type_id in &compiled.declarations {
        let typedef =
            compiled
                .registry
                .get(type_id)
                .ok_or_else(|| CodegenError::UnresolvedType {
                    type_id,
                    referenced_by: "declarations".to_string(),
                })?;

        // Emit blank line + section separator comment.
        w.blank();
        let type_name = type_name_of(typedef);
        w.line(&format!("// \u{2500}\u{2500} {type_name} \u{2500}\u{2500}"));

        // Dispatch to the appropriate emitter.
        match typedef {
            TypeDef::Message(msg) => {
                message::emit_message(&mut w, msg, &compiled.registry, &needs_box, type_id);
                delta::emit_delta(&mut w, msg, &compiled.registry);
            }
            TypeDef::Enum(en) => {
                enum_gen::emit_enum(&mut w, en, &compiled.registry);
            }
            TypeDef::Flags(fl) => {
                flags::emit_flags(&mut w, fl, &compiled.registry);
            }
            TypeDef::Union(un) => {
                union_gen::emit_union(&mut w, un, &compiled.registry, &needs_box, type_id);
            }
            TypeDef::Newtype(nt) => {
                newtype::emit_newtype(&mut w, nt, &compiled.registry, &needs_box);
            }
            TypeDef::Config(cfg) => {
                config::emit_config(&mut w, cfg, &compiled.registry, &needs_box);
            }
            _ => {} // non_exhaustive guard
        }
    }

    // Step 10: Return the generated code.
    Ok(w.finish())
}

/// Returns the name of a TypeDef for use in section separator comments.
fn type_name_of(typedef: &TypeDef) -> &str {
    match typedef {
        TypeDef::Message(m) => m.name.as_str(),
        TypeDef::Enum(e) => e.name.as_str(),
        TypeDef::Flags(f) => f.name.as_str(),
        TypeDef::Union(u) => u.name.as_str(),
        TypeDef::Newtype(n) => n.name.as_str(),
        TypeDef::Config(c) => c.name.as_str(),
        _ => "Unknown", // non_exhaustive guard
    }
}

/// Returns true if any declaration in the schema uses a Map type (recursively).
fn schema_uses_map(compiled: &CompiledSchema) -> bool {
    for &type_id in &compiled.declarations {
        if let Some(typedef) = compiled.registry.get(type_id) {
            if typedef_uses_map(typedef) {
                return true;
            }
        }
    }
    false
}

fn typedef_uses_map(typedef: &TypeDef) -> bool {
    match typedef {
        TypeDef::Message(msg) => msg
            .fields
            .iter()
            .any(|f| resolved_type_uses_map(&f.resolved_type)),
        TypeDef::Union(un) => un.variants.iter().any(|v| {
            v.fields
                .iter()
                .any(|f| resolved_type_uses_map(&f.resolved_type))
        }),
        TypeDef::Config(cfg) => cfg
            .fields
            .iter()
            .any(|f| resolved_type_uses_map(&f.resolved_type)),
        TypeDef::Newtype(nt) => resolved_type_uses_map(&nt.inner_type),
        _ => false,
    }
}

fn resolved_type_uses_map(ty: &ResolvedType) -> bool {
    match ty {
        ResolvedType::Map(_, _) => true,
        ResolvedType::Optional(inner) => resolved_type_uses_map(inner),
        ResolvedType::Array(inner) => resolved_type_uses_map(inner),
        ResolvedType::Result(ok, err) => resolved_type_uses_map(ok) || resolved_type_uses_map(err),
        _ => false,
    }
}
