// Code generated by vexilc. DO NOT EDIT.
// Source: system.monitor

use vexil_runtime::*;

pub const SCHEMA_HASH: [u8; 32] = [0x73, 0xdd, 0xeb, 0xf5, 0xfc, 0x46, 0x72, 0x36, 0xc1, 0x42, 0x71, 0x3f, 0x69, 0x79, 0xd9, 0x54, 0x06, 0xd9, 0x43, 0xdb, 0xa9, 0x89, 0x34, 0x29, 0xa8, 0xf9, 0xa0, 0x2d, 0xb9, 0xf3, 0xef, 0x4e];

// ── CpuStatus ──
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u64)]
pub enum CpuStatus {
    Normal = 0_u64,
    Degraded = 1_u64,
    Critical = 2_u64,
}

impl vexil_runtime::Pack for CpuStatus {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        let disc: u64 = match self {
            Self::Normal => 0_u64,
            Self::Degraded => 1_u64,
            Self::Critical => 2_u64,
        };
        w.write_bits(disc, 2_u8);
        Ok(())
    }
}

impl vexil_runtime::Unpack for CpuStatus {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let disc = r.read_bits(2_u8)?;
        match disc {
            0_u64 => Ok(Self::Normal),
            1_u64 => Ok(Self::Degraded),
            2_u64 => Ok(Self::Critical),
            _ => Err(vexil_runtime::DecodeError::UnknownEnumVariant { type_name: "CpuStatus", value: disc }),
        }
    }
}


// ── SystemSnapshot ──
#[derive(Debug, Clone, PartialEq)]
pub struct SystemSnapshot {
    pub timestamp_ms: i64,
    pub hostname: String,
    pub cpu_usage: u8,
    pub cpu_count: u8,
    pub per_core_usage: Vec<u8>,
    pub memory_used_mb: u32,
    pub memory_total_mb: u32,
    pub cpu_status: CpuStatus,
}

impl vexil_runtime::Pack for SystemSnapshot {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_i64(self.timestamp_ms);
        w.write_string(&self.hostname);
        w.write_u8(self.cpu_usage);
        w.write_u8(self.cpu_count);
        w.write_leb128(self.per_core_usage.len() as u64);
        for item in &self.per_core_usage {
            w.write_u8(*item);
        }
        w.write_u32(self.memory_used_mb);
        w.write_u32(self.memory_total_mb);
        w.enter_recursive()?;
        self.cpu_status.pack(w)?;
        w.leave_recursive();
        w.flush_to_byte_boundary();
        Ok(())
    }
}

impl vexil_runtime::Unpack for SystemSnapshot {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let timestamp_ms = r.read_i64()?;
        let hostname = r.read_string()?;
        let cpu_usage = r.read_u8()?;
        let cpu_count = r.read_u8()?;
        let per_core_usage_len = r.read_leb128(10_u8)? as usize;
        let mut per_core_usage = Vec::with_capacity(per_core_usage_len);
        for _ in 0..per_core_usage_len {
            let per_core_usage_item = r.read_u8()?;
            per_core_usage.push(per_core_usage_item);
        }
        let memory_used_mb = r.read_u32()?;
        let memory_total_mb = r.read_u32()?;
        r.enter_recursive()?;
        let cpu_status = vexil_runtime::Unpack::unpack(r)?;
        r.leave_recursive();
        r.flush_to_byte_boundary();
        Ok(Self {
            timestamp_ms,
            hostname,
            cpu_usage,
            cpu_count,
            per_core_usage,
            memory_used_mb,
            memory_total_mb,
            cpu_status,
        })
    }
}

