# Code generated by vexilc. DO NOT EDIT.
# Source: sensor.telemetry

from __future__ import annotations
from dataclasses import dataclass

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import BitWriter as _BitWriter, BitReader as _BitReader

SCHEMA_HASH: tuple[int, ...] = (0x62, 0x19, 0xa3, 0xc2, 0x34, 0x2a, 0xd0, 0xaf, 0x3e, 0xaa, 0xbe, 0x11, 0xca, 0xe9, 0x6c, 0x23, 0x76, 0x6e, 0x62, 0x27, 0xb4, 0xc1, 0xce, 0x0f, 0x2e, 0x5d, 0xbd, 0x08, 0xdf, 0xec, 0x70, 0x93)


# ---------- DeviceStatus ----------
class DeviceStatus(int):
    ONLINE = 0
    DEGRADED = 1
    OFFLINE = 2
    ERROR = 3

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_bits(int(self), 2)

    @staticmethod
    def decode(data: bytes) -> DeviceStatus:
        r = _BitReader(data)
        return DeviceStatus.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader) -> DeviceStatus:
        v = r.read_bits(2)
        return DeviceStatus(v)

    def __repr__(self) -> str:
        return f"DeviceStatus({int(self)})"


# ---------- SensorReading ----------
@dataclass
class SensorReading:
    device_id: int
    battery: int
    signal: int
    status: DeviceStatus
    temperature: float
    humidity: float
    label: str
    gps_lat: float | None
    gps_lon: float | None
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        try:
            w.enter_nested()
            self.encode_to(w)
        finally:
            w.leave_nested()
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_u32(self.device_id)
        w.write_bits(self.battery, 7)
        w.write_bits(self.signal, 4)
        try:
            w.enter_nested()
            self.status.encode_to(w)
        finally:
            w.leave_nested()
        w.write_f32(self.temperature)
        w.write_f32(self.humidity)
        w.write_string(self.label)
        _vexil_self_2e_gps_5f_lat_optional = self.gps_lat
        w.write_bool(_vexil_self_2e_gps_5f_lat_optional is not None)
        if _vexil_self_2e_gps_5f_lat_optional is not None:
            w.flush_to_byte_boundary()
            w.write_f64(_vexil_self_2e_gps_5f_lat_optional)
        _vexil_self_2e_gps_5f_lon_optional = self.gps_lon
        w.write_bool(_vexil_self_2e_gps_5f_lon_optional is not None)
        if _vexil_self_2e_gps_5f_lon_optional is not None:
            w.flush_to_byte_boundary()
            w.write_f64(_vexil_self_2e_gps_5f_lon_optional)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> SensorReading:
        r = _BitReader(data)
        try:
            r.enter_nested()
            return SensorReading.decode_from(r)
        finally:
            r.leave_nested()

    @staticmethod
    def decode_from(r: _BitReader) -> SensorReading:
        m = SensorReading.__new__(SensorReading)
        m.device_id = r.read_u32()
        m.battery = r.read_bits(7)
        m.signal = r.read_bits(4)
        try:
            r.enter_nested()
            m.status = DeviceStatus.decode_from(r)
        finally:
            r.leave_nested()
        m.temperature = r.read_f32()
        m.humidity = r.read_f32()
        m.label = r.read_string()
        _vexil_m_2e_gps_5f_lat_present = r.read_bool()
        if _vexil_m_2e_gps_5f_lat_present:
            r.flush_to_byte_boundary()
            m.gps_lat = r.read_f64()
        else:
            m.gps_lat = None
        _vexil_m_2e_gps_5f_lon_present = r.read_bool()
        if _vexil_m_2e_gps_5f_lon_present:
            r.flush_to_byte_boundary()
            m.gps_lon = r.read_f64()
        else:
            m.gps_lon = None
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m

__all__ = ["dataclass", "SCHEMA_HASH", "DeviceStatus", "SensorReading"]
