// Code generated by vexilc. DO NOT EDIT.
// Source: sensor.packet

use vexil_runtime::*;

pub const SCHEMA_HASH: [u8; 32] = [0x4d, 0x4c, 0xa9, 0x1b, 0x40, 0xa3, 0xbb, 0xa1, 0x69, 0x4d, 0x74, 0x26, 0xac, 0x43, 0x52, 0xf5, 0x68, 0x5b, 0x4c, 0x40, 0x73, 0x3f, 0x3c, 0xa6, 0x59, 0xc9, 0x08, 0xa3, 0x4d, 0x4e, 0x3a, 0xbb];

// ── SensorKind ──
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u64)]
pub enum SensorKind {
    Temperature = 0_u64,
    Humidity = 1_u64,
    Pressure = 2_u64,
    Light = 3_u64,
}

impl vexil_runtime::Pack for SensorKind {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        let disc: u64 = match self {
            Self::Temperature => 0_u64,
            Self::Humidity => 1_u64,
            Self::Pressure => 2_u64,
            Self::Light => 3_u64,
        };
        w.write_bits(disc, 8_u8);
        Ok(())
    }
}

impl vexil_runtime::Unpack for SensorKind {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let disc = r.read_bits(8_u8)?;
        match disc {
            0_u64 => Ok(Self::Temperature),
            1_u64 => Ok(Self::Humidity),
            2_u64 => Ok(Self::Pressure),
            3_u64 => Ok(Self::Light),
            _ => Err(vexil_runtime::DecodeError::UnknownEnumVariant { type_name: "SensorKind", value: disc }),
        }
    }
}


// ── SensorReading ──
#[derive(Debug, Clone, PartialEq)]
pub struct SensorReading {
    pub channel: u8,
    pub kind: SensorKind,
    pub value: u16,
    pub sequence: u32,
    pub delta_ts: i32,
}

impl vexil_runtime::Pack for SensorReading {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_bits(self.channel as u64, 4_u8);
        self.kind.pack(w)?;
        w.write_u16(self.value);
        w.write_leb128(self.sequence as u64);
        w.write_zigzag(self.delta_ts as i64, 32_u8);
        w.flush_to_byte_boundary();
        Ok(())
    }
}

impl vexil_runtime::Unpack for SensorReading {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let channel = r.read_bits(4_u8)? as u8;
        r.enter_recursive()?;
        let kind = vexil_runtime::Unpack::unpack(r)?;
        r.leave_recursive();
        let value = r.read_u16()?;
        let sequence_raw = r.read_leb128(10_u8)?;
        let sequence: u32 = sequence_raw as u32;
        let delta_ts_raw = r.read_zigzag(32_u8, 10_u8)?;
        let delta_ts: i32 = delta_ts_raw as i32;
        r.flush_to_byte_boundary();
        Ok(Self {
            channel,
            kind,
            value,
            sequence,
            delta_ts,
        })
    }
}


// ── TelemetryPacket ──
#[derive(Debug, Clone, PartialEq)]
pub struct TelemetryPacket {
    pub device_id: u32,
    pub readings: Vec<SensorReading>,
    pub battery: u8,
}

impl vexil_runtime::Pack for TelemetryPacket {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_u32(self.device_id);
        w.write_leb128(self.readings.len() as u64);
        for item in &self.readings {
            item.pack(w)?;
        }
        w.write_bits(self.battery as u64, 7_u8);
        w.flush_to_byte_boundary();
        Ok(())
    }
}

impl vexil_runtime::Unpack for TelemetryPacket {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let device_id = r.read_u32()?;
        let readings_len = r.read_leb128(10_u8)? as usize;
        let mut readings = Vec::with_capacity(readings_len);
        for _ in 0..readings_len {
            r.enter_recursive()?;
            let readings_item = vexil_runtime::Unpack::unpack(r)?;
            r.leave_recursive();
            readings.push(readings_item);
        }
        let battery = r.read_bits(7_u8)? as u8;
        r.flush_to_byte_boundary();
        Ok(Self {
            device_id,
            readings,
            battery,
        })
    }
}

