// Code generated by vexilc. DO NOT EDIT.
// Source: project.messages

use vexil_runtime::*;
use crate::project::types::Priority;
use crate::project::types::Timestamp;

pub const SCHEMA_HASH: [u8; 32] = [0xf7, 0x2f, 0x55, 0x6f, 0xa4, 0xaa, 0x41, 0x3e, 0x2c, 0x41, 0xdd, 0xcd, 0x86, 0x3e, 0x23, 0xbd, 0xb3, 0x70, 0x2e, 0xf9, 0x48, 0xa6, 0xa3, 0xc2, 0xc1, 0x1c, 0x6e, 0x6f, 0x2f, 0x90, 0x5b, 0x17];

// ── Task ──
#[derive(Debug, Clone, PartialEq)]
pub struct Task {
    pub id: u64,
    pub title: String,
    pub priority: Priority,
    pub created_at: Timestamp,
}

impl vexil_runtime::Pack for Task {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_leb128(self.id as u64);
        if (self.title).len() as u64 > 256_u64 { return Err(vexil_runtime::EncodeError::LimitExceeded { field: "title", limit: 256_u64, actual: (self.title).len() as u64 }); }
        w.write_string(&self.title);
        self.priority.pack(w)?;
        self.created_at.pack(w)?;
        w.flush_to_byte_boundary();
        Ok(())
    }
}

impl vexil_runtime::Unpack for Task {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let id_raw = r.read_leb128(10_u8)?;
        let id: u64 = id_raw as u64;
        let title = r.read_string()?;
        if title.len() as u64 > 256_u64 { return Err(vexil_runtime::DecodeError::LimitExceeded { field: "title", limit: 256_u64, actual: title.len() as u64 }); }
        r.enter_recursive()?;
        let priority = vexil_runtime::Unpack::unpack(r)?;
        r.leave_recursive();
        r.enter_recursive()?;
        let created_at = vexil_runtime::Unpack::unpack(r)?;
        r.leave_recursive();
        r.flush_to_byte_boundary();
        Ok(Self {
            id,
            title,
            priority,
            created_at,
        })
    }
}


// ── TaskList ──
#[derive(Debug, Clone, PartialEq)]
pub struct TaskList {
    pub tasks: Vec<Task>,
}

impl vexil_runtime::Pack for TaskList {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_leb128(self.tasks.len() as u64);
        for item in &self.tasks {
            item.pack(w)?;
        }
        w.flush_to_byte_boundary();
        Ok(())
    }
}

impl vexil_runtime::Unpack for TaskList {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let tasks_len = r.read_leb128(10_u8)? as usize;
        let mut tasks = Vec::with_capacity(tasks_len);
        for _ in 0..tasks_len {
            r.enter_recursive()?;
            let tasks_item = vexil_runtime::Unpack::unpack(r)?;
            r.leave_recursive();
            tasks.push(tasks_item);
        }
        r.flush_to_byte_boundary();
        Ok(Self {
            tasks,
        })
    }
}

