// Code generated by vexilc. DO NOT EDIT.
// Source: sensor.telemetry

package main

import vexil "github.com/vexil-lang/vexil/packages/runtime-go"

var SchemaHash = [32]byte{0xb1, 0x3d, 0xa4, 0x8d, 0x34, 0xbf, 0xd6, 0xc9, 0x4b, 0x13, 0xa3, 0x27, 0x52, 0x48, 0x5b, 0x9e, 0xf9, 0x6e, 0x6d, 0x16, 0x4d, 0x1c, 0xbc, 0x3f, 0x34, 0x8e, 0x34, 0x21, 0x37, 0x5f, 0x51, 0xa0}

// ── DeviceStatus ──
type DeviceStatus int

const (
	DeviceStatusOnline DeviceStatus = 0
	DeviceStatusDegraded DeviceStatus = 1
	DeviceStatusOffline DeviceStatus = 2
	DeviceStatusError DeviceStatus = 3
)

func (s DeviceStatus) Pack(w *vexil.BitWriter) error {
	w.WriteBits(uint64(s), 2)
	return nil
}

func (s *DeviceStatus) Unpack(r *vexil.BitReader) error {
	v, err := r.ReadBits(2)
	if err != nil {
		return err
	}
	*s = DeviceStatus(v)
	return nil
}


// ── SensorReading ──
type SensorReading struct {
	DeviceID uint32
	Battery uint8
	Signal uint8
	Status DeviceStatus
	Temperature float32
	Humidity float32
	Label string
	GpsLat *float64
	GpsLon *float64
	Unknown []byte
}

func (m *SensorReading) Pack(w *vexil.BitWriter) error {
	w.WriteU32(m.DeviceID)
	w.WriteBits(uint64(m.Battery), 7)
	w.WriteBits(uint64(m.Signal), 4)
	m.Status.Pack(w)
	w.WriteF32(m.Temperature)
	w.WriteF32(m.Humidity)
	w.WriteString(m.Label)
	w.WriteBool(m.GpsLat != nil)
	w.FlushToByteBoundary()
	if m.GpsLat != nil {
		w.WriteF64(*m.GpsLat)
	}
	w.WriteBool(m.GpsLon != nil)
	w.FlushToByteBoundary()
	if m.GpsLon != nil {
		w.WriteF64(*m.GpsLon)
	}
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *SensorReading) Unpack(r *vexil.BitReader) error {
	{
		v, err := r.ReadU32()
		if err != nil {
			return err
		}
		m.DeviceID = v
	}
	{
		v, err := r.ReadBits(7)
		if err != nil {
			return err
		}
		m.Battery = uint8(v)
	}
	{
		v, err := r.ReadBits(4)
		if err != nil {
			return err
		}
		m.Signal = uint8(v)
	}
	if err := m.Status.Unpack(r); err != nil {
		return err
	}
	{
		v, err := r.ReadF32()
		if err != nil {
			return err
		}
		m.Temperature = v
	}
	{
		v, err := r.ReadF32()
		if err != nil {
			return err
		}
		m.Humidity = v
	}
	{
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Label = v
	}
	{
		present, err := r.ReadBool()
		if err != nil {
			return err
		}
		r.FlushToByteBoundary()
		if present {
			var optVal float64
			{
				v, err := r.ReadF64()
				if err != nil {
					return err
				}
				optVal = v
			}
			m.GpsLat = &optVal
		}
	}
	{
		present, err := r.ReadBool()
		if err != nil {
			return err
		}
		r.FlushToByteBoundary()
		if present {
			var optVal float64
			{
				v, err := r.ReadF64()
				if err != nil {
					return err
				}
				optVal = v
			}
			m.GpsLon = &optVal
		}
	}
	r.FlushToByteBoundary()
	m.Unknown = r.ReadRemaining()
	return nil
}


// ── DeviceConfig ──
type DeviceConfig struct {
	DeviceID uint32
	ReportInterval uint16
	HighTempAlert float32
	LowTempAlert float32
	Label string
	Unknown []byte
}

func (m *DeviceConfig) Pack(w *vexil.BitWriter) error {
	w.WriteU32(m.DeviceID)
	w.WriteU16(m.ReportInterval)
	w.WriteF32(m.HighTempAlert)
	w.WriteF32(m.LowTempAlert)
	w.WriteString(m.Label)
	w.FlushToByteBoundary()
	if len(m.Unknown) > 0 {
		w.WriteRawBytes(m.Unknown)
	}
	return nil
}

func (m *DeviceConfig) Unpack(r *vexil.BitReader) error {
	{
		v, err := r.ReadU32()
		if err != nil {
			return err
		}
		m.DeviceID = v
	}
	{
		v, err := r.ReadU16()
		if err != nil {
			return err
		}
		m.ReportInterval = v
	}
	{
		v, err := r.ReadF32()
		if err != nil {
			return err
		}
		m.HighTempAlert = v
	}
	{
		v, err := r.ReadF32()
		if err != nil {
			return err
		}
		m.LowTempAlert = v
	}
	{
		v, err := r.ReadString()
		if err != nil {
			return err
		}
		m.Label = v
	}
	r.FlushToByteBoundary()
	m.Unknown = r.ReadRemaining()
	return nil
}

