// Code generated by vexilc. DO NOT EDIT.
// Source: test.recursive

use vexil_runtime::*;

pub const SCHEMA_HASH: [u8; 32] = [0xa1, 0x25, 0xcb, 0x50, 0x29, 0x3e, 0xa3, 0x25, 0x60, 0x73, 0x08, 0x42, 0x52, 0xc5, 0xca, 0xf0, 0x83, 0xf5, 0xdd, 0xf7, 0x30, 0x18, 0xf8, 0x51, 0x8e, 0x54, 0xa9, 0xfd, 0xbe, 0xeb, 0x91, 0xae];

// ── TreeNode ──
#[derive(Debug, Clone, PartialEq)]
pub struct TreeNode {
    pub value: i32,
    pub children: Vec<TreeNode>,
}

impl vexil_runtime::Pack for TreeNode {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_i32(self.value);
        w.write_leb128(self.children.len() as u64);
        for item in &self.children {
            item.pack(w)?;
        }
        w.flush_to_byte_boundary();
        Ok(())
    }
}

impl vexil_runtime::Unpack for TreeNode {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let value = r.read_i32()?;
        let children_len = r.read_leb128(10_u8)? as usize;
        let mut children = Vec::with_capacity(children_len);
        for _ in 0..children_len {
            r.enter_recursive()?;
            let children_item = vexil_runtime::Unpack::unpack(r)?;
            r.leave_recursive();
            children.push(children_item);
        }
        r.flush_to_byte_boundary();
        Ok(Self {
            value,
            children,
        })
    }
}


// ── LinkedList ──
#[derive(Debug, Clone, PartialEq)]
pub struct LinkedList {
    pub value: String,
    pub next: Option<Box<LinkedList>>,
}

impl vexil_runtime::Pack for LinkedList {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_string(&self.value);
        w.write_bool(self.next.is_some());
        w.flush_to_byte_boundary();
        if let Some(ref inner_val) = self.next {
            inner_val.pack(w)?;
        }
        w.flush_to_byte_boundary();
        Ok(())
    }
}

impl vexil_runtime::Unpack for LinkedList {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let value = r.read_string()?;
        let next_present = r.read_bool()?;
        r.flush_to_byte_boundary();
        let next = if next_present {
            r.enter_recursive()?;
            let next_inner = vexil_runtime::Unpack::unpack(r)?;
            r.leave_recursive();
            Some(next_inner)
        }
        else {
            None
        }
;
        r.flush_to_byte_boundary();
        Ok(Self {
            value,
            next,
        })
    }
}


// ── Expr ──
#[derive(Debug, Clone, PartialEq)]
pub struct Expr {
    pub kind: Box<ExprKind>,
}

impl vexil_runtime::Pack for Expr {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        self.kind.pack(w)?;
        w.flush_to_byte_boundary();
        Ok(())
    }
}

impl vexil_runtime::Unpack for Expr {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        r.enter_recursive()?;
        let kind = vexil_runtime::Unpack::unpack(r)?;
        r.leave_recursive();
        r.flush_to_byte_boundary();
        Ok(Self {
            kind,
        })
    }
}


// ── ExprKind ──
#[derive(Debug, Clone, PartialEq)]
pub enum ExprKind {
    Literal { value: i64 },
    Binary { left: Box<Expr>, op: u8, right: Box<Expr> },
}

impl vexil_runtime::Pack for ExprKind {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.flush_to_byte_boundary();
        match self {
            Self::Literal { value } => {
                w.write_leb128(0_u64);
                let mut payload_w = vexil_runtime::BitWriter::new();
                payload_w.write_i64(*value);
                payload_w.flush_to_byte_boundary();
                let payload = payload_w.finish();
                w.write_leb128(payload.len() as u64);
                w.write_raw_bytes(&payload);
            }
            Self::Binary { left, op, right } => {
                w.write_leb128(1_u64);
                let mut payload_w = vexil_runtime::BitWriter::new();
                left.pack(&mut payload_w)?;
                payload_w.write_u8(*op);
                right.pack(&mut payload_w)?;
                payload_w.flush_to_byte_boundary();
                let payload = payload_w.finish();
                w.write_leb128(payload.len() as u64);
                w.write_raw_bytes(&payload);
            }
        }
        Ok(())
    }
}

impl vexil_runtime::Unpack for ExprKind {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        r.flush_to_byte_boundary();
        let disc = r.read_leb128(10_u8)?;
        let len = r.read_leb128(10_u8)? as usize;
        match disc {
            0_u64 => {
                let payload = r.read_raw_bytes(len)?;
                let mut pr = vexil_runtime::BitReader::new(&payload);
                let value = pr.read_i64()?;
                pr.flush_to_byte_boundary();
                Ok(Self::Literal { value })
            }
            1_u64 => {
                let payload = r.read_raw_bytes(len)?;
                let mut pr = vexil_runtime::BitReader::new(&payload);
                pr.enter_recursive()?;
                let left = vexil_runtime::Unpack::unpack(&mut pr)?;
                pr.leave_recursive();
                let op = pr.read_u8()?;
                pr.enter_recursive()?;
                let right = vexil_runtime::Unpack::unpack(&mut pr)?;
                pr.leave_recursive();
                pr.flush_to_byte_boundary();
                Ok(Self::Binary { left, op, right })
            }
            _ => {
                let _skip = r.read_raw_bytes(len)?;
                Err(vexil_runtime::DecodeError::UnknownUnionVariant { type_name: "ExprKind", discriminant: disc })
            }
        }
    }
}

