// Code generated by vexilc. DO NOT EDIT.
// Source: test.typed.tombstone

use vexil_runtime::*;

pub const SCHEMA_HASH: [u8; 32] = [0x23, 0x9b, 0xc3, 0x16, 0x2d, 0xc1, 0xc8, 0x3d, 0x4a, 0x09, 0x6b, 0xb2, 0x03, 0xf1, 0xb3, 0x14, 0x3a, 0x4a, 0xbc, 0x27, 0xbb, 0xe4, 0x88, 0xee, 0x2b, 0x99, 0xf8, 0x68, 0x1f, 0x9b, 0x6e, 0x06];

// ── Config ──
// REMOVED @1 (since unknown): migrated to timeout_ms
pub const CONFIG_REMOVED_ORDINALS: &[(u16, &str, &str)] = &[
    (1, "unknown", "migrated to timeout_ms"),
];
#[derive(Debug, Clone, PartialEq)]
pub struct Config {
    pub name: String,
    pub timeout_ms: u64,
    pub _unknown: Vec<u8>,
}

impl vexil_runtime::Pack for Config {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_string(&self.name);
        w.write_u64(self.timeout_ms);
        w.flush_to_byte_boundary();
        if !self._unknown.is_empty() {
            w.write_raw_bytes(&self._unknown);
        }
        Ok(())
    }
}

impl vexil_runtime::Unpack for Config {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let name = r.read_string()?;
        // discard @removed ordinal 1
        let _ = r.read_u32()?;
        let timeout_ms = r.read_u64()?;
        r.flush_to_byte_boundary();
        let _unknown = Vec::new();
        Ok(Self {
            name,
            timeout_ms,
            _unknown,
        })
    }
}

