// Code generated by vexilc. DO NOT EDIT.
// Source: test.reserved_variants

use vexil_runtime::*;

pub const SCHEMA_HASH: [u8; 32] = [0xaa, 0x41, 0xda, 0x90, 0xb9, 0xc2, 0xcb, 0xbb, 0x8d, 0x92, 0x3f, 0xbf, 0x43, 0xde, 0xe2, 0x73, 0xe8, 0xfd, 0x96, 0x6b, 0x8d, 0x0b, 0x0c, 0x60, 0x02, 0xb2, 0xeb, 0x1d, 0x8e, 0xcd, 0xe1, 0x7a];
pub const SCHEMA_VERSION: &str = "1.0.0";

// ── ImageProtocol ──
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u64)]
pub enum ImageProtocol {
    None = 0_u64,
    Sixel = 1_u64,
    Kitty = 2_u64,
}

impl vexil_runtime::Pack for ImageProtocol {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        let disc: u64 = match self {
            Self::None => 0_u64,
            Self::Sixel => 1_u64,
            Self::Kitty => 2_u64,
        };
        w.write_bits(disc, 2_u8);
        Ok(())
    }
}

impl vexil_runtime::Unpack for ImageProtocol {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let disc = r.read_bits(2_u8)?;
        match disc {
            0_u64 => Ok(Self::None),
            1_u64 => Ok(Self::Sixel),
            2_u64 => Ok(Self::Kitty),
            _ => Err(vexil_runtime::DecodeError::UnknownEnumVariant { type_name: "ImageProtocol", value: disc }),
        }
    }
}


// ── ParseResult ──
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u64)]
pub enum ParseResult {
    Ok = 0_u64,
    Err = 1_u64,
    Some = 2_u64,
    None = 3_u64,
}

impl vexil_runtime::Pack for ParseResult {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        let disc: u64 = match self {
            Self::Ok => 0_u64,
            Self::Err => 1_u64,
            Self::Some => 2_u64,
            Self::None => 3_u64,
        };
        w.write_bits(disc, 2_u8);
        Ok(())
    }
}

impl vexil_runtime::Unpack for ParseResult {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let disc = r.read_bits(2_u8)?;
        match disc {
            0_u64 => Ok(Self::Ok),
            1_u64 => Ok(Self::Err),
            2_u64 => Ok(Self::Some),
            3_u64 => Ok(Self::None),
            _ => Err(vexil_runtime::DecodeError::UnknownEnumVariant { type_name: "ParseResult", value: disc }),
        }
    }
}

