// Code generated by vexilc. DO NOT EDIT.
// Source: test.fixed

use vexil_runtime::*;

pub const SCHEMA_HASH: [u8; 32] = [0x15, 0x74, 0x87, 0x60, 0xbd, 0xa3, 0x4d, 0xc8, 0x66, 0x49, 0x67, 0x0d, 0xa0, 0x01, 0x75, 0x3c, 0xf5, 0xdb, 0x64, 0x23, 0xef, 0xa8, 0x97, 0x6a, 0xe4, 0x74, 0x5a, 0xb5, 0x85, 0xd7, 0x4d, 0x0b];

// ── SensorReading ──
#[derive(Debug, Clone, PartialEq)]
pub struct SensorReading {
    pub temperature: i32,
    pub pressure: i64,
    pub delta_temp: i32,
    pub _unknown: Vec<u8>,
}

impl vexil_runtime::Pack for SensorReading {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_i32(self.temperature);
        w.write_i64(self.pressure);
        w.write_leb128(self.delta_temp as u64);
        w.flush_to_byte_boundary();
        if !self._unknown.is_empty() {
            w.write_raw_bytes(&self._unknown);
        }
        Ok(())
    }
}

impl vexil_runtime::Unpack for SensorReading {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let temperature = r.read_i32()?;
        let pressure = r.read_i64()?;
        let delta_temp_raw = r.read_leb128(10_u8)?;
        let delta_temp: u64 = delta_temp_raw as u64;
        r.flush_to_byte_boundary();
        let _unknown = Vec::new();
        Ok(Self {
            temperature,
            pressure,
            delta_temp,
            _unknown,
        })
    }
}

