// Code generated by vexilc. DO NOT EDIT.
// Source: test.generic_trait_nested


pub const SCHEMA_HASH: [u8; 32] = [0x47, 0xe1, 0xbb, 0xd9, 0xad, 0x5a, 0x99, 0x4e, 0xbc, 0xbd, 0x7a, 0xc1, 0xad, 0x0a, 0xae, 0x13, 0x99, 0x05, 0x87, 0x87, 0x89, 0x04, 0xa6, 0xf8, 0xb9, 0x2e, 0xa1, 0xb9, 0x78, 0x7f, 0x36, 0x86];

// ── Container ──
pub trait Container<T> {
    fn items(&self) -> &Vec<T>;
}

// ── EventList ──
#[derive(Debug, Clone, PartialEq)]
pub struct EventList {
    pub items: Vec<u64>,
    pub _unknown: Vec<u8>,
}

impl vexil_runtime::Pack for EventList {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_leb128(self.items.len() as u64);
        for item in &self.items {
            w.write_u64(*item);
        }
        w.flush_to_byte_boundary();
        if !self._unknown.is_empty() {
            w.write_raw_bytes(&self._unknown);
        }
        Ok(())
    }
}

impl vexil_runtime::Unpack for EventList {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let items_len = r.read_leb128(10_u8)? as usize;
        let mut items = Vec::with_capacity(items_len);
        for _ in 0..items_len {
            let items_item = r.read_u64()?;
            items.push(items_item);
        }
        r.flush_to_byte_boundary();
        let _unknown = Vec::new();
        Ok(Self {
            items,
            _unknown,
        })
    }
}


// ── impl Container ──
impl Container<u64> for EventList {
    fn items(&self) -> &Vec<u64> {
        &self.items
    }
}
