// Code generated by vexilc. DO NOT EDIT.
// Source: sensor.telemetry

import { BitReader, BitWriter } from '@vexil-lang/runtime';

export const SCHEMA_HASH = new Uint8Array([0xb1, 0x3d, 0xa4, 0x8d, 0x34, 0xbf, 0xd6, 0xc9, 0x4b, 0x13, 0xa3, 0x27, 0x52, 0x48, 0x5b, 0x9e, 0xf9, 0x6e, 0x6d, 0x16, 0x4d, 0x1c, 0xbc, 0x3f, 0x34, 0x8e, 0x34, 0x21, 0x37, 0x5f, 0x51, 0xa0]);

// ── DeviceStatus ──
export type DeviceStatus = 'Online' | 'Degraded' | 'Offline' | 'Error';
export const DeviceStatus = {
  Online: 'Online' as const,
  Degraded: 'Degraded' as const,
  Offline: 'Offline' as const,
  Error: 'Error' as const,
} as const;

export function encodeDeviceStatus(v: DeviceStatus, w: BitWriter): void {
  let disc: number;
  switch (v) {
    case 'Online': disc = 0; break;
    case 'Degraded': disc = 1; break;
    case 'Offline': disc = 2; break;
    case 'Error': disc = 3; break;
    default: throw new Error(`Unknown DeviceStatus variant: ${v}`);
  }
  w.writeBits(disc, 2);
}

export function decodeDeviceStatus(r: BitReader): DeviceStatus {
  const disc = r.readBits(2);
  switch (disc) {
    case 0: return 'Online';
    case 1: return 'Degraded';
    case 2: return 'Offline';
    case 3: return 'Error';
    default: throw new Error(`Unknown DeviceStatus discriminant: ${disc}`);
  }
}


// ── SensorReading ──
export interface SensorReading {
  device_id: number;
  battery: number;
  signal: number;
  status: DeviceStatus;
  temperature: number;
  humidity: number;
  label: string;
  gps_lat: number | null;
  gps_lon: number | null;
}

export function encodeSensorReading(v: SensorReading, w: BitWriter): void {
  w.writeU32(v.device_id);
  w.writeBits(v.battery, 7);
  w.writeBits(v.signal, 4);
  w.enterNested();
  encodeDeviceStatus(v.status, w);
  w.leaveNested();
  w.writeF32(v.temperature);
  w.writeF32(v.humidity);
  w.writeString(v.label);
  w.writeBool(v.gps_lat !== null);
  w.flushToByteBoundary();
  if (v.gps_lat !== null) {
    w.writeF64(v.gps_lat);
  }
  w.writeBool(v.gps_lon !== null);
  w.flushToByteBoundary();
  if (v.gps_lon !== null) {
    w.writeF64(v.gps_lon);
  }
  w.flushToByteBoundary();
}

export function decodeSensorReading(r: BitReader): SensorReading {
  const device_id = r.readU32();
  const battery = r.readBits(7);
  const signal = r.readBits(4);
  r.enterNested();
  const status = decodeDeviceStatus(r);
  r.leaveNested();
  const temperature = r.readF32();
  const humidity = r.readF32();
  const label = r.readString();
  const gps_lat_present = r.readBool();
  r.flushToByteBoundary();
  let gps_lat: number | null;
  if (gps_lat_present) {
    const gps_lat_inner = r.readF64();
    gps_lat = gps_lat_inner;
  } else {
    gps_lat = null;
  }
  const gps_lon_present = r.readBool();
  r.flushToByteBoundary();
  let gps_lon: number | null;
  if (gps_lon_present) {
    const gps_lon_inner = r.readF64();
    gps_lon = gps_lon_inner;
  } else {
    gps_lon = null;
  }
  r.flushToByteBoundary();
  return { device_id, battery, signal, status, temperature, humidity, label, gps_lat, gps_lon };
}


// ── DeviceConfig ──
export interface DeviceConfig {
  device_id: number;
  report_interval: number;
  high_temp_alert: number;
  low_temp_alert: number;
  label: string;
}

export function encodeDeviceConfig(v: DeviceConfig, w: BitWriter): void {
  w.writeU32(v.device_id);
  w.writeU16(v.report_interval);
  w.writeF32(v.high_temp_alert);
  w.writeF32(v.low_temp_alert);
  w.writeString(v.label);
  w.flushToByteBoundary();
}

export function decodeDeviceConfig(r: BitReader): DeviceConfig {
  const device_id = r.readU32();
  const report_interval = r.readU16();
  const high_temp_alert = r.readF32();
  const low_temp_alert = r.readF32();
  const label = r.readString();
  r.flushToByteBoundary();
  return { device_id, report_interval, high_temp_alert, low_temp_alert, label };
}

