//! # vexil-runtime
//!
//! Runtime support library for [Vexil](https://github.com/vexil-lang/vexil)
//! generated code. Provides the [`Pack`] and [`Unpack`] traits plus
//! [`BitWriter`] / [`BitReader`] for LSB-first bit-packed encoding and decoding.
//!
//! This crate is a dependency of code generated by `vexilc codegen`. You
//! generally don't use it directly — the generated `Pack` and `Unpack` impls
//! call into it.
//!
//! ## Encoding Model
//!
//! - Sub-byte fields are packed LSB-first within each byte
//! - Multi-byte integers use little-endian byte order
//! - `@varint` fields use unsigned LEB128
//! - `@zigzag` fields use ZigZag encoding + LEB128
//! - Strings and byte arrays are length-prefixed with LEB128

pub mod bit_reader;
pub mod bit_writer;
pub mod error;
pub mod handshake;
pub mod leb128;
pub mod traits;
pub mod zigzag;

pub use bit_reader::BitReader;
pub use bit_writer::BitWriter;
pub use error::{DecodeError, EncodeError};
pub use handshake::{HandshakeResult, SchemaHandshake};
pub use traits::{Pack, Unpack};

/// Maximum allowed byte length for strings and byte arrays (64 MiB).
///
/// Decoding a string or `bytes` field whose LEB128 length prefix exceeds this
/// value produces [`DecodeError::LimitExceeded`].
pub const MAX_BYTES_LENGTH: u64 = 1 << 26;

/// Maximum allowed element count for collections (16 M items).
///
/// Used by generated code to cap list/map sizes during decoding.
pub const MAX_COLLECTION_COUNT: u64 = 1 << 24;

/// Maximum number of bytes consumed when reading a LEB128 length prefix.
///
/// Limits the length prefix to at most 4 bytes (values up to 2^28 - 1).
pub const MAX_LENGTH_PREFIX_BYTES: u8 = 4;

/// Maximum nesting depth for recursive types.
///
/// [`BitReader::enter_recursive`] returns [`DecodeError::RecursionLimitExceeded`]
/// when the depth exceeds this value.
pub const MAX_RECURSION_DEPTH: u32 = 64;
