//! Python code generation backend for the Vexil schema compiler.
//!
//! Generates Python `@dataclass` classes with `encode() -> bytes` and
//! `@staticmethod decode(data: bytes) -> Self` methods.
//! Uses stdlib only: `struct`, `dataclasses`, `typing`.

pub mod backend;
pub mod delta;
pub mod emit;
pub mod enum_gen;
pub mod flags;
pub mod message;
pub mod newtype;
pub mod types;
pub mod union_gen;

pub use backend::PythonBackend;

use vexil_lang::ir::{CompiledSchema, TypeDef};

#[derive(Debug, Clone, PartialEq, thiserror::Error)]
pub enum CodegenError {
    #[error("unresolved type {type_id:?} referenced by {referenced_by}")]
    UnresolvedType {
        type_id: vexil_lang::ir::TypeId,
        referenced_by: String,
    },
}

/// Generate Python code for a compiled schema (no cross-file imports).
pub fn generate(compiled: &CompiledSchema) -> Result<String, CodegenError> {
    generate_with_imports(compiled, None)
}

/// Generate Python code for a compiled schema, with optional cross-file import information.
///
/// `import_types` maps type names that are imported from other modules.
pub(crate) fn generate_with_imports(
    compiled: &CompiledSchema,
    import_types: Option<&std::collections::HashMap<String, String>>,
) -> Result<String, CodegenError> {
    let mut w = emit::CodeWriter::new();

    // Header
    w.line("# Code generated by vexilc. DO NOT EDIT.");
    let ns = compiled.namespace.join(".");
    w.line(&format!("# Source: {ns}"));
    w.blank();

    // Imports
    w.line("from __future__ import annotations");
    w.line("from dataclasses import dataclass");
    w.line("from typing import Optional");
    w.blank();
    w.line("# Runtime support (to be provided by vexil Python runtime)");
    w.line("from vexil_runtime import _BitWriter, _BitReader");
    w.blank();

    // Cross-module imports if needed
    if let Some(imports) = import_types {
        if !imports.is_empty() {
            let mut paths: Vec<&String> = imports.values().collect();
            paths.sort();
            paths.dedup();
            for path in paths {
                w.line(&format!("from {path} import *"));
            }
            w.blank();
        }
    }

    // Schema hash
    let hash = vexil_lang::canonical::schema_hash(compiled);
    let hash_str = hash
        .iter()
        .map(|b| format!("0x{b:02x}"))
        .collect::<Vec<_>>()
        .join(", ");
    w.line(&format!("SCHEMA_HASH: tuple[int, ...] = ({hash_str})"));

    // Schema version
    if let Some(ref version) = compiled.annotations.version {
        w.line(&format!("SCHEMA_VERSION: str = \"{version}\""));
    }

    w.blank();

    // Emit each declared type
    for &type_id in &compiled.declarations {
        let typedef =
            compiled
                .registry
                .get(type_id)
                .ok_or_else(|| CodegenError::UnresolvedType {
                    type_id,
                    referenced_by: "declarations".to_string(),
                })?;

        w.blank();
        let type_name = type_name_of(typedef);
        w.line(&format!("# ---------- {type_name} ----------"));

        match typedef {
            TypeDef::Message(msg) => {
                message::emit_message(&mut w, msg, &compiled.registry);
                delta::emit_delta(&mut w, msg, &compiled.registry);
            }
            TypeDef::Enum(en) => {
                enum_gen::emit_enum(&mut w, en, &compiled.registry);
            }
            TypeDef::Flags(fl) => {
                flags::emit_flags(&mut w, fl, &compiled.registry);
            }
            TypeDef::Union(un) => {
                union_gen::emit_union(&mut w, un, &compiled.registry);
            }
            TypeDef::Newtype(nt) => {
                newtype::emit_newtype(&mut w, nt, &compiled.registry);
            }
            TypeDef::Config(cfg) => {
                message::emit_config(&mut w, cfg, &compiled.registry);
            }
            _ => {} // non_exhaustive guard
        }
    }

    Ok(w.finish())
}

/// Returns the name of a TypeDef for use in section separator comments.
pub(crate) fn type_name_of(typedef: &TypeDef) -> &str {
    match typedef {
        TypeDef::Message(m) => m.name.as_str(),
        TypeDef::Enum(e) => e.name.as_str(),
        TypeDef::Flags(f) => f.name.as_str(),
        TypeDef::Union(u) => u.name.as_str(),
        TypeDef::Newtype(n) => n.name.as_str(),
        TypeDef::Config(c) => c.name.as_str(),
        _ => "Unknown",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_produces_output() {
        let result = vexil_lang::compile("namespace test.gen\nmessage Foo { x @0 : u32 }");
        let compiled = result.compiled.unwrap();
        let code = generate(&compiled).unwrap();
        assert!(code.contains("@dataclass"));
        assert!(code.contains("class Foo"));
        assert!(code.contains("def encode(self)"));
        assert!(code.contains("@staticmethod"));
        assert!(code.contains("def decode(data: bytes)"));
    }

    #[test]
    fn generate_with_no_imports_matches_generate() {
        let result = vexil_lang::compile("namespace test.gen\nmessage Foo { x @0 : u32 }");
        let compiled = result.compiled.unwrap();
        let without = generate(&compiled).unwrap();
        let with = generate_with_imports(&compiled, None).unwrap();
        assert_eq!(without, with);
    }

    #[test]
    fn python_backend_generate_matches_free_function() {
        use vexil_lang::codegen::CodegenBackend;
        let result = vexil_lang::compile("namespace test.backend\nmessage Foo { x @0 : u32 }");
        let compiled = result.compiled.unwrap();
        let free_fn = generate(&compiled).unwrap();
        let backend = crate::backend::PythonBackend;
        let trait_fn = backend.generate(&compiled).unwrap();
        assert_eq!(free_fn, trait_fn);
    }
}
