//! Python code generation backend for the Vexil schema compiler.
//!
//! Generates Python `@dataclass` classes with `encode() -> bytes` and
//! `@staticmethod decode(data: bytes) -> Self` methods.
//! Uses stdlib only: `struct`, `dataclasses`, `typing`.

pub mod backend;
pub mod delta;
pub mod emit;
pub mod enum_gen;
pub mod flags;
pub mod fn_body;
pub mod message;
pub mod newtype;
pub mod trait_gen;
pub mod types;
pub mod union_gen;

pub use backend::PythonBackend;

use std::collections::{BTreeMap, HashMap};

use vexil_lang::codegen::portable::PortableFunction;
use vexil_lang::ir::{CompiledSchema, ResolvedType, TypeDef, TypeId};

#[derive(Debug, Clone, PartialEq, thiserror::Error)]
pub enum CodegenError {
    #[error("unresolved type {type_id:?} referenced by {referenced_by}")]
    UnresolvedType {
        type_id: vexil_lang::ir::TypeId,
        referenced_by: String,
    },
    #[error(transparent)]
    PortableFunction(#[from] vexil_lang::codegen::portable::PortableFunctionError),
    #[error("Python identifier collision for '{name}': {context}")]
    IdentifierCollision { name: String, context: String },
}

/// Generate Python code for a compiled schema (no cross-file imports).
pub fn generate(compiled: &CompiledSchema) -> Result<String, CodegenError> {
    generate_with_imports(compiled, None)
}

/// Generate Python code for a compiled schema, with optional cross-file import information.
///
/// `import_types` maps type names that are imported from other modules.
pub(crate) fn generate_with_imports(
    compiled: &CompiledSchema,
    import_types: Option<&std::collections::HashMap<String, String>>,
) -> Result<String, CodegenError> {
    let impl_functions = prepare_trait_functions(compiled)?;
    let has_traits = compiled
        .declarations
        .iter()
        .any(|&id| matches!(compiled.registry.get(id), Some(TypeDef::Trait(_))));
    let has_impls = compiled.impls().next().is_some();
    let trait_type_params: std::collections::BTreeSet<String> = compiled
        .declarations
        .iter()
        .filter_map(|&id| match compiled.registry.get(id) {
            Some(TypeDef::Trait(trait_def)) => Some(trait_def),
            _ => None,
        })
        .flat_map(|trait_def| {
            trait_def
                .type_params
                .iter()
                .map(|param| param.name.node.to_string())
        })
        .collect();

    // Emit declarations first so runtime imports can be driven by what the
    // generated code actually references.
    let body = emit_declarations(compiled, &impl_functions, has_impls)?;
    let runtime_imports = required_runtime_imports(&body);
    let mut w = emit::CodeWriter::new();

    // Header
    w.line("# Code generated by vexilc. DO NOT EDIT.");
    let ns = compiled.namespace.join(".");
    w.line(&format!("# Source: {ns}"));
    w.blank();

    // Imports
    w.line("from __future__ import annotations");
    if body.contains("@dataclass") {
        w.line("from dataclasses import dataclass");
    }
    let mut typing_imports = Vec::new();
    if has_impls {
        typing_imports.push("TYPE_CHECKING");
    }
    if body.contains("_VexilLiteral") {
        typing_imports.push("Literal as _VexilLiteral");
    }
    if has_traits {
        typing_imports.push("Protocol");
        if !trait_type_params.is_empty() {
            typing_imports.push("TypeVar");
        }
        typing_imports.push("runtime_checkable");
    }
    if !typing_imports.is_empty() {
        w.line(&format!("from typing import {}", typing_imports.join(", ")));
    }
    if !runtime_imports.is_empty() {
        w.blank();
        w.line("# Runtime support (to be provided by vexil Python runtime)");
        w.line(&format!(
            "from vexil_runtime import {}",
            runtime_imports.join(", ")
        ));
    }
    w.blank();

    // Cross-module imports if needed
    if let Some(imports) = import_types {
        if !imports.is_empty() {
            let mut modules: BTreeMap<&String, Vec<&String>> = BTreeMap::new();
            for (name, path) in imports {
                modules.entry(path).or_default().push(name);
            }
            for (path, names) in &mut modules {
                names.sort();
                names.dedup();
                let names = names
                    .iter()
                    .map(|name| name.as_str())
                    .collect::<Vec<_>>()
                    .join(", ");
                w.line(&format!("from {path} import {names}"));
            }
            w.blank();
        }
    }

    // Schema hash
    let hash = vexil_lang::canonical::schema_hash(compiled);
    let hash_str = hash
        .iter()
        .map(|b| format!("0x{b:02x}"))
        .collect::<Vec<_>>()
        .join(", ");
    w.line(&format!("SCHEMA_HASH: tuple[int, ...] = ({hash_str})"));

    // Schema version
    if let Some(ref version) = compiled.annotations.version {
        w.line(&format!("SCHEMA_VERSION: str = \"{version}\""));
    }

    if !trait_type_params.is_empty() {
        for param in trait_type_params {
            let ident = types::py_type_param_ident(&param);
            w.line(&format!("{ident} = TypeVar(\"{ident}\")"));
        }
    }

    w.blank();

    let generated = format!("{}{body}", w.finish());
    if has_traits {
        Ok(format!("{}\n", generated.trim_end()))
    } else {
        Ok(generated)
    }
}

/// Emit the body: one section per declared type.
///
/// Produced before the header so that import emission can be driven by the
/// symbols the generated code actually references.
fn emit_declarations(
    compiled: &CompiledSchema,
    impl_functions: &HashMap<TypeId, Vec<PortableFunction>>,
    has_impls: bool,
) -> Result<String, CodegenError> {
    let mut w = emit::CodeWriter::new();

    for &type_id in &compiled.declarations {
        let typedef =
            compiled
                .registry
                .get(type_id)
                .ok_or_else(|| CodegenError::UnresolvedType {
                    type_id,
                    referenced_by: "declarations".to_string(),
                })?;

        w.blank();
        let type_name = type_name_of(typedef);
        w.line(&format!("# ---------- {type_name} ----------"));

        match typedef {
            TypeDef::Message(msg) => {
                let functions = impl_functions
                    .get(&type_id)
                    .map(Vec::as_slice)
                    .unwrap_or_default();
                message::emit_message(&mut w, msg, &compiled.registry, functions);
                delta::emit_delta(&mut w, msg, &compiled.registry);
            }
            TypeDef::Enum(en) => {
                enum_gen::emit_enum(&mut w, en, &compiled.registry);
            }
            TypeDef::Flags(fl) => {
                flags::emit_flags(&mut w, fl, &compiled.registry);
            }
            TypeDef::Union(un) => {
                union_gen::emit_union(&mut w, un, &compiled.registry);
            }
            TypeDef::Newtype(nt) => {
                newtype::emit_newtype(&mut w, nt, &compiled.registry);
            }
            TypeDef::Config(cfg) => {
                message::emit_config(&mut w, cfg, &compiled.registry);
            }
            TypeDef::Trait(trait_def) => {
                trait_gen::emit_trait(&mut w, type_id, trait_def, compiled)?
            }
            _ => {} // non_exhaustive guard
        }
    }

    if has_impls {
        w.blank();
        w.line("if TYPE_CHECKING:");
        w.indent();
        for (_, impl_def) in compiled.impls() {
            trait_gen::emit_impl_proof(&mut w, impl_def, &compiled.registry);
        }
        w.dedent();
    }

    Ok(w.finish())
}

/// Runtime symbols the generated body references, in a stable order.
///
/// A trait-only or alias-only schema emits no codec, so it needs no runtime
/// import at all.
fn required_runtime_imports(body: &str) -> Vec<&'static str> {
    [
        ("_BitWriter", "BitWriter as _BitWriter"),
        ("_BitReader", "BitReader as _BitReader"),
        ("DecodeError", "DecodeError"),
    ]
    .into_iter()
    .filter_map(|(symbol, import)| body.contains(symbol).then_some(import))
    .collect()
}

/// Returns the name of a TypeDef for use in section separator comments.
pub(crate) fn type_name_of(typedef: &TypeDef) -> &str {
    match typedef {
        TypeDef::Message(m) => m.name.as_str(),
        TypeDef::Enum(e) => e.name.as_str(),
        TypeDef::Flags(f) => f.name.as_str(),
        TypeDef::Union(u) => u.name.as_str(),
        TypeDef::Newtype(n) => n.name.as_str(),
        TypeDef::Config(c) => c.name.as_str(),
        TypeDef::Trait(t) => t.name.as_str(),
        _ => "Unknown",
    }
}

fn prepare_trait_functions(
    compiled: &CompiledSchema,
) -> Result<HashMap<TypeId, Vec<PortableFunction>>, CodegenError> {
    for &type_id in &compiled.declarations {
        let Some(TypeDef::Trait(trait_def)) = compiled.registry.get(type_id) else {
            continue;
        };
        for function in vexil_lang::codegen::portable::trait_signatures(compiled, type_id)? {
            if trait_def
                .fields
                .iter()
                .any(|field| field.name == function.name)
            {
                return Err(CodegenError::IdentifierCollision {
                    name: function.name.to_string(),
                    context: "trait function conflicts with a generated field member".to_string(),
                });
            }
            reject_python_keyword(function.name.as_str(), "trait function")?;
            for parameter in &function.params {
                reject_python_binding(parameter.name.as_str(), "function parameter")?;
            }
        }
    }

    let mut by_target: HashMap<TypeId, Vec<PortableFunction>> = HashMap::new();
    for (_, impl_def) in compiled.impls() {
        let ResolvedType::Named(target_id) = &impl_def.target_type else {
            continue;
        };
        let message = match compiled.registry.get(*target_id) {
            Some(TypeDef::Message(message)) => message,
            _ => continue,
        };
        for function in vexil_lang::codegen::portable::project_impl(compiled, impl_def)? {
            if message
                .fields
                .iter()
                .any(|field| field.name == function.name)
                || matches!(
                    function.name.as_str(),
                    "encode" | "decode" | "unknown" | "__init__" | "__new__"
                )
            {
                return Err(CodegenError::IdentifierCollision {
                    name: function.name.to_string(),
                    context: "trait method conflicts with a generated Python member".to_string(),
                });
            }
            reject_python_keyword(function.name.as_str(), "trait method")?;
            let functions = by_target.entry(*target_id).or_default();
            if functions
                .iter()
                .any(|existing| existing.name == function.name)
            {
                return Err(CodegenError::IdentifierCollision {
                    name: function.name.to_string(),
                    context: "multiple implemented traits project the same method".to_string(),
                });
            }
            for parameter in &function.params {
                reject_python_binding(parameter.name.as_str(), "function parameter")?;
            }
            for statement in &function.statements {
                if let vexil_lang::codegen::portable::PortableStatement::Let { name, .. } =
                    statement
                {
                    reject_python_binding(name.as_str(), "local binding")?;
                }
            }
            functions.push(function);
        }
    }
    Ok(by_target)
}

fn reject_python_keyword(name: &str, subject: &str) -> Result<(), CodegenError> {
    if is_python_keyword(name) {
        Err(CodegenError::IdentifierCollision {
            name: name.to_string(),
            context: format!("{subject} is a reserved Python keyword"),
        })
    } else {
        Ok(())
    }
}

fn reject_python_binding(name: &str, subject: &str) -> Result<(), CodegenError> {
    reject_python_keyword(name, subject)?;
    if name == "self" {
        Err(CodegenError::IdentifierCollision {
            name: name.to_string(),
            context: format!("{subject} conflicts with the generated Python receiver"),
        })
    } else {
        Ok(())
    }
}

fn is_python_keyword(name: &str) -> bool {
    matches!(
        name,
        "False"
            | "None"
            | "True"
            | "and"
            | "as"
            | "assert"
            | "async"
            | "await"
            | "break"
            | "class"
            | "continue"
            | "def"
            | "del"
            | "elif"
            | "else"
            | "except"
            | "finally"
            | "for"
            | "from"
            | "global"
            | "if"
            | "import"
            | "in"
            | "is"
            | "lambda"
            | "nonlocal"
            | "not"
            | "or"
            | "pass"
            | "raise"
            | "return"
            | "try"
            | "while"
            | "with"
            | "yield"
            | "match"
            | "case"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_produces_output() {
        let result = vexil_lang::compile("namespace test.gen\nmessage Foo { x @0 : u32 }");
        let compiled = result.compiled.unwrap();
        let code = generate(&compiled).unwrap();
        assert!(code.contains("@dataclass"));
        assert!(code.contains("class Foo"));
        assert!(code.contains("def encode(self)"));
        assert!(code.contains("@staticmethod"));
        assert!(code.contains("def decode(data: bytes)"));
        assert!(code.contains(
            "from vexil_runtime import BitWriter as _BitWriter, BitReader as _BitReader"
        ));
    }

    #[test]
    fn generate_with_no_imports_matches_generate() {
        let result = vexil_lang::compile("namespace test.gen\nmessage Foo { x @0 : u32 }");
        let compiled = result.compiled.unwrap();
        let without = generate(&compiled).unwrap();
        let with = generate_with_imports(&compiled, None).unwrap();
        assert_eq!(without, with);
    }

    #[test]
    fn python_backend_generate_matches_free_function() {
        use vexil_lang::codegen::CodegenBackend;
        let result = vexil_lang::compile("namespace test.backend\nmessage Foo { x @0 : u32 }");
        let compiled = result.compiled.unwrap();
        let free_fn = generate(&compiled).unwrap();
        let backend = crate::backend::PythonBackend;
        let trait_fn = backend.generate(&compiled).unwrap();
        assert_eq!(free_fn, trait_fn);
    }

    #[test]
    fn emits_function_bearing_traits() {
        let compiled = vexil_lang::compile(
            "namespace test.function_trait\ntrait Validatable {\n    fn validate() -> bool\n}",
        )
        .compiled
        .unwrap();
        let generated = generate(&compiled).expect("function signature generates");
        assert!(generated.contains("def validate(self) -> bool:"));
    }

    #[test]
    fn rejects_trait_function_member_collisions() {
        let compiled = vexil_lang::compile(
            "namespace test.collision\ntrait Conflicting { value @0 : i32 fn value() -> i32 }",
        )
        .compiled
        .unwrap();
        assert!(matches!(
            generate(&compiled),
            Err(CodegenError::IdentifierCollision { .. })
        ));
    }

    #[test]
    fn rejects_nonportable_calls_at_codegen_boundary() {
        let compiled = vexil_lang::compile(
            "namespace test.call\ntrait Validatable { fn validate() -> bool }\nmessage Event { value @0 : bool }\nimpl Validatable for Event { fn validate() -> bool { return helper() } }",
        )
        .compiled
        .unwrap();
        assert!(matches!(
            generate(&compiled),
            Err(CodegenError::PortableFunction(
                vexil_lang::codegen::portable::PortableFunctionError::UnsupportedCall { .. }
            ))
        ));
    }

    #[test]
    fn project_codegen_imports_named_trait_for_local_impl() {
        use vexil_lang::codegen::CodegenBackend;
        use vexil_lang::resolve::InMemoryLoader;

        let root_src = "namespace proj.root\nimport { Tagged } from proj.dep\nmessage Event { tag @0 : u64 }\nimpl Tagged<u64> for Event { fn retag(tag: u64) -> u64 { self.tag = tag return self.tag } }";
        let dep_src = "namespace proj.dep\ntrait Tagged<T> { tag @0 : T fn retag(tag: T) -> T }";
        let mut loader = InMemoryLoader::new();
        loader.schemas.insert("proj.dep".into(), dep_src.into());
        let result = vexil_lang::compile_project(
            root_src,
            &std::path::PathBuf::from("proj/root.vexil"),
            &loader,
        )
        .unwrap();
        assert!(result.diagnostics.is_empty(), "{:?}", result.diagnostics);

        let files = crate::backend::PythonBackend
            .generate_project(&result)
            .unwrap();
        let root = files
            .iter()
            .find(|(path, _)| path.to_string_lossy().ends_with("root.py"))
            .map(|(_, code)| code)
            .unwrap();
        assert!(root.contains("from proj.dep import Tagged"), "{root}");
        assert!(root.contains("def retag(self, tag: int) -> int:"), "{root}");
        assert!(
            root.contains("def _vexil_assert_Event_implements_Tagged"),
            "{root}"
        );
    }

    #[test]
    fn conflicting_field_names_are_escaped_injectively() {
        let compiled = vexil_lang::compile(
            "namespace test.kw\nmessage Kw { from @0 : u32  from_ @1 : u8  self @2 : bool  unknown @3 : bytes }",
        )
        .compiled
        .expect("schema compiles");
        let code = generate(&compiled).expect("codegen succeeds");

        for escaped in ["_vexil_from", "_vexil_self", "_vexil_unknown"] {
            assert!(
                code.contains(&format!("    {escaped}: ")),
                "missing escaped field declaration {escaped} in:\n{code}"
            );
        }
        assert!(code.contains("    from_: int"), "{code}");
        assert!(
            code.contains("self._vexil_from") && code.contains("m._vexil_from ="),
            "codecs must use the escaped keyword:\n{code}"
        );
        assert!(
            code.contains("self.from_") && code.contains("m.from_ ="),
            "ordinary trailing-underscore name must remain unchanged:\n{code}"
        );
        assert!(
            code.contains("    unknown: bytes = b\"\"")
                && code.contains("    _vexil_unknown: bytes"),
            "authored unknown field and generated storage must stay distinct:\n{code}"
        );
    }

    #[test]
    fn union_decode_locals_cannot_collide_with_authored_fields() {
        let compiled = vexil_lang::compile(
            "namespace test.union_names\nunion Value { Named @0 { self @0 : u8  pr @1 : u16 } }",
        )
        .compiled
        .expect("schema compiles");
        let code = generate(&compiled).expect("codegen succeeds");

        assert!(
            code.contains("def __init__(self, _vexil_self: int, pr: int)"),
            "{code}"
        );
        assert!(
            code.contains("_vexil_payload_reader = _BitReader(_vexil_payload)"),
            "{code}"
        );
        assert!(
            code.contains("return ValueNamed(_vexil_field_0, _vexil_field_1)"),
            "{code}"
        );
        assert!(!code.contains("\n        pr = _BitReader"), "{code}");
    }

    #[test]
    fn non_keyword_field_names_are_left_alone() {
        let compiled =
            vexil_lang::compile("namespace test.kw2\nmessage Ok { match @0 : u32  hash @1 : u8 }")
                .compiled
                .expect("schema compiles");
        let code = generate(&compiled).expect("codegen succeeds");

        // `match` is a soft keyword and `hash` a builtin; both are valid identifiers.
        assert!(code.contains("    match: "), "{code}");
        assert!(code.contains("    hash: "), "{code}");
        assert!(!code.contains("match_"), "{code}");
    }

    #[test]
    fn nested_fixed_array_annotation_has_no_embedded_comment() {
        let compiled =
            vexil_lang::compile("namespace test.fa\nmessage N { a @0 : array<array<u8, 4>, 3> }")
                .compiled
                .expect("schema compiles");
        let code = generate(&compiled).expect("codegen succeeds");

        // A `#` inside a type annotation comments out the rest of the line.
        for line in code.lines() {
            let trimmed = line.trim_start();
            if trimmed.starts_with('#') {
                continue;
            }
            if let Some(hash_at) = line.find('#') {
                assert!(
                    line[..hash_at].trim_end().ends_with(']')
                        || !line[..hash_at].contains("tuple["),
                    "type annotation contains an embedded comment: {line}"
                );
            }
        }
        assert!(
            code.contains("tuple[tuple[int, ...], ...]"),
            "nested fixed array should nest cleanly:\n{code}"
        );
    }
}
