# Code generated by vexilc. DO NOT EDIT.
# Source: test.primitives

from __future__ import annotations
from dataclasses import dataclass
from typing import Optional

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import _BitWriter, _BitReader

SCHEMA_HASH: tuple[int, ...] = (0x7c, 0x63, 0xe0, 0x11, 0xba, 0x5b, 0x99, 0xab, 0x88, 0x41, 0x02, 0xf3, 0x55, 0xed, 0x30, 0x4a, 0xd3, 0x38, 0xbe, 0x28, 0x8e, 0x69, 0xac, 0x3e, 0xdf, 0x8b, 0x61, 0x99, 0x49, 0x20, 0x41, 0x01)


# ---------- AllPrimitives ----------
@dataclass
class AllPrimitives:
    a: bool
    b: int
    c: int
    d: int
    e: int
    f: int
    g: int
    h: int
    i: int
    j: float
    k: float
    l: None
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_bool(self.a)
        w.write_u8(self.b)
        w.write_u16(self.c)
        w.write_u32(self.d)
        w.write_u64(self.e)
        w.write_i8(self.f)
        w.write_i16(self.g)
        w.write_i32(self.h)
        w.write_i64(self.i)
        w.write_f32(self.j)
        w.write_f64(self.k)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        m = AllPrimitives.__new__(AllPrimitives)
        m.a = r.read_bool()
        m.b = r.read_u8()
        m.c = r.read_u16()
        m.d = r.read_u32()
        m.e = r.read_u64()
        m.f = r.read_i8()
        m.g = r.read_i16()
        m.h = r.read_i32()
        m.i = r.read_i64()
        m.j = r.read_f32()
        m.k = r.read_f64()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m


