# Code generated by vexilc. DO NOT EDIT.
# Source: test.sub_byte

from __future__ import annotations
from dataclasses import dataclass
from typing import Optional

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import _BitWriter, _BitReader

SCHEMA_HASH: tuple[int, ...] = (0xa9, 0xc6, 0x2a, 0x4b, 0xfc, 0xfb, 0x2a, 0xa6, 0x5a, 0xe5, 0x6e, 0xd3, 0x03, 0x51, 0xc4, 0xca, 0xaf, 0x02, 0x47, 0x4b, 0x04, 0xdb, 0x21, 0x05, 0xb5, 0x3c, 0x1e, 0xb0, 0x36, 0x31, 0xd2, 0x5b)


# ---------- SubByteUnsigned ----------
@dataclass
class SubByteUnsigned:
    a: int
    b: int
    c: int
    d: int
    e: int
    f: int
    g: int
    h: int
    i: int
    j: int
    k: int
    l: int
    m: int
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_bits(self.a, 1)
        w.write_bits(self.b, 2)
        w.write_bits(self.c, 3)
        w.write_bits(self.d, 4)
        w.write_bits(self.e, 5)
        w.write_bits(self.f, 6)
        w.write_bits(self.g, 7)
        w.write_bits(self.h, 9)
        w.write_bits(self.i, 15)
        w.write_bits(self.j, 17)
        w.write_bits(self.k, 31)
        w.write_bits(self.l, 33)
        w.write_bits(self.m, 63)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        m = SubByteUnsigned.__new__(SubByteUnsigned)
        m.a = r.read_bits(1)
        m.b = r.read_bits(2)
        m.c = r.read_bits(3)
        m.d = r.read_bits(4)
        m.e = r.read_bits(5)
        m.f = r.read_bits(6)
        m.g = r.read_bits(7)
        m.h = r.read_bits(9)
        m.i = r.read_bits(15)
        m.j = r.read_bits(17)
        m.k = r.read_bits(31)
        m.l = r.read_bits(33)
        m.m = r.read_bits(63)
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- SubByteSigned ----------
@dataclass
class SubByteSigned:
    a: int
    b: int
    c: int
    d: int
    e: int
    f: int
    g: int
    h: int
    i: int
    j: int
    k: int
    l: int
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_bits(self.a, 2)
        w.write_bits(self.b, 3)
        w.write_bits(self.c, 4)
        w.write_bits(self.d, 5)
        w.write_bits(self.e, 6)
        w.write_bits(self.f, 7)
        w.write_bits(self.g, 9)
        w.write_bits(self.h, 15)
        w.write_bits(self.i, 17)
        w.write_bits(self.j, 31)
        w.write_bits(self.k, 33)
        w.write_bits(self.l, 63)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        m = SubByteSigned.__new__(SubByteSigned)
        m.a = r.read_bits(2)
        m.b = r.read_bits(3)
        m.c = r.read_bits(4)
        m.d = r.read_bits(5)
        m.e = r.read_bits(6)
        m.f = r.read_bits(7)
        m.g = r.read_bits(9)
        m.h = r.read_bits(15)
        m.i = r.read_bits(17)
        m.j = r.read_bits(31)
        m.k = r.read_bits(33)
        m.l = r.read_bits(63)
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m


