# Code generated by vexilc. DO NOT EDIT.
# Source: test.semantic_types

from __future__ import annotations
from dataclasses import dataclass
from typing import Optional

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import _BitWriter, _BitReader

SCHEMA_HASH: tuple[int, ...] = (0x39, 0xb0, 0x6f, 0xca, 0x22, 0x4d, 0x88, 0x38, 0x78, 0xf8, 0x98, 0xaf, 0x9a, 0x78, 0x83, 0x90, 0x14, 0x32, 0x7e, 0x02, 0x1f, 0x50, 0x44, 0x0b, 0xa7, 0xf3, 0xee, 0xc0, 0xd8, 0x9e, 0x64, 0x99)


# ---------- AllSemantic ----------
@dataclass
class AllSemantic:
    a: str
    b: bytes
    c: tuple[int, int, int]
    d: bytes
    e: int
    f: bytes
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_string(self.a)
        w.write_bytes(self.b)
        w.write_u8(self.c[0])
        w.write_u8(self.c[1])
        w.write_u8(self.c[2])
        w.write_raw_bytes(self.d, 16)
        w.write_i64(self.e)
        w.write_raw_bytes(self.f, 32)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        m = AllSemantic.__new__(AllSemantic)
        m.a = r.read_string()
        m.b = r.read_bytes()
        r = r.read_u8()
        g = r.read_u8()
        b = r.read_u8()
        m.c = (r, g, b)
        m.d = r.read_raw_bytes(16)
        m.e = r.read_i64()
        m.f = r.read_raw_bytes(32)
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m


