# Code generated by vexilc. DO NOT EDIT.
# Source: test.parameterized

from __future__ import annotations
from dataclasses import dataclass
from typing import Optional

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import _BitWriter, _BitReader

SCHEMA_HASH: tuple[int, ...] = (0xb2, 0x56, 0xf5, 0x41, 0xe5, 0x8d, 0xeb, 0x54, 0x58, 0x21, 0xa3, 0xbe, 0x87, 0x43, 0xaa, 0xaf, 0x16, 0xe2, 0x4a, 0x3b, 0xf4, 0xdf, 0xbc, 0x74, 0x43, 0x07, 0xae, 0x2e, 0x48, 0xd6, 0x5a, 0x3f)


# ---------- Basic ----------
@dataclass
class Basic:
    a: int | None
    b: list[str]
    c: dict[str, int]
    d: tuple[bool, int | str]
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_bool(self.a is not None)
        w.flush_to_byte_boundary()
        if self.a is not None:
            w.write_u32(self.a)
        w.write_leb128(len(self.b))
        for item in {access}:
            w.write_string(item)
        w.write_leb128(len(self.c))
        for map_k, map_v in self.c.items():
            w.write_string(map_k)
            w.write_u64(map_v)
        if self.d[0]:
            w.write_bool(True)
            w.write_u32(self.d[1])
        else:
            w.write_bool(False)
            w.write_string(self.d[1])
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        m = Basic.__new__(Basic)
        present = r.read_bool()
        r.flush_to_byte_boundary()
        if present:
            m.a: int = None  # type: ignore[assignment]
            m.a = r.read_u32()
        else:
            m.a = None
        arr_len = r.read_leb128()
        m.b: list[str] = []
        for _ in range(arr_len):
            _item: str = None  # type: ignore[assignment]
            _item = r.read_string()
            m.b.append(_item)
        map_len = r.read_leb128()
        m.c: dict[str, int] = {}
        for _ in range(map_len):
            _k: str = None  # type: ignore[assignment]
            _v: int = None  # type: ignore[assignment]
            _k = r.read_string()
            _v = r.read_u64()
            m.c[_k] = _v
        is_ok = r.read_bool()
        if is_ok:
            _ok_val: int = None  # type: ignore[assignment]
            _ok_val = r.read_u32()
            m.d = (True, _ok_val)
        else:
            _err_val: str = None  # type: ignore[assignment]
            _err_val = r.read_string()
            m.d = (False, _err_val)
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- Nested ----------
@dataclass
class Nested:
    a: list[str] | None
    b: list[int | None]
    c: dict[str, list[int]]
    d: tuple[bool, None | str]
    e: tuple[bool, str | None]
    f: tuple[bool, None | None]
    g: tuple[bool, list[str] | dict[int, str]] | None
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_bool(self.a is not None)
        w.flush_to_byte_boundary()
        if self.a is not None:
            w.write_leb128(len(self.a))
            for item in {access}:
                w.write_string(item)
        w.write_leb128(len(self.b))
        for item in {access}:
            w.write_bool(item is not None)
            w.flush_to_byte_boundary()
            if item is not None:
                w.write_u32(item)
        w.write_leb128(len(self.c))
        for map_k, map_v in self.c.items():
            w.write_string(map_k)
            w.write_leb128(len(map_v))
            for item in {access}:
                w.write_u8(item)
        if self.d[0]:
            w.write_bool(True)
        else:
            w.write_bool(False)
            w.write_string(self.d[1])
        if self.e[0]:
            w.write_bool(True)
            w.write_string(self.e[1])
        else:
            w.write_bool(False)
        if self.f[0]:
            w.write_bool(True)
        else:
            w.write_bool(False)
        w.write_bool(self.g is not None)
        w.flush_to_byte_boundary()
        if self.g is not None:
            if self.g[0]:
                w.write_bool(True)
                w.write_leb128(len(self.g[1]))
                for item in {access}:
                    w.write_string(item)
            else:
                w.write_bool(False)
                w.write_leb128(len(self.g[1]))
                for map_k, map_v in self.g[1].items():
                    w.write_u32(map_k)
                    w.write_string(map_v)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        m = Nested.__new__(Nested)
        present = r.read_bool()
        r.flush_to_byte_boundary()
        if present:
            m.a: list[str] = None  # type: ignore[assignment]
            arr_len = r.read_leb128()
            m.a: list[str] = []
            for _ in range(arr_len):
                _item: str = None  # type: ignore[assignment]
                _item = r.read_string()
                m.a.append(_item)
        else:
            m.a = None
        arr_len = r.read_leb128()
        m.b: list[int | None] = []
        for _ in range(arr_len):
            _item: int | None = None  # type: ignore[assignment]
            present = r.read_bool()
            r.flush_to_byte_boundary()
            if present:
                _item: int = None  # type: ignore[assignment]
                _item = r.read_u32()
            else:
                _item = None
            m.b.append(_item)
        map_len = r.read_leb128()
        m.c: dict[str, list[int]] = {}
        for _ in range(map_len):
            _k: str = None  # type: ignore[assignment]
            _v: list[int] = None  # type: ignore[assignment]
            _k = r.read_string()
            arr_len = r.read_leb128()
            _v: list[int] = []
            for _ in range(arr_len):
                _item: int = None  # type: ignore[assignment]
                _item = r.read_u8()
                _v.append(_item)
            m.c[_k] = _v
        is_ok = r.read_bool()
        if is_ok:
            _ok_val: None = None  # type: ignore[assignment]
            m.d = (True, _ok_val)
        else:
            _err_val: str = None  # type: ignore[assignment]
            _err_val = r.read_string()
            m.d = (False, _err_val)
        is_ok = r.read_bool()
        if is_ok:
            _ok_val: str = None  # type: ignore[assignment]
            _ok_val = r.read_string()
            m.e = (True, _ok_val)
        else:
            _err_val: None = None  # type: ignore[assignment]
            m.e = (False, _err_val)
        is_ok = r.read_bool()
        if is_ok:
            _ok_val: None = None  # type: ignore[assignment]
            m.f = (True, _ok_val)
        else:
            _err_val: None = None  # type: ignore[assignment]
            m.f = (False, _err_val)
        present = r.read_bool()
        r.flush_to_byte_boundary()
        if present:
            m.g: tuple[bool, list[str] | dict[int, str]] = None  # type: ignore[assignment]
            is_ok = r.read_bool()
            if is_ok:
                _ok_val: list[str] = None  # type: ignore[assignment]
                arr_len = r.read_leb128()
                _ok_val: list[str] = []
                for _ in range(arr_len):
                    _item: str = None  # type: ignore[assignment]
                    _item = r.read_string()
                    _ok_val.append(_item)
                m.g = (True, _ok_val)
            else:
                _err_val: dict[int, str] = None  # type: ignore[assignment]
                map_len = r.read_leb128()
                _err_val: dict[int, str] = {}
                for _ in range(map_len):
                    _k: int = None  # type: ignore[assignment]
                    _v: str = None  # type: ignore[assignment]
                    _k = r.read_u32()
                    _v = r.read_string()
                    _err_val[_k] = _v
                m.g = (False, _err_val)
        else:
            m.g = None
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m


