# Code generated by vexilc. DO NOT EDIT.
# Source: test.parameterized

from __future__ import annotations
from dataclasses import dataclass

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import BitWriter as _BitWriter, BitReader as _BitReader, DecodeError

SCHEMA_HASH: tuple[int, ...] = (0xb2, 0x56, 0xf5, 0x41, 0xe5, 0x8d, 0xeb, 0x54, 0x58, 0x21, 0xa3, 0xbe, 0x87, 0x43, 0xaa, 0xaf, 0x16, 0xe2, 0x4a, 0x3b, 0xf4, 0xdf, 0xbc, 0x74, 0x43, 0x07, 0xae, 0x2e, 0x48, 0xd6, 0x5a, 0x3f)


# ---------- Basic ----------
@dataclass
class Basic:
    a: int | None
    b: list[str]
    c: dict[str, int]
    d: tuple[bool, int | str]
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        _vexil_self_2e_a_optional = self.a
        w.write_bool(_vexil_self_2e_a_optional is not None)
        w.flush_to_byte_boundary()
        if _vexil_self_2e_a_optional is not None:
            w.write_u32(_vexil_self_2e_a_optional)
        w.write_leb128(len(self.b))
        for _vexil_self_2e_b_array_item in self.b:
            w.write_string(_vexil_self_2e_b_array_item)
        w.write_leb128(len(self.c))
        for _vexil_self_2e_c_map_key in sorted(self.c):
            _vexil_self_2e_c_map_value = self.c[_vexil_self_2e_c_map_key]
            w.write_string(_vexil_self_2e_c_map_key)
            w.write_u64(_vexil_self_2e_c_map_value)
        if self.d[0]:
            w.write_bool(True)
            w.write_u32(self.d[1])
        else:
            w.write_bool(False)
            w.write_string(self.d[1])
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> Basic:
        r = _BitReader(data)
        return Basic.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader) -> Basic:
        m = Basic.__new__(Basic)
        try:
            _vexil_m_2e_a_present = r.read_bool()
        except DecodeError:
            m.a = None
        else:
            r.flush_to_byte_boundary()
            if _vexil_m_2e_a_present:
                m.a = r.read_u32()
            else:
                m.a = None
        _vexil_m_2e_b_array_length = r.read_leb128()
        _vexil_m_2e_b_array_items: list[str] = []
        for _ in range(_vexil_m_2e_b_array_length):
            _vexil_m_2e_b_array_item = r.read_string()
            _vexil_m_2e_b_array_items.append(_vexil_m_2e_b_array_item)
        m.b = _vexil_m_2e_b_array_items
        _vexil_m_2e_c_map_length = r.read_leb128()
        _vexil_m_2e_c_map_items: dict[str, int] = {}
        for _ in range(_vexil_m_2e_c_map_length):
            _vexil_m_2e_c_map_key = r.read_string()
            _vexil_m_2e_c_map_value = r.read_u64()
            _vexil_m_2e_c_map_items[_vexil_m_2e_c_map_key] = _vexil_m_2e_c_map_value
        m.c = _vexil_m_2e_c_map_items
        _vexil_m_2e_d_result_is_ok = r.read_bool()
        if _vexil_m_2e_d_result_is_ok:
            _vexil_m_2e_d_result_ok = r.read_u32()
            m.d = (True, _vexil_m_2e_d_result_ok)
        else:
            _vexil_m_2e_d_result_err = r.read_string()
            m.d = (False, _vexil_m_2e_d_result_err)
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- Nested ----------
@dataclass
class Nested:
    a: list[str] | None
    b: list[int | None]
    c: dict[str, list[int]]
    d: tuple[bool, None | str]
    e: tuple[bool, str | None]
    f: tuple[bool, None | None]
    g: tuple[bool, list[str] | dict[int, str]] | None
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        _vexil_self_2e_a_optional = self.a
        w.write_bool(_vexil_self_2e_a_optional is not None)
        w.flush_to_byte_boundary()
        if _vexil_self_2e_a_optional is not None:
            w.write_leb128(len(_vexil_self_2e_a_optional))
            for _vexil__5f_vexil_5f_self_5f_2e_5f_a_5f_optional_array_item in _vexil_self_2e_a_optional:
                w.write_string(_vexil__5f_vexil_5f_self_5f_2e_5f_a_5f_optional_array_item)
        w.write_leb128(len(self.b))
        for _vexil_self_2e_b_array_item in self.b:
            _vexil__5f_vexil_5f_self_5f_2e_5f_b_5f_array_5f_item_optional = _vexil_self_2e_b_array_item
            w.write_bool(_vexil__5f_vexil_5f_self_5f_2e_5f_b_5f_array_5f_item_optional is not None)
            w.flush_to_byte_boundary()
            if _vexil__5f_vexil_5f_self_5f_2e_5f_b_5f_array_5f_item_optional is not None:
                w.write_u32(_vexil__5f_vexil_5f_self_5f_2e_5f_b_5f_array_5f_item_optional)
        w.write_leb128(len(self.c))
        for _vexil_self_2e_c_map_key in sorted(self.c):
            _vexil_self_2e_c_map_value = self.c[_vexil_self_2e_c_map_key]
            w.write_string(_vexil_self_2e_c_map_key)
            w.write_leb128(len(_vexil_self_2e_c_map_value))
            for _vexil__5f_vexil_5f_self_5f_2e_5f_c_5f_map_5f_value_array_item in _vexil_self_2e_c_map_value:
                w.write_u8(_vexil__5f_vexil_5f_self_5f_2e_5f_c_5f_map_5f_value_array_item)
        if self.d[0]:
            w.write_bool(True)
        else:
            w.write_bool(False)
            w.write_string(self.d[1])
        if self.e[0]:
            w.write_bool(True)
            w.write_string(self.e[1])
        else:
            w.write_bool(False)
        if self.f[0]:
            w.write_bool(True)
        else:
            w.write_bool(False)
        _vexil_self_2e_g_optional = self.g
        w.write_bool(_vexil_self_2e_g_optional is not None)
        w.flush_to_byte_boundary()
        if _vexil_self_2e_g_optional is not None:
            if _vexil_self_2e_g_optional[0]:
                w.write_bool(True)
                w.write_leb128(len(_vexil_self_2e_g_optional[1]))
                for _vexil__5f_vexil_5f_self_5f_2e_5f_g_5f_optional_5b_1_5d__array_item in _vexil_self_2e_g_optional[1]:
                    w.write_string(_vexil__5f_vexil_5f_self_5f_2e_5f_g_5f_optional_5b_1_5d__array_item)
            else:
                w.write_bool(False)
                w.write_leb128(len(_vexil_self_2e_g_optional[1]))
                for _vexil__5f_vexil_5f_self_5f_2e_5f_g_5f_optional_5b_1_5d__map_key, _vexil__5f_vexil_5f_self_5f_2e_5f_g_5f_optional_5b_1_5d__map_value in _vexil_self_2e_g_optional[1].items():
                    w.write_u32(_vexil__5f_vexil_5f_self_5f_2e_5f_g_5f_optional_5b_1_5d__map_key)
                    w.write_string(_vexil__5f_vexil_5f_self_5f_2e_5f_g_5f_optional_5b_1_5d__map_value)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> Nested:
        r = _BitReader(data)
        return Nested.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader) -> Nested:
        m = Nested.__new__(Nested)
        try:
            _vexil_m_2e_a_present = r.read_bool()
        except DecodeError:
            m.a = None
        else:
            r.flush_to_byte_boundary()
            if _vexil_m_2e_a_present:
                _vexil_m_2e_a_array_length = r.read_leb128()
                _vexil_m_2e_a_array_items: list[str] = []
                for _ in range(_vexil_m_2e_a_array_length):
                    _vexil_m_2e_a_array_item = r.read_string()
                    _vexil_m_2e_a_array_items.append(_vexil_m_2e_a_array_item)
                m.a = _vexil_m_2e_a_array_items
            else:
                m.a = None
        _vexil_m_2e_b_array_length = r.read_leb128()
        _vexil_m_2e_b_array_items: list[int | None] = []
        for _ in range(_vexil_m_2e_b_array_length):
            try:
                _vexil__5f_vexil_5f_m_5f_2e_5f_b_5f_array_5f_item_present = r.read_bool()
            except DecodeError:
                _vexil_m_2e_b_array_item = None
            else:
                r.flush_to_byte_boundary()
                if _vexil__5f_vexil_5f_m_5f_2e_5f_b_5f_array_5f_item_present:
                    _vexil_m_2e_b_array_item = r.read_u32()
                else:
                    _vexil_m_2e_b_array_item = None
            _vexil_m_2e_b_array_items.append(_vexil_m_2e_b_array_item)
        m.b = _vexil_m_2e_b_array_items
        _vexil_m_2e_c_map_length = r.read_leb128()
        _vexil_m_2e_c_map_items: dict[str, list[int]] = {}
        for _ in range(_vexil_m_2e_c_map_length):
            _vexil_m_2e_c_map_key = r.read_string()
            _vexil__5f_vexil_5f_m_5f_2e_5f_c_5f_map_5f_value_array_length = r.read_leb128()
            _vexil__5f_vexil_5f_m_5f_2e_5f_c_5f_map_5f_value_array_items: list[int] = []
            for _ in range(_vexil__5f_vexil_5f_m_5f_2e_5f_c_5f_map_5f_value_array_length):
                _vexil__5f_vexil_5f_m_5f_2e_5f_c_5f_map_5f_value_array_item = r.read_u8()
                _vexil__5f_vexil_5f_m_5f_2e_5f_c_5f_map_5f_value_array_items.append(_vexil__5f_vexil_5f_m_5f_2e_5f_c_5f_map_5f_value_array_item)
            _vexil_m_2e_c_map_value = _vexil__5f_vexil_5f_m_5f_2e_5f_c_5f_map_5f_value_array_items
            _vexil_m_2e_c_map_items[_vexil_m_2e_c_map_key] = _vexil_m_2e_c_map_value
        m.c = _vexil_m_2e_c_map_items
        _vexil_m_2e_d_result_is_ok = r.read_bool()
        if _vexil_m_2e_d_result_is_ok:
            _vexil_m_2e_d_result_ok = None
            m.d = (True, _vexil_m_2e_d_result_ok)
        else:
            _vexil_m_2e_d_result_err = r.read_string()
            m.d = (False, _vexil_m_2e_d_result_err)
        _vexil_m_2e_e_result_is_ok = r.read_bool()
        if _vexil_m_2e_e_result_is_ok:
            _vexil_m_2e_e_result_ok = r.read_string()
            m.e = (True, _vexil_m_2e_e_result_ok)
        else:
            _vexil_m_2e_e_result_err = None
            m.e = (False, _vexil_m_2e_e_result_err)
        _vexil_m_2e_f_result_is_ok = r.read_bool()
        if _vexil_m_2e_f_result_is_ok:
            _vexil_m_2e_f_result_ok = None
            m.f = (True, _vexil_m_2e_f_result_ok)
        else:
            _vexil_m_2e_f_result_err = None
            m.f = (False, _vexil_m_2e_f_result_err)
        try:
            _vexil_m_2e_g_present = r.read_bool()
        except DecodeError:
            m.g = None
        else:
            r.flush_to_byte_boundary()
            if _vexil_m_2e_g_present:
                _vexil_m_2e_g_result_is_ok = r.read_bool()
                if _vexil_m_2e_g_result_is_ok:
                    _vexil__5f_vexil_5f_m_5f_2e_5f_g_5f_result_5f_ok_array_length = r.read_leb128()
                    _vexil__5f_vexil_5f_m_5f_2e_5f_g_5f_result_5f_ok_array_items: list[str] = []
                    for _ in range(_vexil__5f_vexil_5f_m_5f_2e_5f_g_5f_result_5f_ok_array_length):
                        _vexil__5f_vexil_5f_m_5f_2e_5f_g_5f_result_5f_ok_array_item = r.read_string()
                        _vexil__5f_vexil_5f_m_5f_2e_5f_g_5f_result_5f_ok_array_items.append(_vexil__5f_vexil_5f_m_5f_2e_5f_g_5f_result_5f_ok_array_item)
                    _vexil_m_2e_g_result_ok = _vexil__5f_vexil_5f_m_5f_2e_5f_g_5f_result_5f_ok_array_items
                    m.g = (True, _vexil_m_2e_g_result_ok)
                else:
                    _vexil__5f_vexil_5f_m_5f_2e_5f_g_5f_result_5f_err_map_length = r.read_leb128()
                    _vexil__5f_vexil_5f_m_5f_2e_5f_g_5f_result_5f_err_map_items: dict[int, str] = {}
                    for _ in range(_vexil__5f_vexil_5f_m_5f_2e_5f_g_5f_result_5f_err_map_length):
                        _vexil__5f_vexil_5f_m_5f_2e_5f_g_5f_result_5f_err_map_key = r.read_u32()
                        _vexil__5f_vexil_5f_m_5f_2e_5f_g_5f_result_5f_err_map_value = r.read_string()
                        _vexil__5f_vexil_5f_m_5f_2e_5f_g_5f_result_5f_err_map_items[_vexil__5f_vexil_5f_m_5f_2e_5f_g_5f_result_5f_err_map_key] = _vexil__5f_vexil_5f_m_5f_2e_5f_g_5f_result_5f_err_map_value
                    _vexil_m_2e_g_result_err = _vexil__5f_vexil_5f_m_5f_2e_5f_g_5f_result_5f_err_map_items
                    m.g = (False, _vexil_m_2e_g_result_err)
            else:
                m.g = None
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m


