# Code generated by vexilc. DO NOT EDIT.
# Source: test.message

from __future__ import annotations
from dataclasses import dataclass
from typing import Optional

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import _BitWriter, _BitReader

SCHEMA_HASH: tuple[int, ...] = (0x97, 0xbc, 0xeb, 0x17, 0x56, 0x6b, 0xc1, 0xda, 0x25, 0x18, 0x59, 0x62, 0x39, 0x6c, 0xdf, 0x60, 0x32, 0x7b, 0xac, 0xce, 0x89, 0x7b, 0x85, 0xb7, 0x17, 0xfa, 0x73, 0xbd, 0xbe, 0xe5, 0x98, 0x01)


# ---------- Empty ----------
@dataclass
class Empty:
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        m = Empty.__new__(Empty)
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- WithGaps ----------
@dataclass
class WithGaps:
    first: int
    third: int
    tenth: str
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_u32(self.first)
        w.write_u32(self.third)
        w.write_string(self.tenth)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        m = WithGaps.__new__(WithGaps)
        m.first = r.read_u32()
        m.third = r.read_u32()
        m.tenth = r.read_string()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- Annotated ----------
@dataclass
class Annotated:
    version: int
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_u8(self.version)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        m = Annotated.__new__(Annotated)
        m.version = r.read_u8()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- FieldAnnotations ----------
@dataclass
class FieldAnnotations:
    a: int
    b: int
    c: str
    d: int
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_u32(self.a)
        w.write_leb128(self.b)
        w.write_string(self.c)
        w.write_i32(self.d)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        m = FieldAnnotations.__new__(FieldAnnotations)
        m.a = r.read_u32()
        m.b = r.read_leb128()
        m.c = r.read_string()
        m.d = r.read_i32()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m


class FieldAnnotationsEncoder:

    def __init__(self):
        self._prev_d: int = 0

    def encode(self, val: FieldAnnotations) -> bytes:
        w = _BitWriter()
        w.write_u32(val.A)
        w.write_leb128(val.B)
        w.write_string(val.C)
        delta_d = val.D - self._prev_d
        w.write_i32(delta_d)
        self._prev_d = val.D
        w.flush_to_byte_boundary()
        return w.finish()

    def reset(self):
        self._prev_d = 0

class FieldAnnotationsDecoder:

    def __init__(self):
        self._prev_d: int = 0

    def decode(self, data: bytes) -> FieldAnnotations:
        r = _BitReader(data)
        m = FieldAnnotations.__new__(FieldAnnotations)
        m.A = r.read_u32()
        m.B = r.read_leb128()
        m.C = r.read_string()
        delta_d = None
        delta_d = r.read_i32()
        m.D = self._prev_d + delta_d
        self._prev_d = m.D
        r.flush_to_byte_boundary()
        return m

    def reset(self):
        self._prev_d = 0

