# Code generated by vexilc. DO NOT EDIT.
# Source: test.enums

from __future__ import annotations

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import BitWriter as _BitWriter, BitReader as _BitReader

SCHEMA_HASH: tuple[int, ...] = (0x8a, 0xc5, 0x25, 0xce, 0x0a, 0xec, 0xba, 0x7a, 0xf1, 0x28, 0xaf, 0x30, 0xbc, 0x21, 0x43, 0xe0, 0xfa, 0x59, 0x1b, 0x4a, 0x62, 0xf6, 0xd7, 0x19, 0x90, 0x74, 0xe9, 0xca, 0x84, 0x9e, 0x34, 0x68)


# ---------- Direction ----------
class Direction(int):
    NORTH = 0
    SOUTH = 1
    EAST = 2
    WEST = 3

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_bits(int(self), 2)

    @staticmethod
    def decode(data: bytes) -> Direction:
        r = _BitReader(data)
        return Direction.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader) -> Direction:
        v = r.read_bits(2)
        return Direction(v)

    def __repr__(self) -> str:
        return f"Direction({int(self)})"


# ---------- ClientKind ----------
class ClientKind(int):
    RENDERER = 0
    AGENT = 1
    PLUGIN = 2
    SHELL = 3

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_bits(int(self), 8)

    @staticmethod
    def decode(data: bytes) -> ClientKind:
        r = _BitReader(data)
        return ClientKind.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader) -> ClientKind:
        v = r.read_bits(8)
        return ClientKind(v)

    def __repr__(self) -> str:
        return f"ClientKind({int(self)})"


# ---------- HardwareStatus ----------
class HardwareStatus(int):
    OK = 0
    WARN = 1
    FAULT = 2

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_bits(int(self), 16)

    @staticmethod
    def decode(data: bytes) -> HardwareStatus:
        r = _BitReader(data)
        return HardwareStatus.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader) -> HardwareStatus:
        v = r.read_bits(16)
        return HardwareStatus(v)

    def __repr__(self) -> str:
        return f"HardwareStatus({int(self)})"


# ---------- Sparse ----------
class Sparse(int):
    LOW = 0
    HIGH = 1000

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_bits(int(self), 32)

    @staticmethod
    def decode(data: bytes) -> Sparse:
        r = _BitReader(data)
        return Sparse.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader) -> Sparse:
        v = r.read_bits(32)
        return Sparse(v)

    def __repr__(self) -> str:
        return f"Sparse({int(self)})"


# ---------- Lifecycle ----------
class Lifecycle(int):
    ACTIVE = 0
    PENDING = 2

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_bits(int(self), 2)

    @staticmethod
    def decode(data: bytes) -> Lifecycle:
        r = _BitReader(data)
        return Lifecycle.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader) -> Lifecycle:
        v = r.read_bits(2)
        return Lifecycle(v)

    def __repr__(self) -> str:
        return f"Lifecycle({int(self)})"
