# Code generated by vexilc. DO NOT EDIT.
# Source: test.imports

from __future__ import annotations
from dataclasses import dataclass

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import BitWriter as _BitWriter, BitReader as _BitReader

SCHEMA_HASH: tuple[int, ...] = (0xe6, 0x77, 0xbb, 0x9e, 0xff, 0x71, 0x0e, 0x00, 0xdf, 0x90, 0x26, 0x63, 0x68, 0xcb, 0x1b, 0x47, 0xd2, 0xc3, 0x00, 0xb2, 0x61, 0x64, 0x63, 0x0e, 0x84, 0xa1, 0x59, 0xaa, 0x40, 0x77, 0xb2, 0xd9)


# ---------- UseImports ----------
@dataclass
class UseImports:
    session: object
    shape: object
    kind: object
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        try:
            w.enter_nested()
            self.encode_to(w)
        finally:
            w.leave_nested()
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        try:
            w.enter_nested()
            # Unknown type: Unknown
        finally:
            w.leave_nested()
        try:
            w.enter_nested()
            # Unknown type: Unknown
        finally:
            w.leave_nested()
        try:
            w.enter_nested()
            # Unknown type: Unknown
        finally:
            w.leave_nested()
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> UseImports:
        r = _BitReader(data)
        try:
            r.enter_nested()
            return UseImports.decode_from(r)
        finally:
            r.leave_nested()

    @staticmethod
    def decode_from(r: _BitReader) -> UseImports:
        m = UseImports.__new__(UseImports)
        try:
            r.enter_nested()
            # Unknown type: Unknown
        finally:
            r.leave_nested()
        try:
            r.enter_nested()
            # Unknown type: Unknown
        finally:
            r.leave_nested()
        try:
            r.enter_nested()
            # Unknown type: Unknown
        finally:
            r.leave_nested()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m
