# Code generated by vexilc. DO NOT EDIT.
# Source: test.annotations

from __future__ import annotations
from dataclasses import dataclass

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import BitWriter as _BitWriter, BitReader as _BitReader

SCHEMA_HASH: tuple[int, ...] = (0x79, 0x11, 0xcd, 0x44, 0x04, 0x6d, 0x10, 0x7a, 0xf1, 0xf1, 0x82, 0x9b, 0x7b, 0x72, 0x7b, 0x36, 0x1c, 0x74, 0xbf, 0x08, 0x23, 0xb7, 0x7d, 0xec, 0x49, 0x18, 0xe9, 0xd4, 0xe0, 0xb3, 0x05, 0x67)
SCHEMA_VERSION: str = "1.2.0"


# ---------- OldMessage ----------
@dataclass
class OldMessage:
    value: int
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        try:
            w.enter_nested()
            self.encode_to(w)
        finally:
            w.leave_nested()
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_u32(self.value)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> OldMessage:
        r = _BitReader(data)
        try:
            r.enter_nested()
            return OldMessage.decode_from(r)
        finally:
            r.leave_nested()

    @staticmethod
    def decode_from(r: _BitReader) -> OldMessage:
        m = OldMessage.__new__(OldMessage)
        m.value = r.read_u32()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- Lifecycle ----------
@dataclass
class Lifecycle:
    name: str
    email: str
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        try:
            w.enter_nested()
            self.encode_to(w)
        finally:
            w.leave_nested()
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_string(self.name)
        w.write_string(self.email)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> Lifecycle:
        r = _BitReader(data)
        try:
            r.enter_nested()
            return Lifecycle.decode_from(r)
        finally:
            r.leave_nested()

    @staticmethod
    def decode_from(r: _BitReader) -> Lifecycle:
        m = Lifecycle.__new__(Lifecycle)
        m.name = r.read_string()
        m.email = r.read_string()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- Encoded ----------
@dataclass
class Encoded:
    count: int
    delta: int
    offset: int
    smooth: int
    signed: int
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        try:
            w.enter_nested()
            self.encode_to(w)
        finally:
            w.leave_nested()
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_leb128(self.count)
        w.write_zigzag(self.delta)
        w.write_u64(self.offset)
        w.write_leb128(self.smooth)
        w.write_zigzag(self.signed)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> Encoded:
        r = _BitReader(data)
        try:
            r.enter_nested()
            return Encoded.decode_from(r)
        finally:
            r.leave_nested()

    @staticmethod
    def decode_from(r: _BitReader) -> Encoded:
        m = Encoded.__new__(Encoded)
        m.count = r.read_leb128()
        m.delta = r.read_zigzag()
        m.offset = r.read_u64()
        m.smooth = r.read_leb128()
        m.signed = r.read_zigzag()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m


class EncodedEncoder:

    def __init__(self):
        self._prev_offset: int = 0
        self._prev_smooth: int = 0
        self._prev_signed: int = 0

    def encode(self, val: Encoded) -> bytes:
        w = _BitWriter()
        w.write_leb128(val.count)
        w.write_zigzag(val.delta)
        delta_offset = val.offset - self._prev_offset
        w.write_u64(delta_offset)
        self._prev_offset = val.offset
        delta_smooth = val.smooth - self._prev_smooth
        w.write_leb128(delta_smooth)
        self._prev_smooth = val.smooth
        delta_signed = val.signed - self._prev_signed
        w.write_zigzag(delta_signed)
        self._prev_signed = val.signed
        w.flush_to_byte_boundary()
        return w.finish()

    def reset(self):
        self._prev_offset = 0
        self._prev_smooth = 0
        self._prev_signed = 0

class EncodedDecoder:

    def __init__(self):
        self._prev_offset: int = 0
        self._prev_smooth: int = 0
        self._prev_signed: int = 0

    def decode(self, data: bytes) -> Encoded:
        r = _BitReader(data)
        m = Encoded.__new__(Encoded)
        m.count = r.read_leb128()
        m.delta = r.read_zigzag()
        delta_offset = None
        delta_offset = r.read_u64()
        m.offset = self._prev_offset + delta_offset
        self._prev_offset = m.offset
        delta_smooth = None
        delta_smooth = r.read_leb128()
        m.smooth = self._prev_smooth + delta_smooth
        self._prev_smooth = m.smooth
        delta_signed = None
        delta_signed = r.read_zigzag()
        m.signed = self._prev_signed + delta_signed
        self._prev_signed = m.signed
        r.flush_to_byte_boundary()
        return m

    def reset(self):
        self._prev_offset = 0
        self._prev_smooth = 0
        self._prev_signed = 0


# ---------- Limited ----------
@dataclass
class Limited:
    body: str
    tags: list[str]
    headers: dict[str, str]
    data: bytes
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        try:
            w.enter_nested()
            self.encode_to(w)
        finally:
            w.leave_nested()
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_string(self.body)
        w.write_leb128(len(self.tags))
        for _vexil_self_2e_tags_array_item in self.tags:
            w.write_string(_vexil_self_2e_tags_array_item)
        w.write_leb128(len(self.headers))
        for _vexil_self_2e_headers_map_key in sorted(self.headers):
            _vexil_self_2e_headers_map_value = self.headers[_vexil_self_2e_headers_map_key]
            w.write_string(_vexil_self_2e_headers_map_key)
            w.write_string(_vexil_self_2e_headers_map_value)
        w.write_bytes(self.data)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> Limited:
        r = _BitReader(data)
        try:
            r.enter_nested()
            return Limited.decode_from(r)
        finally:
            r.leave_nested()

    @staticmethod
    def decode_from(r: _BitReader) -> Limited:
        m = Limited.__new__(Limited)
        m.body = r.read_string()
        _vexil_m_2e_tags_array_length = r.read_leb128()
        _vexil_m_2e_tags_array_items: list[str] = []
        for _ in range(_vexil_m_2e_tags_array_length):
            _vexil_m_2e_tags_array_item = r.read_string()
            _vexil_m_2e_tags_array_items.append(_vexil_m_2e_tags_array_item)
        m.tags = _vexil_m_2e_tags_array_items
        _vexil_m_2e_headers_map_length = r.read_leb128()
        _vexil_m_2e_headers_map_items: dict[str, str] = {}
        for _ in range(_vexil_m_2e_headers_map_length):
            _vexil_m_2e_headers_map_key = r.read_string()
            _vexil_m_2e_headers_map_value = r.read_string()
            _vexil_m_2e_headers_map_items[_vexil_m_2e_headers_map_key] = _vexil_m_2e_headers_map_value
        m.headers = _vexil_m_2e_headers_map_items
        _vexil_m_2e_data_length = r.read_leb128()
        m.data = r.read_bytes(_vexil_m_2e_data_length)
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- RenderCommand ----------
@dataclass
class RenderCommand:
    op: int
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        try:
            w.enter_nested()
            self.encode_to(w)
        finally:
            w.leave_nested()
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_u8(self.op)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> RenderCommand:
        r = _BitReader(data)
        try:
            r.enter_nested()
            return RenderCommand.decode_from(r)
        finally:
            r.leave_nested()

    @staticmethod
    def decode_from(r: _BitReader) -> RenderCommand:
        m = RenderCommand.__new__(RenderCommand)
        m.op = r.read_u8()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- Documented ----------
@dataclass
class Documented:
    value: int
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        try:
            w.enter_nested()
            self.encode_to(w)
        finally:
            w.leave_nested()
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_u32(self.value)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> Documented:
        r = _BitReader(data)
        try:
            r.enter_nested()
            return Documented.decode_from(r)
        finally:
            r.leave_nested()

    @staticmethod
    def decode_from(r: _BitReader) -> Documented:
        m = Documented.__new__(Documented)
        m.value = r.read_u32()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m

__all__ = ["dataclass", "SCHEMA_HASH", "SCHEMA_VERSION", "OldMessage", "Lifecycle", "Encoded", "EncodedEncoder", "EncodedDecoder", "Limited", "RenderCommand", "Documented"]
