# Code generated by vexilc. DO NOT EDIT.
# Source: test.annotations

from __future__ import annotations
from dataclasses import dataclass
from typing import Optional

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import _BitWriter, _BitReader

SCHEMA_HASH: tuple[int, ...] = (0x79, 0x11, 0xcd, 0x44, 0x04, 0x6d, 0x10, 0x7a, 0xf1, 0xf1, 0x82, 0x9b, 0x7b, 0x72, 0x7b, 0x36, 0x1c, 0x74, 0xbf, 0x08, 0x23, 0xb7, 0x7d, 0xec, 0x49, 0x18, 0xe9, 0xd4, 0xe0, 0xb3, 0x05, 0x67)
SCHEMA_VERSION: str = "1.2.0"


# ---------- OldMessage ----------
@dataclass
class OldMessage:
    value: int
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_u32(self.value)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        m = OldMessage.__new__(OldMessage)
        m.value = r.read_u32()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- Lifecycle ----------
@dataclass
class Lifecycle:
    name: str
    email: str
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_string(self.name)
        w.write_string(self.email)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        m = Lifecycle.__new__(Lifecycle)
        m.name = r.read_string()
        m.email = r.read_string()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- Encoded ----------
@dataclass
class Encoded:
    count: int
    delta: int
    offset: int
    smooth: int
    signed: int
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_leb128(self.count)
        w.write_zigzag(self.delta)
        w.write_u64(self.offset)
        w.write_leb128(self.smooth)
        w.write_zigzag(self.signed)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        m = Encoded.__new__(Encoded)
        m.count = r.read_leb128()
        m.delta = r.read_zigzag()
        m.offset = r.read_u64()
        m.smooth = r.read_leb128()
        m.signed = r.read_zigzag()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m


class EncodedEncoder:

    def __init__(self):
        self._prev_offset: int = 0
        self._prev_smooth: int = 0
        self._prev_signed: int = 0

    def encode(self, val: Encoded) -> bytes:
        w = _BitWriter()
        w.write_leb128(val.Count)
        w.write_zigzag(val.Delta)
        delta_offset = val.Offset - self._prev_offset
        w.write_u64(delta_offset)
        self._prev_offset = val.Offset
        delta_smooth = val.Smooth - self._prev_smooth
        w.write_leb128(delta_smooth)
        self._prev_smooth = val.Smooth
        delta_signed = val.Signed - self._prev_signed
        w.write_zigzag(delta_signed)
        self._prev_signed = val.Signed
        w.flush_to_byte_boundary()
        return w.finish()

    def reset(self):
        self._prev_offset = 0
        self._prev_smooth = 0
        self._prev_signed = 0

class EncodedDecoder:

    def __init__(self):
        self._prev_offset: int = 0
        self._prev_smooth: int = 0
        self._prev_signed: int = 0

    def decode(self, data: bytes) -> Encoded:
        r = _BitReader(data)
        m = Encoded.__new__(Encoded)
        m.Count = r.read_leb128()
        m.Delta = r.read_zigzag()
        delta_offset = None
        delta_offset = r.read_u64()
        m.Offset = self._prev_offset + delta_offset
        self._prev_offset = m.Offset
        delta_smooth = None
        delta_smooth = r.read_leb128()
        m.Smooth = self._prev_smooth + delta_smooth
        self._prev_smooth = m.Smooth
        delta_signed = None
        delta_signed = r.read_zigzag()
        m.Signed = self._prev_signed + delta_signed
        self._prev_signed = m.Signed
        r.flush_to_byte_boundary()
        return m

    def reset(self):
        self._prev_offset = 0
        self._prev_smooth = 0
        self._prev_signed = 0


# ---------- Limited ----------
@dataclass
class Limited:
    body: str
    tags: list[str]
    headers: dict[str, str]
    data: bytes
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_string(self.body)
        w.write_leb128(len(self.tags))
        for item in {access}:
            w.write_string(item)
        w.write_leb128(len(self.headers))
        for map_k, map_v in self.headers.items():
            w.write_string(map_k)
            w.write_string(map_v)
        w.write_bytes(self.data)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        m = Limited.__new__(Limited)
        m.body = r.read_string()
        arr_len = r.read_leb128()
        m.tags: list[str] = []
        for _ in range(arr_len):
            _item: str = None  # type: ignore[assignment]
            _item = r.read_string()
            m.tags.append(_item)
        map_len = r.read_leb128()
        m.headers: dict[str, str] = {}
        for _ in range(map_len):
            _k: str = None  # type: ignore[assignment]
            _v: str = None  # type: ignore[assignment]
            _k = r.read_string()
            _v = r.read_string()
            m.headers[_k] = _v
        m.data = r.read_bytes()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- RenderCommand ----------
@dataclass
class RenderCommand:
    op: int
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_u8(self.op)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        m = RenderCommand.__new__(RenderCommand)
        m.op = r.read_u8()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- Documented ----------
@dataclass
class Documented:
    value: int
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_u32(self.value)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        m = Documented.__new__(Documented)
        m.value = r.read_u32()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m


