# Code generated by vexilc. DO NOT EDIT.
# Source: test.keywords_as_fields

from __future__ import annotations
from dataclasses import dataclass
from typing import Optional

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import _BitWriter, _BitReader

SCHEMA_HASH: tuple[int, ...] = (0x3c, 0xe1, 0x7c, 0x93, 0x58, 0x63, 0xae, 0xa0, 0x6f, 0x76, 0x53, 0xdc, 0xb8, 0x11, 0xe3, 0x87, 0x34, 0x2a, 0x85, 0x1c, 0x0a, 0xcd, 0xee, 0x7e, 0xa2, 0x86, 0x73, 0x7c, 0x3e, 0x03, 0xe7, 0x41)


# ---------- KeywordFields ----------
@dataclass
class KeywordFields:
    flags: int
    type: int
    hash: bytes
    string: int
    message: int
    enum: int
    union: int
    config: bool
    import: int
    namespace: str
    array: int
    map: int
    result: int
    optional: int
    from: int
    as: int
    void: int
    none: int
    true: int
    false: int
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_u8(self.flags)
        w.write_u16(self.type)
        w.write_bytes(self.hash)
        w.write_u32(self.string)
        w.write_u64(self.message)
        w.write_u8(self.enum)
        w.write_u8(self.union)
        w.write_bool(self.config)
        w.write_u32(self.import)
        w.write_string(self.namespace)
        w.write_u8(self.array)
        w.write_u8(self.map)
        w.write_u8(self.result)
        w.write_u8(self.optional)
        w.write_u8(self.from)
        w.write_u8(self.as)
        w.write_u8(self.void)
        w.write_u8(self.none)
        w.write_u8(self.true)
        w.write_u8(self.false)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        m = KeywordFields.__new__(KeywordFields)
        m.flags = r.read_u8()
        m.type = r.read_u16()
        m.hash = r.read_bytes()
        m.string = r.read_u32()
        m.message = r.read_u64()
        m.enum = r.read_u8()
        m.union = r.read_u8()
        m.config = r.read_bool()
        m.import = r.read_u32()
        m.namespace = r.read_string()
        m.array = r.read_u8()
        m.map = r.read_u8()
        m.result = r.read_u8()
        m.optional = r.read_u8()
        m.from = r.read_u8()
        m.as = r.read_u8()
        m.void = r.read_u8()
        m.none = r.read_u8()
        m.true = r.read_u8()
        m.false = r.read_u8()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m


