# Code generated by vexilc. DO NOT EDIT.
# Source: test.forward_refs

from __future__ import annotations
from dataclasses import dataclass

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import BitWriter as _BitWriter, BitReader as _BitReader

SCHEMA_HASH: tuple[int, ...] = (0xc8, 0x5a, 0xa7, 0x6a, 0x4f, 0xf4, 0x12, 0x1b, 0x4f, 0xbd, 0x1a, 0xb4, 0x28, 0xa8, 0x64, 0x39, 0xe7, 0x6e, 0x33, 0x0f, 0xb7, 0x41, 0x6f, 0xf2, 0x06, 0x66, 0x86, 0x33, 0x5a, 0x04, 0x05, 0xc7)


# ---------- Container ----------
@dataclass
class Container:
    item: Item
    meta: Metadata
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        self.item.encode_to(w)
        self.meta.encode_to(w)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> Container:
        r = _BitReader(data)
        return Container.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader) -> Container:
        m = Container.__new__(Container)
        m.item = Item.decode_from(r)
        m.meta = Metadata.decode_from(r)
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- Item ----------
@dataclass
class Item:
    name: str
    value: int
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_string(self.name)
        w.write_u64(self.value)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> Item:
        r = _BitReader(data)
        return Item.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader) -> Item:
        m = Item.__new__(Item)
        m.name = r.read_string()
        m.value = r.read_u64()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- Metadata ----------
@dataclass
class Metadata:
    created: int
    author: str
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_i64(self.created)
        w.write_string(self.author)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> Metadata:
        r = _BitReader(data)
        return Metadata.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader) -> Metadata:
        m = Metadata.__new__(Metadata)
        m.created = r.read_i64()
        m.author = r.read_string()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m


