# Code generated by vexilc. DO NOT EDIT.
# Source: test.recursive

from __future__ import annotations
from dataclasses import dataclass

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import BitWriter as _BitWriter, BitReader as _BitReader, DecodeError

SCHEMA_HASH: tuple[int, ...] = (0xa1, 0x25, 0xcb, 0x50, 0x29, 0x3e, 0xa3, 0x25, 0x60, 0x73, 0x08, 0x42, 0x52, 0xc5, 0xca, 0xf0, 0x83, 0xf5, 0xdd, 0xf7, 0x30, 0x18, 0xf8, 0x51, 0x8e, 0x54, 0xa9, 0xfd, 0xbe, 0xeb, 0x91, 0xae)


# ---------- TreeNode ----------
@dataclass
class TreeNode:
    value: int
    children: list[TreeNode]
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_i32(self.value)
        w.write_leb128(len(self.children))
        for item in self.children:
            item.encode_to(w)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> TreeNode:
        r = _BitReader(data)
        return TreeNode.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader) -> TreeNode:
        m = TreeNode.__new__(TreeNode)
        m.value = r.read_i32()
        arr_len = r.read_leb128()
        m.children = []
        for _ in range(arr_len):
            _item: TreeNode = None  # type: ignore[assignment]
            _item = TreeNode.decode_from(r)
            m.children.append(_item)
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- LinkedList ----------
@dataclass
class LinkedList:
    value: str
    next: LinkedList | None
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_string(self.value)
        w.write_bool(self.next is not None)
        w.flush_to_byte_boundary()
        if self.next is not None:
            self.next.encode_to(w)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> LinkedList:
        r = _BitReader(data)
        return LinkedList.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader) -> LinkedList:
        m = LinkedList.__new__(LinkedList)
        m.value = r.read_string()
        try:
            present = r.read_bool()
        except DecodeError:
            m.next = None
        else:
            r.flush_to_byte_boundary()
            if present:
                m.next: LinkedList = None  # type: ignore[assignment]
                m.next = LinkedList.decode_from(r)
            else:
                m.next = None
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- Expr ----------
@dataclass
class Expr:
    kind: ExprKind
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        self.kind.encode_to(w)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> Expr:
        r = _BitReader(data)
        return Expr.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader) -> Expr:
        m = Expr.__new__(Expr)
        m.kind = decode_ExprKind_from(r)
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- ExprKind ----------
class ExprKind:

    def encode(self) -> bytes:
        _vexil_writer = _BitWriter()
        self.encode_to(_vexil_writer)
        return _vexil_writer.finish()

    def encode_to(self, _vexil_writer: _BitWriter) -> None:
        raise NotImplementedError

class ExprKindLiteral(ExprKind):
    def __init__(self, value: int):
        self.value = value

    def encode_to(self, _vexil_writer: _BitWriter) -> None:
        _vexil_writer.write_leb128(0)
        _vexil_payload_writer = _BitWriter()
        _vexil_payload_writer.write_i64(self.value)
        _vexil_payload_writer.flush_to_byte_boundary()
        _vexil_payload = _vexil_payload_writer.finish()
        _vexil_writer.write_leb128(len(_vexil_payload))
        _vexil_writer.write_raw_bytes(_vexil_payload, len(_vexil_payload))


class ExprKindBinary(ExprKind):
    def __init__(self, left: Expr, op: int, right: Expr):
        self.left = left
        self.op = op
        self.right = right

    def encode_to(self, _vexil_writer: _BitWriter) -> None:
        _vexil_writer.write_leb128(1)
        _vexil_payload_writer = _BitWriter()
        self.left.encode_to(_vexil_payload_writer)
        _vexil_payload_writer.write_u8(self.op)
        self.right.encode_to(_vexil_payload_writer)
        _vexil_payload_writer.flush_to_byte_boundary()
        _vexil_payload = _vexil_payload_writer.finish()
        _vexil_writer.write_leb128(len(_vexil_payload))
        _vexil_writer.write_raw_bytes(_vexil_payload, len(_vexil_payload))


def decode_ExprKind_from(_vexil_reader: _BitReader) -> ExprKind:
    _vexil_reader.flush_to_byte_boundary()
    _vexil_discriminant = _vexil_reader.read_leb128()
    _vexil_length = _vexil_reader.read_leb128()
    if _vexil_discriminant == 0:
        _vexil_payload = _vexil_reader.read_bytes(_vexil_length)
        _vexil_payload_reader = _BitReader(_vexil_payload)
        _vexil_field_0: int = None  # type: ignore[assignment]
        _vexil_field_0 = _vexil_payload_reader.read_i64()
        return ExprKindLiteral(_vexil_field_0)
    elif _vexil_discriminant == 1:
        _vexil_payload = _vexil_reader.read_bytes(_vexil_length)
        _vexil_payload_reader = _BitReader(_vexil_payload)
        _vexil_field_0: Expr = None  # type: ignore[assignment]
        _vexil_field_0 = Expr.decode_from(_vexil_payload_reader)
        _vexil_field_1: int = None  # type: ignore[assignment]
        _vexil_field_1 = _vexil_payload_reader.read_u8()
        _vexil_field_2: Expr = None  # type: ignore[assignment]
        _vexil_field_2 = Expr.decode_from(_vexil_payload_reader)
        return ExprKindBinary(_vexil_field_0, _vexil_field_1, _vexil_field_2)
    else:
        raise ValueError(f"unknown ExprKind discriminant: {_vexil_discriminant}")

def decode_ExprKind(data: bytes) -> ExprKind:
    _vexil_reader = _BitReader(data)
    return decode_ExprKind_from(_vexil_reader)

