# Code generated by vexilc. DO NOT EDIT.
# Source: test.comments

from __future__ import annotations
from dataclasses import dataclass
from typing import Optional

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import _BitWriter, _BitReader

SCHEMA_HASH: tuple[int, ...] = (0xe6, 0x4c, 0x04, 0xab, 0xea, 0xe9, 0xc8, 0x5a, 0xc2, 0x27, 0x20, 0xe6, 0xf8, 0x3b, 0x27, 0x24, 0x6f, 0xcb, 0x78, 0xc3, 0x4d, 0x7c, 0xf8, 0x64, 0x2c, 0x82, 0x94, 0x0f, 0x5f, 0x52, 0x87, 0x11)


# ---------- Foo ----------
@dataclass
class Foo:
    x: int
    y: str
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_u32(self.x)
        w.write_string(self.y)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        m = Foo.__new__(Foo)
        m.x = r.read_u32()
        m.y = r.read_string()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- Bar ----------
class Bar(int):
    A = 0
    B = 1

    def encode(self) -> bytes:
        return _BitWriter().write_bits(int(self), 1).finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        v = r.read_bits(1)
        return Bar(v)

    def __repr__(self) -> str:
        return f"Bar({int(self)})"

