# Code generated by vexilc. DO NOT EDIT.
# Source: test.evolution.variant

from __future__ import annotations
from dataclasses import dataclass
from typing import Optional

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import _BitWriter, _BitReader

SCHEMA_HASH: tuple[int, ...] = (0xb1, 0x0f, 0x2e, 0x28, 0x31, 0xe3, 0xae, 0x61, 0xa2, 0x0f, 0x7c, 0xcb, 0x87, 0x0e, 0xeb, 0x2c, 0x7a, 0x7d, 0x09, 0x08, 0x40, 0xf9, 0x13, 0xb0, 0x96, 0xe9, 0x8d, 0x3c, 0x2e, 0x8a, 0xf8, 0x74)
SCHEMA_VERSION: str = "1.0.0"


# ---------- ShapeV1 ----------
class ShapeV1:

    def encode(self) -> bytes:
        return self._encode_variant()

    def _encode_variant(self) -> bytes:
        raise NotImplementedError

class ShapeV1Circle(ShapeV1):
    def __init__(self, radius: float):
        self.radius = radius

    def _encode_variant(self) -> bytes:
        w = _BitWriter()
        w.write_leb128(0)
        pw = _BitWriter()
        pw.write_f32(self.radius)
        pw.flush_to_byte_boundary()
        payload = pw.finish()
        w.write_leb128(len(payload))
        w.write_raw_bytes(payload)
        return w.finish()


class ShapeV1Rect(ShapeV1):
    def __init__(self, w: float, h: float):
        self.w = w
        self.h = h

    def _encode_variant(self) -> bytes:
        w = _BitWriter()
        w.write_leb128(1)
        pw = _BitWriter()
        pw.write_f32(self.w)
        pw.write_f32(self.h)
        pw.flush_to_byte_boundary()
        payload = pw.finish()
        w.write_leb128(len(payload))
        w.write_raw_bytes(payload)
        return w.finish()


def decode_ShapeV1(data: bytes) -> ShapeV1:
    r = _BitReader(data)
    r.flush_to_byte_boundary()
    disc = r.read_leb128()
    length = r.read_leb128()
    if disc == 0:
        _payload = r.read_raw_bytes(length)
        pr = _BitReader(_payload)
        radius: float = None  # type: ignore[assignment]
        radius = pr.read_f32()
        return ShapeV1Circle(radius)
    elif disc == 1:
        _payload = r.read_raw_bytes(length)
        pr = _BitReader(_payload)
        w: float = None  # type: ignore[assignment]
        w = pr.read_f32()
        h: float = None  # type: ignore[assignment]
        h = pr.read_f32()
        return ShapeV1Rect(w, h)
    else:
        raise ValueError(f"unknown ShapeV1 discriminant: {disc}")


# ---------- ShapeV2 ----------
class ShapeV2:

    def encode(self) -> bytes:
        return self._encode_variant()

    def _encode_variant(self) -> bytes:
        raise NotImplementedError

class ShapeV2Circle(ShapeV2):
    def __init__(self, radius: float):
        self.radius = radius

    def _encode_variant(self) -> bytes:
        w = _BitWriter()
        w.write_leb128(0)
        pw = _BitWriter()
        pw.write_f32(self.radius)
        pw.flush_to_byte_boundary()
        payload = pw.finish()
        w.write_leb128(len(payload))
        w.write_raw_bytes(payload)
        return w.finish()


class ShapeV2Rect(ShapeV2):
    def __init__(self, w: float, h: float):
        self.w = w
        self.h = h

    def _encode_variant(self) -> bytes:
        w = _BitWriter()
        w.write_leb128(1)
        pw = _BitWriter()
        pw.write_f32(self.w)
        pw.write_f32(self.h)
        pw.flush_to_byte_boundary()
        payload = pw.finish()
        w.write_leb128(len(payload))
        w.write_raw_bytes(payload)
        return w.finish()


class ShapeV2Triangle(ShapeV2):
    def __init__(self, base: float, height: float):
        self.base = base
        self.height = height

    def _encode_variant(self) -> bytes:
        w = _BitWriter()
        w.write_leb128(2)
        pw = _BitWriter()
        pw.write_f32(self.base)
        pw.write_f32(self.height)
        pw.flush_to_byte_boundary()
        payload = pw.finish()
        w.write_leb128(len(payload))
        w.write_raw_bytes(payload)
        return w.finish()


def decode_ShapeV2(data: bytes) -> ShapeV2:
    r = _BitReader(data)
    r.flush_to_byte_boundary()
    disc = r.read_leb128()
    length = r.read_leb128()
    if disc == 0:
        _payload = r.read_raw_bytes(length)
        pr = _BitReader(_payload)
        radius: float = None  # type: ignore[assignment]
        radius = pr.read_f32()
        return ShapeV2Circle(radius)
    elif disc == 1:
        _payload = r.read_raw_bytes(length)
        pr = _BitReader(_payload)
        w: float = None  # type: ignore[assignment]
        w = pr.read_f32()
        h: float = None  # type: ignore[assignment]
        h = pr.read_f32()
        return ShapeV2Rect(w, h)
    elif disc == 2:
        _payload = r.read_raw_bytes(length)
        pr = _BitReader(_payload)
        base: float = None  # type: ignore[assignment]
        base = pr.read_f32()
        height: float = None  # type: ignore[assignment]
        height = pr.read_f32()
        return ShapeV2Triangle(base, height)
    else:
        raise ValueError(f"unknown ShapeV2 discriminant: {disc}")

