# Code generated by vexilc. DO NOT EDIT.
# Source: test.evolution.variant

from __future__ import annotations

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import BitWriter as _BitWriter, BitReader as _BitReader

SCHEMA_HASH: tuple[int, ...] = (0xb1, 0x0f, 0x2e, 0x28, 0x31, 0xe3, 0xae, 0x61, 0xa2, 0x0f, 0x7c, 0xcb, 0x87, 0x0e, 0xeb, 0x2c, 0x7a, 0x7d, 0x09, 0x08, 0x40, 0xf9, 0x13, 0xb0, 0x96, 0xe9, 0x8d, 0x3c, 0x2e, 0x8a, 0xf8, 0x74)
SCHEMA_VERSION: str = "1.0.0"


# ---------- ShapeV1 ----------
class ShapeV1:

    def encode(self) -> bytes:
        _vexil_writer = _BitWriter()
        self.encode_to(_vexil_writer)
        return _vexil_writer.finish()

    def encode_to(self, _vexil_writer: _BitWriter) -> None:
        raise NotImplementedError

class ShapeV1Circle(ShapeV1):
    def __init__(self, radius: float):
        self.radius = radius

    def encode_to(self, _vexil_writer: _BitWriter) -> None:
        _vexil_writer.write_leb128(0)
        _vexil_payload_writer = _BitWriter()
        _vexil_payload_writer.write_f32(self.radius)
        _vexil_payload_writer.flush_to_byte_boundary()
        _vexil_payload = _vexil_payload_writer.finish()
        _vexil_writer.write_leb128(len(_vexil_payload))
        _vexil_writer.write_raw_bytes(_vexil_payload, len(_vexil_payload))


class ShapeV1Rect(ShapeV1):
    def __init__(self, w: float, h: float):
        self.w = w
        self.h = h

    def encode_to(self, _vexil_writer: _BitWriter) -> None:
        _vexil_writer.write_leb128(1)
        _vexil_payload_writer = _BitWriter()
        _vexil_payload_writer.write_f32(self.w)
        _vexil_payload_writer.write_f32(self.h)
        _vexil_payload_writer.flush_to_byte_boundary()
        _vexil_payload = _vexil_payload_writer.finish()
        _vexil_writer.write_leb128(len(_vexil_payload))
        _vexil_writer.write_raw_bytes(_vexil_payload, len(_vexil_payload))


def decode_ShapeV1_from(_vexil_reader: _BitReader) -> ShapeV1:
    _vexil_reader.flush_to_byte_boundary()
    _vexil_discriminant = _vexil_reader.read_leb128()
    _vexil_length = _vexil_reader.read_leb128()
    if _vexil_discriminant == 0:
        _vexil_payload = _vexil_reader.read_bytes(_vexil_length)
        _vexil_payload_reader = _BitReader(_vexil_payload)
        _vexil_field_0 = _vexil_payload_reader.read_f32()
        return ShapeV1Circle(_vexil_field_0)
    elif _vexil_discriminant == 1:
        _vexil_payload = _vexil_reader.read_bytes(_vexil_length)
        _vexil_payload_reader = _BitReader(_vexil_payload)
        _vexil_field_0 = _vexil_payload_reader.read_f32()
        _vexil_field_1 = _vexil_payload_reader.read_f32()
        return ShapeV1Rect(_vexil_field_0, _vexil_field_1)
    else:
        raise ValueError(f"unknown ShapeV1 discriminant: {_vexil_discriminant}")

def decode_ShapeV1(data: bytes) -> ShapeV1:
    _vexil_reader = _BitReader(data)
    return decode_ShapeV1_from(_vexil_reader)


# ---------- ShapeV2 ----------
class ShapeV2:

    def encode(self) -> bytes:
        _vexil_writer = _BitWriter()
        self.encode_to(_vexil_writer)
        return _vexil_writer.finish()

    def encode_to(self, _vexil_writer: _BitWriter) -> None:
        raise NotImplementedError

class ShapeV2Circle(ShapeV2):
    def __init__(self, radius: float):
        self.radius = radius

    def encode_to(self, _vexil_writer: _BitWriter) -> None:
        _vexil_writer.write_leb128(0)
        _vexil_payload_writer = _BitWriter()
        _vexil_payload_writer.write_f32(self.radius)
        _vexil_payload_writer.flush_to_byte_boundary()
        _vexil_payload = _vexil_payload_writer.finish()
        _vexil_writer.write_leb128(len(_vexil_payload))
        _vexil_writer.write_raw_bytes(_vexil_payload, len(_vexil_payload))


class ShapeV2Rect(ShapeV2):
    def __init__(self, w: float, h: float):
        self.w = w
        self.h = h

    def encode_to(self, _vexil_writer: _BitWriter) -> None:
        _vexil_writer.write_leb128(1)
        _vexil_payload_writer = _BitWriter()
        _vexil_payload_writer.write_f32(self.w)
        _vexil_payload_writer.write_f32(self.h)
        _vexil_payload_writer.flush_to_byte_boundary()
        _vexil_payload = _vexil_payload_writer.finish()
        _vexil_writer.write_leb128(len(_vexil_payload))
        _vexil_writer.write_raw_bytes(_vexil_payload, len(_vexil_payload))


class ShapeV2Triangle(ShapeV2):
    def __init__(self, base: float, height: float):
        self.base = base
        self.height = height

    def encode_to(self, _vexil_writer: _BitWriter) -> None:
        _vexil_writer.write_leb128(2)
        _vexil_payload_writer = _BitWriter()
        _vexil_payload_writer.write_f32(self.base)
        _vexil_payload_writer.write_f32(self.height)
        _vexil_payload_writer.flush_to_byte_boundary()
        _vexil_payload = _vexil_payload_writer.finish()
        _vexil_writer.write_leb128(len(_vexil_payload))
        _vexil_writer.write_raw_bytes(_vexil_payload, len(_vexil_payload))


def decode_ShapeV2_from(_vexil_reader: _BitReader) -> ShapeV2:
    _vexil_reader.flush_to_byte_boundary()
    _vexil_discriminant = _vexil_reader.read_leb128()
    _vexil_length = _vexil_reader.read_leb128()
    if _vexil_discriminant == 0:
        _vexil_payload = _vexil_reader.read_bytes(_vexil_length)
        _vexil_payload_reader = _BitReader(_vexil_payload)
        _vexil_field_0 = _vexil_payload_reader.read_f32()
        return ShapeV2Circle(_vexil_field_0)
    elif _vexil_discriminant == 1:
        _vexil_payload = _vexil_reader.read_bytes(_vexil_length)
        _vexil_payload_reader = _BitReader(_vexil_payload)
        _vexil_field_0 = _vexil_payload_reader.read_f32()
        _vexil_field_1 = _vexil_payload_reader.read_f32()
        return ShapeV2Rect(_vexil_field_0, _vexil_field_1)
    elif _vexil_discriminant == 2:
        _vexil_payload = _vexil_reader.read_bytes(_vexil_length)
        _vexil_payload_reader = _BitReader(_vexil_payload)
        _vexil_field_0 = _vexil_payload_reader.read_f32()
        _vexil_field_1 = _vexil_payload_reader.read_f32()
        return ShapeV2Triangle(_vexil_field_0, _vexil_field_1)
    else:
        raise ValueError(f"unknown ShapeV2 discriminant: {_vexil_discriminant}")

def decode_ShapeV2(data: bytes) -> ShapeV2:
    _vexil_reader = _BitReader(data)
    return decode_ShapeV2_from(_vexil_reader)
