# Code generated by vexilc. DO NOT EDIT.
# Source: test.recursive.depth

from __future__ import annotations
from dataclasses import dataclass

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import BitWriter as _BitWriter, BitReader as _BitReader, DecodeError

SCHEMA_HASH: tuple[int, ...] = (0x4f, 0x25, 0x39, 0x5a, 0x3e, 0x94, 0xda, 0xf1, 0x8a, 0xee, 0xff, 0x59, 0x90, 0x93, 0x11, 0xaa, 0x20, 0x39, 0xa6, 0x36, 0x6b, 0xe5, 0x3c, 0xb0, 0x16, 0x54, 0x23, 0x6c, 0x09, 0x44, 0x4d, 0x73)


# ---------- TreeNode ----------
@dataclass
class TreeNode:
    value: int
    children: list[TreeNode]
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        try:
            w.enter_nested()
            self.encode_to(w)
        finally:
            w.leave_nested()
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_u32(self.value)
        w.write_leb128(len(self.children))
        for _vexil_self_2e_children_array_item in self.children:
            try:
                w.enter_nested()
                _vexil_self_2e_children_array_item.encode_to(w)
            finally:
                w.leave_nested()
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> TreeNode:
        r = _BitReader(data)
        try:
            r.enter_nested()
            return TreeNode.decode_from(r)
        finally:
            r.leave_nested()

    @staticmethod
    def decode_from(r: _BitReader) -> TreeNode:
        m = TreeNode.__new__(TreeNode)
        m.value = r.read_u32()
        _vexil_m_2e_children_array_length = r.read_leb128()
        _vexil_m_2e_children_array_items: list[TreeNode] = []
        for _ in range(_vexil_m_2e_children_array_length):
            try:
                r.enter_nested()
                _vexil_m_2e_children_array_item = TreeNode.decode_from(r)
            finally:
                r.leave_nested()
            _vexil_m_2e_children_array_items.append(_vexil_m_2e_children_array_item)
        m.children = _vexil_m_2e_children_array_items
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- LinkedList ----------
@dataclass
class LinkedList:
    value: int
    next: LinkedList | None
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        try:
            w.enter_nested()
            self.encode_to(w)
        finally:
            w.leave_nested()
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_i64(self.value)
        _vexil_self_2e_next_optional = self.next
        w.write_bool(_vexil_self_2e_next_optional is not None)
        if _vexil_self_2e_next_optional is not None:
            try:
                w.enter_nested()
                _vexil_self_2e_next_optional.encode_to(w)
            finally:
                w.leave_nested()
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> LinkedList:
        r = _BitReader(data)
        try:
            r.enter_nested()
            return LinkedList.decode_from(r)
        finally:
            r.leave_nested()

    @staticmethod
    def decode_from(r: _BitReader) -> LinkedList:
        m = LinkedList.__new__(LinkedList)
        m.value = r.read_i64()
        try:
            _vexil_m_2e_next_present = r.read_bool()
        except DecodeError:
            m.next = None
        else:
            if _vexil_m_2e_next_present:
                try:
                    r.enter_nested()
                    m.next = LinkedList.decode_from(r)
                finally:
                    r.leave_nested()
            else:
                m.next = None
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m
