# Code generated by vexilc. DO NOT EDIT.
# Source: test.zero.payload

from __future__ import annotations
from dataclasses import dataclass

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import _BitWriter, _BitReader

SCHEMA_HASH: tuple[int, ...] = (0xc4, 0x4e, 0x40, 0xb2, 0xf3, 0x59, 0x8c, 0xc5, 0xf4, 0x0d, 0xfe, 0xbc, 0x69, 0x4b, 0x7c, 0xcf, 0xee, 0x8b, 0x02, 0x52, 0xd5, 0x4f, 0xc1, 0x80, 0xb7, 0xa2, 0xd0, 0xc0, 0xca, 0x3c, 0xa0, 0x55)


# ---------- Empty ----------
@dataclass
class Empty:
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter):
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        return Empty.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader):
        m = Empty.__new__(Empty)
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- Wrapper ----------
@dataclass
class Wrapper:
    inner: Empty
    tag: int
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter):
        self.inner.encode_to(w)
        w.write_u8(self.tag)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        return Wrapper.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader):
        m = Wrapper.__new__(Wrapper)
        m.inner = Empty.decode_from(r)
        m.tag = r.read_u8()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- Event ----------
class Event:

    def encode(self) -> bytes:
        return self._encode_variant()

    def _encode_variant(self) -> bytes:
        raise NotImplementedError

class EventPing(Event):
    def __init__(self):
        pass

    def _encode_variant(self) -> bytes:
        _vexil_writer = _BitWriter()
        _vexil_writer.write_leb128(0)
        _vexil_writer.write_leb128(0)
        return _vexil_writer.finish()


class EventPong(Event):
    def __init__(self):
        pass

    def _encode_variant(self) -> bytes:
        _vexil_writer = _BitWriter()
        _vexil_writer.write_leb128(1)
        _vexil_writer.write_leb128(0)
        return _vexil_writer.finish()


class EventData(Event):
    def __init__(self, payload: bytes):
        self.payload = payload

    def _encode_variant(self) -> bytes:
        _vexil_writer = _BitWriter()
        _vexil_writer.write_leb128(2)
        _vexil_payload_writer = _BitWriter()
        _vexil_payload_writer.write_bytes(self.payload)
        _vexil_payload_writer.flush_to_byte_boundary()
        _vexil_payload = _vexil_payload_writer.finish()
        _vexil_writer.write_leb128(len(_vexil_payload))
        _vexil_writer.write_raw_bytes(_vexil_payload, len(_vexil_payload))
        return _vexil_writer.finish()


def decode_Event_from(_vexil_reader: _BitReader) -> Event:
    _vexil_reader.flush_to_byte_boundary()
    _vexil_discriminant = _vexil_reader.read_leb128()
    _vexil_length = _vexil_reader.read_leb128()
    if _vexil_discriminant == 0:
        return EventPing()
    elif _vexil_discriminant == 1:
        return EventPong()
    elif _vexil_discriminant == 2:
        _vexil_payload = _vexil_reader.read_bytes(_vexil_length)
        _vexil_payload_reader = _BitReader(_vexil_payload)
        _vexil_field_0: bytes = None  # type: ignore[assignment]
        _vexil_field_0 = _vexil_payload_reader.read_bytes(_vexil_payload_reader.read_leb128())
        return EventData(_vexil_field_0)
    else:
        raise ValueError(f"unknown Event discriminant: {_vexil_discriminant}")

def decode_Event(data: bytes) -> Event:
    _vexil_reader = _BitReader(data)
    return decode_Event_from(_vexil_reader)

