# Code generated by vexilc. DO NOT EDIT.
# Source: test.evolution.reqopt

from __future__ import annotations
from dataclasses import dataclass

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import BitWriter as _BitWriter, BitReader as _BitReader

SCHEMA_HASH: tuple[int, ...] = (0x26, 0x17, 0x33, 0xb3, 0x2d, 0x8b, 0x2f, 0xf3, 0x27, 0x2f, 0xf2, 0x60, 0xc8, 0xb1, 0xb2, 0x99, 0xa6, 0xea, 0x63, 0xeb, 0xcf, 0xd8, 0xee, 0x99, 0x90, 0xe8, 0x3c, 0xb6, 0x88, 0x83, 0x6b, 0xd3)


# ---------- SettingsV1 ----------
@dataclass
class SettingsV1:
    timeout: int
    name: str
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        try:
            w.enter_nested()
            self.encode_to(w)
        finally:
            w.leave_nested()
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_u32(self.timeout)
        w.write_string(self.name)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> SettingsV1:
        r = _BitReader(data)
        try:
            r.enter_nested()
            return SettingsV1.decode_from(r)
        finally:
            r.leave_nested()

    @staticmethod
    def decode_from(r: _BitReader) -> SettingsV1:
        m = SettingsV1.__new__(SettingsV1)
        m.timeout = r.read_u32()
        m.name = r.read_string()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- SettingsV2 ----------
@dataclass
class SettingsV2:
    timeout: int | None
    name: str
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        try:
            w.enter_nested()
            self.encode_to(w)
        finally:
            w.leave_nested()
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        _vexil_self_2e_timeout_optional = self.timeout
        w.write_bool(_vexil_self_2e_timeout_optional is not None)
        if _vexil_self_2e_timeout_optional is not None:
            w.flush_to_byte_boundary()
            w.write_u32(_vexil_self_2e_timeout_optional)
        w.write_string(self.name)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> SettingsV2:
        r = _BitReader(data)
        try:
            r.enter_nested()
            return SettingsV2.decode_from(r)
        finally:
            r.leave_nested()

    @staticmethod
    def decode_from(r: _BitReader) -> SettingsV2:
        m = SettingsV2.__new__(SettingsV2)
        _vexil_m_2e_timeout_present = r.read_bool()
        if _vexil_m_2e_timeout_present:
            r.flush_to_byte_boundary()
            m.timeout = r.read_u32()
        else:
            m.timeout = None
        m.name = r.read_string()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m

__all__ = ["dataclass", "SCHEMA_HASH", "SettingsV1", "SettingsV2"]
