# Code generated by vexilc. DO NOT EDIT.
# Source: test.delta.message

from __future__ import annotations
from dataclasses import dataclass
from typing import Optional

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import _BitWriter, _BitReader

SCHEMA_HASH: tuple[int, ...] = (0x07, 0x20, 0xc0, 0x79, 0x18, 0xe4, 0x24, 0xcf, 0xdb, 0xde, 0x48, 0xe0, 0xdb, 0x86, 0xb5, 0xb2, 0x2e, 0x55, 0x23, 0x7f, 0xf9, 0x9c, 0xe5, 0xd7, 0x95, 0x14, 0x35, 0x9e, 0x8f, 0xab, 0x99, 0x67)


# ---------- Telemetry ----------
@dataclass
class Telemetry:
    timestamp: int
    value: float
    label: str
    count: int
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_zigzag(self.timestamp)
        w.write_f32(self.value)
        w.write_string(self.label)
        w.write_leb128(self.count)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        m = Telemetry.__new__(Telemetry)
        m.timestamp = r.read_zigzag()
        m.value = r.read_f32()
        m.label = r.read_string()
        m.count = r.read_leb128()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m


class TelemetryEncoder:

    def __init__(self):
        self._prev_timestamp: int = 0
        self._prev_value: float = 0.0
        self._prev_count: int = 0

    def encode(self, val: Telemetry) -> bytes:
        w = _BitWriter()
        delta_timestamp = val.Timestamp - self._prev_timestamp
        w.write_zigzag(delta_timestamp)
        self._prev_timestamp = val.Timestamp
        delta_value = val.Value - self._prev_value
        w.write_f32(delta_value)
        self._prev_value = val.Value
        w.write_string(val.Label)
        delta_count = val.Count - self._prev_count
        w.write_leb128(delta_count)
        self._prev_count = val.Count
        w.flush_to_byte_boundary()
        return w.finish()

    def reset(self):
        self._prev_timestamp = 0
        self._prev_value = 0.0
        self._prev_count = 0

class TelemetryDecoder:

    def __init__(self):
        self._prev_timestamp: int = 0
        self._prev_value: float = 0.0
        self._prev_count: int = 0

    def decode(self, data: bytes) -> Telemetry:
        r = _BitReader(data)
        m = Telemetry.__new__(Telemetry)
        delta_timestamp = None
        delta_timestamp = r.read_zigzag()
        m.Timestamp = self._prev_timestamp + delta_timestamp
        self._prev_timestamp = m.Timestamp
        delta_value = None
        delta_value = r.read_f32()
        m.Value = self._prev_value + delta_value
        self._prev_value = m.Value
        m.Label = r.read_string()
        delta_count = None
        delta_count = r.read_leb128()
        m.Count = self._prev_count + delta_count
        self._prev_count = m.Count
        r.flush_to_byte_boundary()
        return m

    def reset(self):
        self._prev_timestamp = 0
        self._prev_value = 0.0
        self._prev_count = 0

