# Code generated by vexilc. DO NOT EDIT.
# Source: test.newtype_map_key

from __future__ import annotations
from dataclasses import dataclass
from typing import Optional

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import _BitWriter, _BitReader

SCHEMA_HASH: tuple[int, ...] = (0x18, 0xfd, 0xc9, 0xe0, 0x68, 0x83, 0x2d, 0x02, 0x03, 0x88, 0x9a, 0x40, 0x58, 0x69, 0xe8, 0xd5, 0xf3, 0xc4, 0x44, 0xec, 0x31, 0xe3, 0x08, 0x0b, 0x7b, 0x3b, 0x56, 0x02, 0x9d, 0xc1, 0x41, 0x81)
SCHEMA_VERSION: str = "1.0.0"


# ---------- UserId ----------
class UserId:

    def __init__(self, value):
        self.value: int = value

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_u32(self.value)
        return w.finish()

    @staticmethod
    def decode(data: bytes) -> UserId:
        r = _BitReader(data)
        inner: int = None  # type: ignore[assignment]
        inner = r.read_u32()
        return UserId(inner)

    def __repr__(self) -> str:
        return f"UserId({self.value!r})"

    def __eq__(self, other):
        return isinstance(other, UserId) and self.value == other.value


# ---------- Label ----------
class Label:

    def __init__(self, value):
        self.value: str = value

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_string(self.value)
        return w.finish()

    @staticmethod
    def decode(data: bytes) -> Label:
        r = _BitReader(data)
        inner: str = None  # type: ignore[assignment]
        inner = r.read_string()
        return Label(inner)

    def __repr__(self) -> str:
        return f"Label({self.value!r})"

    def __eq__(self, other):
        return isinstance(other, Label) and self.value == other.value


# ---------- UserProfile ----------
@dataclass
class UserProfile:
    id: UserId
    friends: dict[UserId, str]
    tags: dict[Label, int]
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        w.extend(self.id.encode())
        w.write_leb128(len(self.friends))
        for map_k, map_v in self.friends.items():
            w.extend(map_k.encode())
            w.write_string(map_v)
        w.write_leb128(len(self.tags))
        for map_k, map_v in self.tags.items():
            w.extend(map_k.encode())
            w.write_u32(map_v)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        m = UserProfile.__new__(UserProfile)
        _payload = r.read_bytes()
        m.id = UserId.decode(_payload)
        map_len = r.read_leb128()
        m.friends: dict[UserId, str] = {}
        for _ in range(map_len):
            _k: UserId = None  # type: ignore[assignment]
            _v: str = None  # type: ignore[assignment]
            _payload = r.read_bytes()
            _k = UserId.decode(_payload)
            _v = r.read_string()
            m.friends[_k] = _v
        map_len = r.read_leb128()
        m.tags: dict[Label, int] = {}
        for _ in range(map_len):
            _k: Label = None  # type: ignore[assignment]
            _v: int = None  # type: ignore[assignment]
            _payload = r.read_bytes()
            _k = Label.decode(_payload)
            _v = r.read_u32()
            m.tags[_k] = _v
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m


