# Code generated by vexilc. DO NOT EDIT.
# Source: test.newtype_map_key

from __future__ import annotations
from dataclasses import dataclass

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import BitWriter as _BitWriter, BitReader as _BitReader

SCHEMA_HASH: tuple[int, ...] = (0x18, 0xfd, 0xc9, 0xe0, 0x68, 0x83, 0x2d, 0x02, 0x03, 0x88, 0x9a, 0x40, 0x58, 0x69, 0xe8, 0xd5, 0xf3, 0xc4, 0x44, 0xec, 0x31, 0xe3, 0x08, 0x0b, 0x7b, 0x3b, 0x56, 0x02, 0x9d, 0xc1, 0x41, 0x81)
SCHEMA_VERSION: str = "1.0.0"


# ---------- UserId ----------
class UserId:

    def __init__(self, value: int) -> None:
        self.value: int = value

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_u32(self.value)

    @staticmethod
    def decode(data: bytes) -> UserId:
        r = _BitReader(data)
        return UserId.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader) -> UserId:
        inner = r.read_u32()
        return UserId(inner)

    def __repr__(self) -> str:
        return f"UserId({self.value!r})"

    def __eq__(self, other: object) -> bool:
        return isinstance(other, UserId) and self.value == other.value


# ---------- Label ----------
class Label:

    def __init__(self, value: str) -> None:
        self.value: str = value

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_string(self.value)

    @staticmethod
    def decode(data: bytes) -> Label:
        r = _BitReader(data)
        return Label.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader) -> Label:
        inner = r.read_string()
        return Label(inner)

    def __repr__(self) -> str:
        return f"Label({self.value!r})"

    def __eq__(self, other: object) -> bool:
        return isinstance(other, Label) and self.value == other.value


# ---------- UserProfile ----------
@dataclass
class UserProfile:
    id: UserId
    friends: dict[UserId, str]
    tags: dict[Label, int]
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        try:
            w.enter_nested()
            self.encode_to(w)
        finally:
            w.leave_nested()
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        try:
            w.enter_nested()
            self.id.encode_to(w)
        finally:
            w.leave_nested()
        w.write_leb128(len(self.friends))
        for _vexil_self_2e_friends_map_key, _vexil_self_2e_friends_map_value in self.friends.items():
            try:
                w.enter_nested()
                _vexil_self_2e_friends_map_key.encode_to(w)
            finally:
                w.leave_nested()
            w.write_string(_vexil_self_2e_friends_map_value)
        w.write_leb128(len(self.tags))
        for _vexil_self_2e_tags_map_key, _vexil_self_2e_tags_map_value in self.tags.items():
            try:
                w.enter_nested()
                _vexil_self_2e_tags_map_key.encode_to(w)
            finally:
                w.leave_nested()
            w.write_u32(_vexil_self_2e_tags_map_value)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> UserProfile:
        r = _BitReader(data)
        try:
            r.enter_nested()
            return UserProfile.decode_from(r)
        finally:
            r.leave_nested()

    @staticmethod
    def decode_from(r: _BitReader) -> UserProfile:
        m = UserProfile.__new__(UserProfile)
        try:
            r.enter_nested()
            m.id = UserId.decode_from(r)
        finally:
            r.leave_nested()
        _vexil_m_2e_friends_map_length = r.read_leb128()
        _vexil_m_2e_friends_map_items: dict[UserId, str] = {}
        for _ in range(_vexil_m_2e_friends_map_length):
            try:
                r.enter_nested()
                _vexil_m_2e_friends_map_key = UserId.decode_from(r)
            finally:
                r.leave_nested()
            _vexil_m_2e_friends_map_value = r.read_string()
            _vexil_m_2e_friends_map_items[_vexil_m_2e_friends_map_key] = _vexil_m_2e_friends_map_value
        m.friends = _vexil_m_2e_friends_map_items
        _vexil_m_2e_tags_map_length = r.read_leb128()
        _vexil_m_2e_tags_map_items: dict[Label, int] = {}
        for _ in range(_vexil_m_2e_tags_map_length):
            try:
                r.enter_nested()
                _vexil_m_2e_tags_map_key = Label.decode_from(r)
            finally:
                r.leave_nested()
            _vexil_m_2e_tags_map_value = r.read_u32()
            _vexil_m_2e_tags_map_items[_vexil_m_2e_tags_map_key] = _vexil_m_2e_tags_map_value
        m.tags = _vexil_m_2e_tags_map_items
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m
