# Code generated by vexilc. DO NOT EDIT.
# Source: test.custom_annotations

from __future__ import annotations
from dataclasses import dataclass
from typing import Optional

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import _BitWriter, _BitReader

SCHEMA_HASH: tuple[int, ...] = (0xb5, 0xa1, 0x57, 0x1c, 0xa4, 0x06, 0xbb, 0xc7, 0xaf, 0x52, 0x7f, 0x9d, 0xcd, 0x09, 0x62, 0x1e, 0x61, 0xbc, 0xa3, 0x89, 0x2e, 0xa7, 0xf3, 0x64, 0xba, 0x3c, 0x9b, 0x2f, 0x2e, 0xeb, 0x7f, 0xd7)
SCHEMA_VERSION: str = "1.0.0"


# ---------- Alert ----------
@dataclass
class Alert:
    code: int
    message: str
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_u32(self.code)
        w.write_string(self.message)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        m = Alert.__new__(Alert)
        m.code = r.read_u32()
        m.message = r.read_string()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- Heartbeat ----------
@dataclass
class Heartbeat:
    seq: int
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_u64(self.seq)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        m = Heartbeat.__new__(Heartbeat)
        m.seq = r.read_u64()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m


