# Code generated by vexilc. DO NOT EDIT.
# Source: test.fixed_array

from __future__ import annotations
from dataclasses import dataclass

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import _BitWriter, _BitReader, DecodeError

SCHEMA_HASH: tuple[int, ...] = (0x06, 0xd9, 0x95, 0xe1, 0xc7, 0x2a, 0xef, 0xec, 0x68, 0x94, 0xe9, 0x71, 0x21, 0x92, 0x96, 0x74, 0xb6, 0xaa, 0xb0, 0x66, 0x4b, 0x64, 0x27, 0x91, 0x85, 0x34, 0x22, 0x3e, 0xdc, 0xeb, 0x60, 0x31)


# ---------- Basic ----------
@dataclass
class Basic:
    a: tuple[int, ...]
    b: tuple[int, ...]
    c: tuple[float, ...]
    d: tuple[str, ...]
    e: tuple[Point, ...]
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter):
        for item in self.a:
            w.write_u8(item)
        for item in self.b:
            w.write_u32(item)
        for item in self.c:
            w.write_f64(item)
        for item in self.d:
            w.write_string(item)
        for item in self.e:
            item.encode_to(w)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        return Basic.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader):
        m = Basic.__new__(Basic)
        _vexil_m_a_fixed_items: list[int] = []
        for _ in range(4):
            _vexil_m_a_fixed_item = r.read_u8()
            _vexil_m_a_fixed_items.append(_vexil_m_a_fixed_item)
        m.a = tuple(_vexil_m_a_fixed_items)
        _vexil_m_b_fixed_items: list[int] = []
        for _ in range(8):
            _vexil_m_b_fixed_item = r.read_u32()
            _vexil_m_b_fixed_items.append(_vexil_m_b_fixed_item)
        m.b = tuple(_vexil_m_b_fixed_items)
        _vexil_m_c_fixed_items: list[float] = []
        for _ in range(16):
            _vexil_m_c_fixed_item = r.read_f64()
            _vexil_m_c_fixed_items.append(_vexil_m_c_fixed_item)
        m.c = tuple(_vexil_m_c_fixed_items)
        _vexil_m_d_fixed_items: list[str] = []
        for _ in range(3):
            _vexil_m_d_fixed_item = r.read_string()
            _vexil_m_d_fixed_items.append(_vexil_m_d_fixed_item)
        m.d = tuple(_vexil_m_d_fixed_items)
        _vexil_m_e_fixed_items: list[Point] = []
        for _ in range(5):
            _vexil_m_e_fixed_item = Point.decode_from(r)
            _vexil_m_e_fixed_items.append(_vexil_m_e_fixed_item)
        m.e = tuple(_vexil_m_e_fixed_items)
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- Point ----------
@dataclass
class Point:
    x: float
    y: float
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter):
        w.write_f32(self.x)
        w.write_f32(self.y)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        return Point.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader):
        m = Point.__new__(Point)
        m.x = r.read_f32()
        m.y = r.read_f32()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- Nested ----------
@dataclass
class Nested:
    a: tuple[tuple[int, ...], ...]
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter):
        for item in self.a:
            for item in item:
                w.write_u8(item)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        return Nested.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader):
        m = Nested.__new__(Nested)
        _vexil_m_a_fixed_items: list[tuple[int, ...]] = []
        for _ in range(3):
            _vexil__vexil_m_a_fixed_item_fixed_items: list[int] = []
            for _ in range(4):
                _vexil__vexil_m_a_fixed_item_fixed_item = r.read_u8()
                _vexil__vexil_m_a_fixed_item_fixed_items.append(_vexil__vexil_m_a_fixed_item_fixed_item)
            _vexil_m_a_fixed_item = tuple(_vexil__vexil_m_a_fixed_item_fixed_items)
            _vexil_m_a_fixed_items.append(_vexil_m_a_fixed_item)
        m.a = tuple(_vexil_m_a_fixed_items)
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- WithOptional ----------
@dataclass
class WithOptional:
    a: tuple[int | None, ...]
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter):
        for item in self.a:
            w.write_bool(item is not None)
            w.flush_to_byte_boundary()
            if item is not None:
                w.write_u32(item)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        return WithOptional.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader):
        m = WithOptional.__new__(WithOptional)
        _vexil_m_a_fixed_items: list[int | None] = []
        for _ in range(10):
            try:
                present = r.read_bool()
            except DecodeError:
                _vexil_m_a_fixed_item = None
            else:
                r.flush_to_byte_boundary()
                if present:
                    _vexil_m_a_fixed_item: int = None  # type: ignore[assignment]
                    _vexil_m_a_fixed_item = r.read_u32()
                else:
                    _vexil_m_a_fixed_item = None
            _vexil_m_a_fixed_items.append(_vexil_m_a_fixed_item)
        m.a = tuple(_vexil_m_a_fixed_items)
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- WithUnion ----------
@dataclass
class WithUnion:
    data: Data
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter):
        _encoded_union = self.data.encode()
        w.write_raw_bytes(_encoded_union, len(_encoded_union))
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        return WithUnion.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader):
        m = WithUnion.__new__(WithUnion)
        m.data = decode_Data_from(r)
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- Data ----------
class Data:

    def encode(self) -> bytes:
        return self._encode_variant()

    def _encode_variant(self) -> bytes:
        raise NotImplementedError

class DataFixedInts(Data):
    def __init__(self, values: tuple[int, ...]):
        self.values = values

    def _encode_variant(self) -> bytes:
        _vexil_writer = _BitWriter()
        _vexil_writer.write_leb128(0)
        _vexil_payload_writer = _BitWriter()
        for item in self.values:
            _vexil_payload_writer.write_i32(item)
        _vexil_payload_writer.flush_to_byte_boundary()
        _vexil_payload = _vexil_payload_writer.finish()
        _vexil_writer.write_leb128(len(_vexil_payload))
        _vexil_writer.write_raw_bytes(_vexil_payload, len(_vexil_payload))
        return _vexil_writer.finish()


class DataFixedBytes(Data):
    def __init__(self, bytes: tuple[int, ...]):
        self.bytes = bytes

    def _encode_variant(self) -> bytes:
        _vexil_writer = _BitWriter()
        _vexil_writer.write_leb128(1)
        _vexil_payload_writer = _BitWriter()
        for item in self.bytes:
            _vexil_payload_writer.write_u8(item)
        _vexil_payload_writer.flush_to_byte_boundary()
        _vexil_payload = _vexil_payload_writer.finish()
        _vexil_writer.write_leb128(len(_vexil_payload))
        _vexil_writer.write_raw_bytes(_vexil_payload, len(_vexil_payload))
        return _vexil_writer.finish()


def decode_Data_from(_vexil_reader: _BitReader) -> Data:
    _vexil_reader.flush_to_byte_boundary()
    _vexil_discriminant = _vexil_reader.read_leb128()
    _vexil_length = _vexil_reader.read_leb128()
    if _vexil_discriminant == 0:
        _vexil_payload = _vexil_reader.read_bytes(_vexil_length)
        _vexil_payload_reader = _BitReader(_vexil_payload)
        _vexil_field_0: tuple[int, ...] = None  # type: ignore[assignment]
        _vexil__vexil_field_0_fixed_items: list[int] = []
        for _ in range(4):
            _vexil__vexil_field_0_fixed_item = _vexil_payload_reader.read_i32()
            _vexil__vexil_field_0_fixed_items.append(_vexil__vexil_field_0_fixed_item)
        _vexil_field_0 = tuple(_vexil__vexil_field_0_fixed_items)
        return DataFixedInts(_vexil_field_0)
    elif _vexil_discriminant == 1:
        _vexil_payload = _vexil_reader.read_bytes(_vexil_length)
        _vexil_payload_reader = _BitReader(_vexil_payload)
        _vexil_field_0: tuple[int, ...] = None  # type: ignore[assignment]
        _vexil__vexil_field_0_fixed_items: list[int] = []
        for _ in range(32):
            _vexil__vexil_field_0_fixed_item = _vexil_payload_reader.read_u8()
            _vexil__vexil_field_0_fixed_items.append(_vexil__vexil_field_0_fixed_item)
        _vexil_field_0 = tuple(_vexil__vexil_field_0_fixed_items)
        return DataFixedBytes(_vexil_field_0)
    else:
        raise ValueError(f"unknown Data discriminant: {_vexil_discriminant}")

def decode_Data(data: bytes) -> Data:
    _vexil_reader = _BitReader(data)
    return decode_Data_from(_vexil_reader)


# ---------- EdgeCases ----------
@dataclass
class EdgeCases:
    single: tuple[int, ...]
    large: tuple[int, ...]
    hex_sized: tuple[int, ...]
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        self.encode_to(w)
        return w.finish()

    def encode_to(self, w: _BitWriter):
        for item in self.single:
            w.write_u8(item)
        for item in self.large:
            w.write_u8(item)
        for item in self.hex_sized:
            w.write_u16(item)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        return EdgeCases.decode_from(r)

    @staticmethod
    def decode_from(r: _BitReader):
        m = EdgeCases.__new__(EdgeCases)
        _vexil_m_single_fixed_items: list[int] = []
        for _ in range(1):
            _vexil_m_single_fixed_item = r.read_u8()
            _vexil_m_single_fixed_items.append(_vexil_m_single_fixed_item)
        m.single = tuple(_vexil_m_single_fixed_items)
        _vexil_m_large_fixed_items: list[int] = []
        for _ in range(1024):
            _vexil_m_large_fixed_item = r.read_u8()
            _vexil_m_large_fixed_items.append(_vexil_m_large_fixed_item)
        m.large = tuple(_vexil_m_large_fixed_items)
        _vexil_m_hex_sized_fixed_items: list[int] = []
        for _ in range(16):
            _vexil_m_hex_sized_fixed_item = r.read_u16()
            _vexil_m_hex_sized_fixed_items.append(_vexil_m_hex_sized_fixed_item)
        m.hex_sized = tuple(_vexil_m_hex_sized_fixed_items)
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m


