# Code generated by vexilc. DO NOT EDIT.
# Source: test.map_key_ordering

from __future__ import annotations
from dataclasses import dataclass
from typing import Optional

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import _BitWriter, _BitReader

SCHEMA_HASH: tuple[int, ...] = (0xf6, 0x28, 0xdf, 0x10, 0x8a, 0xab, 0x0d, 0x88, 0x79, 0x58, 0x8a, 0x9f, 0xe6, 0xf8, 0x5f, 0x4a, 0xb6, 0x27, 0x11, 0x96, 0xd4, 0x78, 0x05, 0xce, 0x3e, 0x33, 0x37, 0x5b, 0x81, 0x1d, 0x3e, 0xc9)
SCHEMA_VERSION: str = "1.0.0"


# ---------- Status ----------
class Status(int):
    ACTIVE = 1
    PENDING = 0
    COMPLETED = 2

    def encode(self) -> bytes:
        return _BitWriter().write_bits(int(self), 2).finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        v = r.read_bits(2)
        return Status(v)

    def __repr__(self) -> str:
        return f"Status({int(self)})"


# ---------- Permissions ----------
class Permissions(int):
    READ = 1
    WRITE = 2
    EXECUTE = 4

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_u8(int(self))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        v = r.read_u8()
        return Permissions(v)

    def has(self, flag: int):
        return bool(int(self) & flag)

    def __repr__(self) -> str:
        return f"Permissions({int(self)})"


# ---------- UserId ----------
class UserId:

    def __init__(self, value):
        self.value: int = value

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_u32(self.value)
        return w.finish()

    @staticmethod
    def decode(data: bytes) -> UserId:
        r = _BitReader(data)
        inner: int = None  # type: ignore[assignment]
        inner = r.read_u32()
        return UserId(inner)

    def __repr__(self) -> str:
        return f"UserId({self.value!r})"

    def __eq__(self, other):
        return isinstance(other, UserId) and self.value == other.value


# ---------- Label ----------
class Label:

    def __init__(self, value):
        self.value: str = value

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_string(self.value)
        return w.finish()

    @staticmethod
    def decode(data: bytes) -> Label:
        r = _BitReader(data)
        inner: str = None  # type: ignore[assignment]
        inner = r.read_string()
        return Label(inner)

    def __repr__(self) -> str:
        return f"Label({self.value!r})"

    def __eq__(self, other):
        return isinstance(other, Label) and self.value == other.value


# ---------- MapKeyTest ----------
@dataclass
class MapKeyTest:
    bool_map: dict[bool, str]
    u8_map: dict[int, str]
    u32_map: dict[int, str]
    i32_map: dict[int, str]
    fixed_map: dict[int, str]
    string_map: dict[str, int]
    bytes_map: dict[bytes, int]
    uuid_map: dict[bytes, str]
    enum_map: dict[Status, str]
    flags_map: dict[Permissions, str]
    newtype_u32_map: dict[UserId, str]
    newtype_str_map: dict[Label, int]
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        w.write_leb128(len(self.bool_map))
        for map_k, map_v in self.bool_map.items():
            w.write_bool(map_k)
            w.write_string(map_v)
        w.write_leb128(len(self.u8_map))
        for map_k, map_v in self.u8_map.items():
            w.write_u8(map_k)
            w.write_string(map_v)
        w.write_leb128(len(self.u32_map))
        for map_k, map_v in self.u32_map.items():
            w.write_u32(map_k)
            w.write_string(map_v)
        w.write_leb128(len(self.i32_map))
        for map_k, map_v in self.i32_map.items():
            w.write_i32(map_k)
            w.write_string(map_v)
        w.write_leb128(len(self.fixed_map))
        for map_k, map_v in self.fixed_map.items():
            w.write_i32(map_k)
            w.write_string(map_v)
        w.write_leb128(len(self.string_map))
        for map_k, map_v in self.string_map.items():
            w.write_string(map_k)
            w.write_u32(map_v)
        w.write_leb128(len(self.bytes_map))
        for map_k, map_v in self.bytes_map.items():
            w.write_bytes(map_k)
            w.write_u32(map_v)
        w.write_leb128(len(self.uuid_map))
        for map_k, map_v in self.uuid_map.items():
            w.write_raw_bytes(map_k, 16)
            w.write_string(map_v)
        w.write_leb128(len(self.enum_map))
        for map_k, map_v in self.enum_map.items():
            map_k.encode_to(w)
            w.write_string(map_v)
        w.write_leb128(len(self.flags_map))
        for map_k, map_v in self.flags_map.items():
            map_k.encode_to(w)
            w.write_string(map_v)
        w.write_leb128(len(self.newtype_u32_map))
        for map_k, map_v in self.newtype_u32_map.items():
            w.extend(map_k.encode())
            w.write_string(map_v)
        w.write_leb128(len(self.newtype_str_map))
        for map_k, map_v in self.newtype_str_map.items():
            w.extend(map_k.encode())
            w.write_u32(map_v)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))
        return w.finish()

    @staticmethod
    def decode(data: bytes):
        r = _BitReader(data)
        m = MapKeyTest.__new__(MapKeyTest)
        map_len = r.read_leb128()
        m.bool_map: dict[bool, str] = {}
        for _ in range(map_len):
            _k: bool = None  # type: ignore[assignment]
            _v: str = None  # type: ignore[assignment]
            _k = r.read_bool()
            _v = r.read_string()
            m.bool_map[_k] = _v
        map_len = r.read_leb128()
        m.u8_map: dict[int, str] = {}
        for _ in range(map_len):
            _k: int = None  # type: ignore[assignment]
            _v: str = None  # type: ignore[assignment]
            _k = r.read_u8()
            _v = r.read_string()
            m.u8_map[_k] = _v
        map_len = r.read_leb128()
        m.u32_map: dict[int, str] = {}
        for _ in range(map_len):
            _k: int = None  # type: ignore[assignment]
            _v: str = None  # type: ignore[assignment]
            _k = r.read_u32()
            _v = r.read_string()
            m.u32_map[_k] = _v
        map_len = r.read_leb128()
        m.i32_map: dict[int, str] = {}
        for _ in range(map_len):
            _k: int = None  # type: ignore[assignment]
            _v: str = None  # type: ignore[assignment]
            _k = r.read_i32()
            _v = r.read_string()
            m.i32_map[_k] = _v
        map_len = r.read_leb128()
        m.fixed_map: dict[int, str] = {}
        for _ in range(map_len):
            _k: int = None  # type: ignore[assignment]
            _v: str = None  # type: ignore[assignment]
            _k = r.read_i32()
            _v = r.read_string()
            m.fixed_map[_k] = _v
        map_len = r.read_leb128()
        m.string_map: dict[str, int] = {}
        for _ in range(map_len):
            _k: str = None  # type: ignore[assignment]
            _v: int = None  # type: ignore[assignment]
            _k = r.read_string()
            _v = r.read_u32()
            m.string_map[_k] = _v
        map_len = r.read_leb128()
        m.bytes_map: dict[bytes, int] = {}
        for _ in range(map_len):
            _k: bytes = None  # type: ignore[assignment]
            _v: int = None  # type: ignore[assignment]
            _k = r.read_bytes()
            _v = r.read_u32()
            m.bytes_map[_k] = _v
        map_len = r.read_leb128()
        m.uuid_map: dict[bytes, str] = {}
        for _ in range(map_len):
            _k: bytes = None  # type: ignore[assignment]
            _v: str = None  # type: ignore[assignment]
            _k = r.read_raw_bytes(16)
            _v = r.read_string()
            m.uuid_map[_k] = _v
        map_len = r.read_leb128()
        m.enum_map: dict[Status, str] = {}
        for _ in range(map_len):
            _k: Status = None  # type: ignore[assignment]
            _v: str = None  # type: ignore[assignment]
            _k = Status.decode_from(r)
            _v = r.read_string()
            m.enum_map[_k] = _v
        map_len = r.read_leb128()
        m.flags_map: dict[Permissions, str] = {}
        for _ in range(map_len):
            _k: Permissions = None  # type: ignore[assignment]
            _v: str = None  # type: ignore[assignment]
            _k = Permissions.decode_from(r)
            _v = r.read_string()
            m.flags_map[_k] = _v
        map_len = r.read_leb128()
        m.newtype_u32_map: dict[UserId, str] = {}
        for _ in range(map_len):
            _k: UserId = None  # type: ignore[assignment]
            _v: str = None  # type: ignore[assignment]
            _payload = r.read_bytes()
            _k = UserId.decode(_payload)
            _v = r.read_string()
            m.newtype_u32_map[_k] = _v
        map_len = r.read_leb128()
        m.newtype_str_map: dict[Label, int] = {}
        for _ in range(map_len):
            _k: Label = None  # type: ignore[assignment]
            _v: int = None  # type: ignore[assignment]
            _payload = r.read_bytes()
            _k = Label.decode(_payload)
            _v = r.read_u32()
            m.newtype_str_map[_k] = _v
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m


