# Code generated by vexilc. DO NOT EDIT.
# Source: test.union_unknown

from __future__ import annotations

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import BitWriter as _BitWriter, BitReader as _BitReader, EncodeError, DecodeError, MAX_BYTES_LENGTH, MAX_LENGTH_PREFIX_BYTES

SCHEMA_HASH: tuple[int, ...] = (0x37, 0xaa, 0x69, 0x59, 0xbd, 0x52, 0x55, 0xc1, 0x24, 0x8d, 0x0d, 0xe0, 0x56, 0xe7, 0x71, 0x98, 0x64, 0x3e, 0x5e, 0x00, 0x37, 0x00, 0xdf, 0x2c, 0x9b, 0x3a, 0x8d, 0x19, 0xc5, 0x9f, 0x91, 0xca)


# ---------- Event ----------
class Event:

    def encode(self) -> bytes:
        _vexil_writer = _BitWriter()
        self.encode_to(_vexil_writer)
        return _vexil_writer.finish()

    def encode_to(self, _vexil_writer: _BitWriter) -> None:
        raise NotImplementedError

class EventUnknown(Event):
    def __init__(self, reason: str):
        self.reason = reason

    def encode_to(self, _vexil_writer: _BitWriter) -> None:
        _vexil_writer.write_leb128(0)
        _vexil_payload_writer = _BitWriter()
        _vexil_payload_writer.write_string(self.reason)
        _vexil_payload_writer.flush_to_byte_boundary()
        _vexil_payload = _vexil_payload_writer.finish()
        _vexil_writer.write_leb128(len(_vexil_payload))
        _vexil_writer.write_raw_bytes(_vexil_payload, len(_vexil_payload))


class EventData(Event):
    def __init__(self, value: int):
        self.value = value

    def encode_to(self, _vexil_writer: _BitWriter) -> None:
        _vexil_writer.write_leb128(1)
        _vexil_payload_writer = _BitWriter()
        _vexil_payload_writer.write_u16(self.value)
        _vexil_payload_writer.flush_to_byte_boundary()
        _vexil_payload = _vexil_payload_writer.finish()
        _vexil_writer.write_leb128(len(_vexil_payload))
        _vexil_writer.write_raw_bytes(_vexil_payload, len(_vexil_payload))


class Event__VexilUnknown(Event):
    def __init__(self, discriminant: int, data: bytes):
        self.discriminant = discriminant
        self.data = data

    def encode_to(self, _vexil_writer: _BitWriter) -> None:
        if len(self.data) > MAX_BYTES_LENGTH:
            raise EncodeError(f"Event payload length {len(self.data)} exceeds limit {MAX_BYTES_LENGTH}")
        _vexil_writer.write_leb128(self.discriminant)
        _vexil_writer.write_leb128(len(self.data))
        _vexil_writer.write_raw_bytes(self.data, len(self.data))

def decode_Event_from(_vexil_reader: _BitReader) -> Event:
    _vexil_reader.flush_to_byte_boundary()
    _vexil_discriminant = _vexil_reader.read_leb128()
    _vexil_length = _vexil_reader.read_leb128(MAX_LENGTH_PREFIX_BYTES)
    if _vexil_length > MAX_BYTES_LENGTH:
        raise DecodeError(f"Event payload length {_vexil_length} exceeds limit {MAX_BYTES_LENGTH}")
    if _vexil_discriminant == 0:
        _vexil_payload = _vexil_reader.read_bytes(_vexil_length)
        _vexil_payload_reader = _BitReader(_vexil_payload)
        _vexil_field_0 = _vexil_payload_reader.read_string()
        return EventUnknown(_vexil_field_0)
    elif _vexil_discriminant == 1:
        _vexil_payload = _vexil_reader.read_bytes(_vexil_length)
        _vexil_payload_reader = _BitReader(_vexil_payload)
        _vexil_field_0 = _vexil_payload_reader.read_u16()
        return EventData(_vexil_field_0)
    else:
        _vexil_data = _vexil_reader.read_bytes(_vexil_length)
        return Event__VexilUnknown(_vexil_discriminant, _vexil_data)

def decode_Event(data: bytes) -> Event:
    _vexil_reader = _BitReader(data)
    return decode_Event_from(_vexil_reader)

__all__ = ["EncodeError", "DecodeError", "MAX_BYTES_LENGTH", "MAX_LENGTH_PREFIX_BYTES", "SCHEMA_HASH", "Event", "EventUnknown", "EventData", "Event__VexilUnknown", "decode_Event_from", "decode_Event"]
