# Code generated by vexilc. DO NOT EDIT.
# Source: test.identifier_conflicts

from __future__ import annotations
from dataclasses import dataclass
from typing import Protocol, runtime_checkable

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import BitWriter as _BitWriter, BitReader as _BitReader

SCHEMA_HASH: tuple[int, ...] = (0xe8, 0x9e, 0x3d, 0xf3, 0xbb, 0xd3, 0xf0, 0x51, 0x30, 0xe2, 0xa4, 0x92, 0x1c, 0x77, 0xdf, 0x4a, 0xaf, 0x61, 0x5b, 0x1e, 0x7c, 0x62, 0x54, 0xea, 0xae, 0x92, 0xa8, 0xc9, 0x5e, 0x27, 0x82, 0xf6)


# ---------- Settings ----------
@dataclass
class Settings:
    _vexil_self: int
    _vexil_unknown: int
    _vexil_from: int


# ---------- Fields ----------
@runtime_checkable
class Fields(Protocol):
    _vexil_self: int
    _vexil_unknown: int

# ---------- Collision ----------
@dataclass
class Collision:
    _vexil_from: int
    from_: int
    _vexil_self: int
    _vexil_unknown: bytes
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        try:
            w.enter_nested()
            self.encode_to(w)
        finally:
            w.leave_nested()
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_u8(self._vexil_from)
        w.write_u8(self.from_)
        w.write_u8(self._vexil_self)
        w.write_bytes(self._vexil_unknown)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> Collision:
        r = _BitReader(data)
        try:
            r.enter_nested()
            return Collision.decode_from(r)
        finally:
            r.leave_nested()

    @staticmethod
    def decode_from(r: _BitReader) -> Collision:
        m = Collision.__new__(Collision)
        m._vexil_from = r.read_u8()
        m.from_ = r.read_u8()
        m._vexil_self = r.read_u8()
        _vexil_m_2e__5f_vexil_5f_unknown_length = r.read_leb128()
        m._vexil_unknown = r.read_bytes(_vexil_m_2e__5f_vexil_5f_unknown_length)
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m



# ---------- Choice ----------
class Choice:

    def encode(self) -> bytes:
        _vexil_writer = _BitWriter()
        self.encode_to(_vexil_writer)
        return _vexil_writer.finish()

    def encode_to(self, _vexil_writer: _BitWriter) -> None:
        raise NotImplementedError

class ChoiceNamed(Choice):
    def __init__(self, _vexil_self: int, pr: int):
        self._vexil_self = _vexil_self
        self.pr = pr

    def encode_to(self, _vexil_writer: _BitWriter) -> None:
        _vexil_writer.write_leb128(0)
        _vexil_payload_writer = _BitWriter()
        _vexil_payload_writer.write_u8(self._vexil_self)
        _vexil_payload_writer.write_u16(self.pr)
        _vexil_payload_writer.flush_to_byte_boundary()
        _vexil_payload = _vexil_payload_writer.finish()
        _vexil_writer.write_leb128(len(_vexil_payload))
        _vexil_writer.write_raw_bytes(_vexil_payload, len(_vexil_payload))


def decode_Choice_from(_vexil_reader: _BitReader) -> Choice:
    _vexil_reader.flush_to_byte_boundary()
    _vexil_discriminant = _vexil_reader.read_leb128()
    _vexil_length = _vexil_reader.read_leb128()
    if _vexil_discriminant == 0:
        _vexil_payload = _vexil_reader.read_bytes(_vexil_length)
        _vexil_payload_reader = _BitReader(_vexil_payload)
        _vexil_field_0 = _vexil_payload_reader.read_u8()
        _vexil_field_1 = _vexil_payload_reader.read_u16()
        return ChoiceNamed(_vexil_field_0, _vexil_field_1)
    else:
        raise ValueError(f"unknown Choice discriminant: {_vexil_discriminant}")

def decode_Choice(data: bytes) -> Choice:
    _vexil_reader = _BitReader(data)
    return decode_Choice_from(_vexil_reader)

__all__ = ["dataclass", "Protocol", "runtime_checkable", "SCHEMA_HASH", "Settings", "Fields", "Collision", "Choice", "ChoiceNamed", "decode_Choice_from", "decode_Choice"]
