# Code generated by vexilc. DO NOT EDIT.
# Source: test.nested_optional_constraint

from __future__ import annotations
from dataclasses import dataclass

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import BitWriter as _BitWriter, BitReader as _BitReader, DecodeError

SCHEMA_HASH: tuple[int, ...] = (0x63, 0x55, 0xb4, 0xa1, 0x61, 0xe9, 0xa7, 0x0e, 0x3c, 0x62, 0xf1, 0xfb, 0x3c, 0x50, 0x70, 0x44, 0xf9, 0x65, 0xcd, 0x91, 0xe2, 0x16, 0xa5, 0x5b, 0x22, 0x1a, 0x82, 0x22, 0x88, 0x93, 0xbe, 0x30)


# ---------- M ----------
@dataclass
class M:
    v: tuple[int | None] | None
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        try:
            w.enter_nested()
            self.encode_to(w)
        finally:
            w.leave_nested()
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        if self.v is not None and self.v[0] is not None:
            if not (1 <= self.v[0] <= 1000):
                raise ValueError(f"constraint violation for field 'v': value {self.v[0]} violates constraint")
        _vexil_self_2e_v_optional = self.v
        w.write_bool(_vexil_self_2e_v_optional is not None)
        if _vexil_self_2e_v_optional is not None:
            _vexil__5f_vexil_5f_self_5f_2e_5f_v_5f_optional_5b_0_5d__optional = _vexil_self_2e_v_optional[0]
            w.write_bool(_vexil__5f_vexil_5f_self_5f_2e_5f_v_5f_optional_5b_0_5d__optional is not None)
            w.flush_to_byte_boundary()
            if _vexil__5f_vexil_5f_self_5f_2e_5f_v_5f_optional_5b_0_5d__optional is not None:
                w.write_u16(_vexil__5f_vexil_5f_self_5f_2e_5f_v_5f_optional_5b_0_5d__optional)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> M:
        r = _BitReader(data)
        try:
            r.enter_nested()
            return M.decode_from(r)
        finally:
            r.leave_nested()

    @staticmethod
    def decode_from(r: _BitReader) -> M:
        m = M.__new__(M)
        try:
            _vexil_m_2e_v_present = r.read_bool()
        except DecodeError:
            m.v = None
        else:
            if _vexil_m_2e_v_present:
                try:
                    _vexil__5f_vexil_5f_m_5f_2e_5f_v_5f_optional_5f_value_present = r.read_bool()
                except DecodeError:
                    _vexil_m_2e_v_optional_value = None
                else:
                    r.flush_to_byte_boundary()
                    if _vexil__5f_vexil_5f_m_5f_2e_5f_v_5f_optional_5f_value_present:
                        _vexil_m_2e_v_optional_value = r.read_u16()
                    else:
                        _vexil_m_2e_v_optional_value = None
                m.v = (_vexil_m_2e_v_optional_value,)
            else:
                m.v = None
        if m.v is not None and m.v[0] is not None:
            if not (1 <= m.v[0] <= 1000):
                raise ValueError(f"constraint violation for field 'v': value {m.v[0]} violates constraint")
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m

__all__ = ["dataclass", "DecodeError", "SCHEMA_HASH", "M"]
