# Code generated by vexilc. DO NOT EDIT.
# Source: test.typed.tombstone.shapes

from __future__ import annotations
from dataclasses import dataclass

# Runtime support (to be provided by vexil Python runtime)
from vexil_runtime import BitWriter as _BitWriter, BitReader as _BitReader

SCHEMA_HASH: tuple[int, ...] = (0x4d, 0xac, 0xa6, 0x04, 0x23, 0xa1, 0x95, 0xe3, 0x24, 0x5b, 0x30, 0xe0, 0x7e, 0x61, 0xfc, 0x62, 0x3c, 0x37, 0x49, 0xeb, 0xec, 0x52, 0xad, 0x00, 0x96, 0x08, 0x4b, 0xf0, 0x85, 0x0a, 0x50, 0x06)


# ---------- LegacyShapes ----------
@dataclass
class LegacyShapes:
    current: int
    unknown: bytes = b""

    def encode(self) -> bytes:
        w = _BitWriter()
        try:
            w.enter_nested()
            self.encode_to(w)
        finally:
            w.leave_nested()
        return w.finish()

    def encode_to(self, w: _BitWriter) -> None:
        w.write_u32(self.current)
        w.flush_to_byte_boundary()
        if self.unknown:
            w.write_raw_bytes(self.unknown, len(self.unknown))

    @staticmethod
    def decode(data: bytes) -> LegacyShapes:
        r = _BitReader(data)
        try:
            r.enter_nested()
            return LegacyShapes.decode_from(r)
        finally:
            r.leave_nested()

    @staticmethod
    def decode_from(r: _BitReader) -> LegacyShapes:
        m = LegacyShapes.__new__(LegacyShapes)
        m.current = r.read_u32()
        r.flush_to_byte_boundary()
        m.unknown = b""
        return m

__all__ = ["dataclass", "SCHEMA_HASH", "LegacyShapes"]
