//! Integration tests for multi-file project compilation + codegen.
//!
//! For each corpus project:
//! 1. Load root file, create FilesystemLoader with project dir as include root
//! 2. Compile project via compile_project()
//! 3. Assert no error-level diagnostics
//! 4. Generate project files via the `CodegenBackend` trait, which is what
//!    emits cross-file `use` statements
//! 5. Verify the exact generated file set
//! 6. Compile the generated crate natively with Cargo
//!
//! The diamond test also proves that transitive type references
//! (`Graph -> LeftNode/RightNode -> Id`) are remapped to imports that resolve
//! without duplicate definitions.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};
use vexil_lang::codegen::CodegenBackend;
use vexil_lang::diagnostic::Severity;
use vexil_lang::project::ProjectResult;
use vexil_lang::resolve::FilesystemLoader;

static TEMP_PROJECT_COUNTER: AtomicU64 = AtomicU64::new(0);

struct TempProject {
    path: PathBuf,
    cleaned: bool,
}

impl TempProject {
    fn new(label: &str) -> Self {
        let sequence = TEMP_PROJECT_COUNTER.fetch_add(1, Ordering::Relaxed);
        let path = std::env::temp_dir().join(format!(
            "vexil-project-codegen-check-{label}-{}-{sequence}",
            std::process::id()
        ));
        std::fs::create_dir(&path).unwrap_or_else(|e| {
            panic!("failed to create temporary project {}: {e}", path.display())
        });
        Self {
            path,
            cleaned: false,
        }
    }

    fn path(&self) -> &Path {
        &self.path
    }

    fn cleanup(mut self) {
        std::fs::remove_dir_all(&self.path).unwrap_or_else(|e| {
            panic!(
                "failed to remove temporary project {}: {e}",
                self.path.display()
            )
        });
        self.cleaned = true;
    }
}

impl Drop for TempProject {
    fn drop(&mut self) {
        if !self.cleaned {
            let _ = std::fs::remove_dir_all(&self.path);
        }
    }
}

fn corpus_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("corpus")
        .join("projects")
}

/// Compile a corpus project and return its schemas plus generated files.
fn compile_project_files(
    project_name: &str,
    root_ns: &str,
    expected_schema_count: usize,
    expected_paths: &[&str],
) -> BTreeMap<PathBuf, String> {
    let project_dir = corpus_dir().join(project_name);

    // Build root file path from namespace: "simple.main" -> "simple/main.vexil"
    let root_segments: Vec<&str> = root_ns.split('.').collect();
    let mut root_path = project_dir.clone();
    for seg in &root_segments {
        root_path.push(seg);
    }
    root_path.set_extension("vexil");

    let source = std::fs::read_to_string(&root_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", root_path.display()));

    let loader = FilesystemLoader::new(vec![project_dir]);

    let result: ProjectResult = vexil_lang::compile_project(&source, &root_path, &loader)
        .unwrap_or_else(|e| panic!("compile_project failed for {project_name}: {e}"));

    let errors: Vec<_> = result
        .diagnostics
        .iter()
        .filter(|d| d.severity == Severity::Error)
        .collect();
    assert!(
        errors.is_empty(),
        "unexpected errors in {project_name}: {errors:?}"
    );

    assert_eq!(
        result.schemas.len(),
        expected_schema_count,
        "{project_name}: expected {expected_schema_count} schemas, got {}",
        result.schemas.len()
    );

    // Generate the whole project through the backend so cross-file `use`
    // statements are exercised, not just per-schema output.
    let backend = vexil_codegen_rust::RustBackend;
    let files = backend
        .generate_project(&result)
        .unwrap_or_else(|e| panic!("generate_project failed for {project_name}: {e}"));

    let generated_paths: Vec<String> = files
        .keys()
        .map(|path| path.to_string_lossy().replace('\\', "/"))
        .collect();
    assert_eq!(
        generated_paths, expected_paths,
        "{project_name}: generated file set changed"
    );

    for (path, content) in &files {
        assert!(
            !content.is_empty(),
            "{project_name}: empty file generated at {path:?}"
        );
        assert!(
            content.contains("// Code generated by vexilc"),
            "{project_name}: missing header in {path:?}"
        );
    }

    eprintln!(
        "{project_name}: {} schemas compiled, {} files generated",
        result.schemas.len(),
        files.len()
    );

    files
}

/// Write a generated project into `dir` as a compilable crate.
///
/// `generate_project` emits a top-level `mod.rs`; a crate needs that content at
/// `src/lib.rs` instead. Every other path is written under `src/` unchanged.
fn write_crate(dir: &Path, files: &BTreeMap<PathBuf, String>, runtime_path: &Path) {
    let src = dir.join("src");
    std::fs::create_dir_all(&src).unwrap();

    for (rel_path, content) in files {
        let target = if rel_path == Path::new("mod.rs") {
            src.join("lib.rs")
        } else {
            src.join(rel_path)
        };
        if let Some(parent) = target.parent() {
            std::fs::create_dir_all(parent).unwrap();
        }
        std::fs::write(&target, content).unwrap();
    }

    // Use forward slashes in the TOML path to avoid backslash escape issues on Windows.
    let runtime_path_str = runtime_path
        .to_str()
        .expect("runtime path must be valid UTF-8")
        .replace('\\', "/");
    std::fs::write(
        dir.join("Cargo.toml"),
        format!(
            r#"[package]
name = "project-codegen-check"
version = "0.1.0"
edition = "2021"

[dependencies]
vexil-runtime = {{ path = "{runtime_path_str}" }}
"#
        ),
    )
    .unwrap();
}

fn compile_generated_crate(project_name: &str, files: &BTreeMap<PathBuf, String>) {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir.parent().unwrap().parent().unwrap();
    let runtime_path = workspace_root.join("crates/vexil-runtime");

    let tmp = TempProject::new(project_name);
    write_crate(tmp.path(), files, &runtime_path);

    let output = std::process::Command::new("cargo")
        .args(["clippy", "--", "-D", "warnings"])
        .current_dir(tmp.path())
        .env("CARGO_TARGET_DIR", tmp.path().join("target"))
        .output()
        .expect("failed to run cargo clippy");

    tmp.cleanup();

    assert!(
        output.status.success(),
        "Generated {project_name} project failed to compile:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}

/// Simple two-file project: main imports types.
#[test]
fn project_simple() {
    let files = compile_project_files(
        "simple",
        "simple.main",
        2,
        &[
            "mod.rs",
            "simple/main.rs",
            "simple/mod.rs",
            "simple/types.rs",
        ],
    );
    compile_generated_crate("simple", &files);
}

/// Diamond dependency: root -> left + right -> base.
/// Verifies diamond dedup (base compiled only once).
#[test]
fn project_diamond() {
    compile_project_files(
        "diamond",
        "diamond.root",
        4,
        &[
            "diamond/base.rs",
            "diamond/left.rs",
            "diamond/mod.rs",
            "diamond/right.rs",
            "diamond/root.rs",
            "mod.rs",
        ],
    );
}

/// Mixed project with enum + message across three files.
#[test]
fn project_mixed() {
    let files = compile_project_files(
        "mixed",
        "mix.app",
        3,
        &[
            "mix/app.rs",
            "mix/mod.rs",
            "mix/shapes.rs",
            "mix/types.rs",
            "mod.rs",
        ],
    );
    compile_generated_crate("mixed", &files);
}

/// The diamond project exercises a transitive type reference:
/// `diamond.root::Graph -> left::LeftNode / right::RightNode -> base::Id`.
///
/// `Id` must be defined once in its own module and imported by every dependent
/// module, and the whole generated module tree must compile natively.
#[test]
fn project_diamond_compiles_natively() {
    let files = compile_project_files(
        "diamond",
        "diamond.root",
        4,
        &[
            "diamond/base.rs",
            "diamond/left.rs",
            "diamond/mod.rs",
            "diamond/right.rs",
            "diamond/root.rs",
            "mod.rs",
        ],
    );

    let get = |name: &str| -> &str {
        files
            .iter()
            .find(|(p, _)| p.to_string_lossy().replace('\\', "/") == name)
            .map(|(_, c)| c.as_str())
            .unwrap_or_else(|| {
                let present: Vec<String> = files
                    .keys()
                    .map(|p| p.to_string_lossy().replace('\\', "/"))
                    .collect();
                panic!("missing generated file {name}; generated: {present:?}")
            })
    };

    let base = get("diamond/base.rs");
    let left = get("diamond/left.rs");
    let right = get("diamond/right.rs");
    let root = get("diamond/root.rs");

    // `Id` is defined exactly once, in its defining schema's module.
    assert!(
        base.contains("pub struct Id {"),
        "base.rs should define Id, got:\n{base}"
    );
    let definitions = files
        .values()
        .filter(|c| c.contains("pub struct Id {"))
        .count();
    assert_eq!(
        definitions, 1,
        "Id must be defined once across the project, found {definitions}"
    );

    // Transitive dependents import it from the defining module, not redefine it.
    for (name, code) in [("left.rs", left), ("right.rs", right)] {
        assert!(
            code.contains("use crate::diamond::base::Id;"),
            "{name} should import Id from its defining module, got:\n{code}"
        );
        assert!(
            !code.contains("pub struct Id {"),
            "{name} must not redefine Id, got:\n{code}"
        );
    }

    // The root imports its direct dependencies from their own modules.
    assert!(
        root.contains("use crate::diamond::left::LeftNode;"),
        "root.rs should import LeftNode from diamond::left, got:\n{root}"
    );
    assert!(
        root.contains("use crate::diamond::right::RightNode;"),
        "root.rs should import RightNode from diamond::right, got:\n{root}"
    );

    compile_generated_crate("diamond", &files);
}

#[test]
fn aliased_trait_project_compiles_natively() {
    let project_dir = corpus_dir().join("trait_alias");
    let root_path = project_dir.join("app/root.vexil");
    let source = std::fs::read_to_string(&root_path).expect("read aliased trait root");
    let loader = FilesystemLoader::new(vec![project_dir]);
    let result =
        vexil_lang::compile_project(&source, &root_path, &loader).expect("compile aliased project");
    assert!(
        result
            .diagnostics
            .iter()
            .all(|diagnostic| diagnostic.severity != Severity::Error),
        "{:#?}",
        result.diagnostics
    );
    let files = vexil_codegen_rust::RustBackend
        .generate_project(&result)
        .expect("generate aliased Rust project");

    let workspace_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("crates directory")
        .parent()
        .expect("workspace root")
        .to_path_buf();
    let runtime_path = workspace_root
        .join("crates/vexil-runtime")
        .to_string_lossy()
        .replace('\\', "/");
    let temp =
        std::env::temp_dir().join(format!("vexil-rust-alias-project-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&temp);
    std::fs::create_dir_all(temp.join("src")).expect("create source directory");
    for (relative, content) in files {
        let destination = temp.join("src").join(relative);
        if let Some(parent) = destination.parent() {
            std::fs::create_dir_all(parent).expect("create generated module directory");
        }
        std::fs::write(destination, content).expect("write generated Rust module");
    }
    std::fs::write(
        temp.join("src/lib.rs"),
        "pub mod traits { pub mod contracts; }\npub mod app { pub mod root; }\n",
    )
    .expect("write crate root");
    std::fs::write(
        temp.join("Cargo.toml"),
        format!(
            "[package]\nname = \"vexil-alias-contract\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[dependencies]\nvexil-runtime = {{ path = \"{runtime_path}\" }}\n"
        ),
    )
    .expect("write Cargo manifest");

    let output = std::process::Command::new("cargo")
        .args(["clippy", "--", "-D", "warnings"])
        .current_dir(&temp)
        .env("CARGO_TARGET_DIR", temp.join("target"))
        .output()
        .expect("run native Rust check");
    let _ = std::fs::remove_dir_all(&temp);
    assert!(
        output.status.success(),
        "generated aliased Rust project failed Clippy:\n{}",
        String::from_utf8_lossy(&output.stderr)
    );
}
