//! Rust code generation backend for the Vexil schema compiler.
//!
//! Implements the [`CodegenBackend`](vexil_lang::codegen::CodegenBackend) trait,
//! generating Rust structs with `Pack`/`Unpack` implementations for wire encoding.
//!
//! # Usage
//!
//! ```ignore
//! let result = vexil_lang::compile(source);
//! let code = vexil_codegen_rust::generate(&result.compiled.unwrap());
//! ```

pub mod annotations;
pub mod backend;
pub mod boxing;
pub mod config;
pub mod delta;
pub mod emit;
pub mod enum_gen;
pub mod flags;
pub mod fn_body;
pub mod message;
pub mod newtype;
pub mod trait_gen;
pub mod types;
pub mod union_gen;

pub use backend::RustBackend;

use std::collections::HashMap;

use vexil_lang::ir::{CompiledSchema, ResolvedType, TypeDef, TypeId};

/// Errors that can occur during Rust code generation.
#[derive(Debug, Clone, PartialEq, thiserror::Error)]
pub enum CodegenError {
    /// A type reference could not be resolved in the schema registry.
    #[error("unresolved type {type_id:?} referenced by {referenced_by}")]
    UnresolvedType {
        type_id: TypeId,
        referenced_by: String,
    },
    /// A function body cannot be projected to portable target code.
    #[error(transparent)]
    PortableFunction(#[from] vexil_lang::codegen::portable::PortableFunctionError),
    /// A projected function collides with another generated Rust member.
    #[error("Rust identifier collision for '{name}': {context}")]
    IdentifierCollision { name: String, context: String },
}

/// Generate Rust code for a compiled schema (no cross-file imports).
pub fn generate(compiled: &CompiledSchema) -> Result<String, CodegenError> {
    generate_with_imports(compiled, None)
}

/// Generate Rust code for a compiled schema, with optional cross-file import `use` statements.
///
/// `import_paths` maps TypeIds of imported types to their Rust module paths
/// (e.g., `"crate::foo::bar::types::Baz"` for a type `Baz` from namespace `foo.bar.types`).
pub(crate) fn generate_with_imports(
    compiled: &CompiledSchema,
    import_paths: Option<&HashMap<TypeId, String>>,
) -> Result<String, CodegenError> {
    preflight_trait_functions(compiled)?;
    // Step 1: Detect recursive types that need Box<T> wrapping.
    let needs_box = boxing::detect_boxing(compiled);

    // Step 2: Create the code writer.
    let mut w = emit::CodeWriter::new();

    // Step 3: Emit header.
    w.line("// Code generated by vexilc. DO NOT EDIT.");
    let ns = compiled.namespace.join(".");
    w.line(&format!("// Source: {ns}"));

    // Step 4: Emit blank line.
    w.blank();

    // Step 5: Check if any type uses Map -> emit BTreeMap import.
    if schema_uses_map(compiled) {
        w.line("use std::collections::BTreeMap;");
    }
    // Cross-file use statements.
    if let Some(paths) = import_paths {
        let mut unique_paths: Vec<&String> = paths.values().collect();
        unique_paths.sort();
        unique_paths.dedup();
        for path in unique_paths {
            w.line(&format!("use {path};"));
        }
    }

    // Step 7: Emit blank line.
    w.blank();

    // Emit SCHEMA_HASH (always present — every schema has a hash).
    let hash = vexil_lang::canonical::schema_hash(compiled);
    let hash_str = hash
        .iter()
        .map(|b| format!("0x{b:02x}"))
        .collect::<Vec<_>>()
        .join(", ");
    w.line(&format!("pub const SCHEMA_HASH: [u8; 32] = [{hash_str}];"));

    // Emit SCHEMA_VERSION if present (after SCHEMA_HASH per spec §8.2).
    if let Some(ref version) = compiled.annotations.version {
        w.line(&format!("pub const SCHEMA_VERSION: &str = \"{version}\";"));
    }

    // Step 9: For each declared type, emit the appropriate code.
    for &type_id in &compiled.declarations {
        let typedef =
            compiled
                .registry
                .get(type_id)
                .ok_or_else(|| CodegenError::UnresolvedType {
                    type_id,
                    referenced_by: "declarations".to_string(),
                })?;

        // Emit blank line + section separator comment.
        w.blank();
        let type_name = type_name_of(typedef);
        w.line(&format!("// \u{2500}\u{2500} {type_name} \u{2500}\u{2500}"));

        // Dispatch to the appropriate emitter.
        match typedef {
            TypeDef::Message(msg) => {
                message::emit_message(&mut w, msg, &compiled.registry, &needs_box, type_id);
                delta::emit_delta(&mut w, msg, &compiled.registry);
            }
            TypeDef::Enum(en) => {
                enum_gen::emit_enum(&mut w, en, &compiled.registry);
            }
            TypeDef::Flags(fl) => {
                flags::emit_flags(&mut w, fl, &compiled.registry);
            }
            TypeDef::Union(un) => {
                union_gen::emit_union(&mut w, un, &compiled.registry, &needs_box, type_id);
            }
            TypeDef::Newtype(nt) => {
                newtype::emit_newtype(&mut w, nt, &compiled.registry, &needs_box);
            }
            TypeDef::Config(cfg) => {
                config::emit_config(&mut w, cfg, &compiled.registry, &needs_box);
            }
            TypeDef::Trait(trait_def) => {
                trait_gen::emit_trait(&mut w, type_id, trait_def, compiled)?
            }
            _ => {} // non_exhaustive guard
        }
    }

    for (_, impl_def) in compiled.impls() {
        w.blank();
        w.line(&format!("// ── impl {} ──", impl_def.trait_name));
        trait_gen::emit_impl(&mut w, impl_def, compiled, &needs_box)?;
    }

    Ok(w.finish())
}

/// Generate a `mod.rs` file that re-exports child modules.
///
/// Produces a source string containing `pub mod <name>;` declarations
/// for each entry in `module_names`, suitable for writing to `mod.rs`.
pub fn generate_mod_file(module_names: &[&str]) -> String {
    let mut w = emit::CodeWriter::new();
    w.line("// Code generated by vexilc. DO NOT EDIT.");
    w.blank();
    for name in module_names {
        w.line(&format!("pub mod {name};"));
    }
    w.finish()
}

/// Returns the name of a TypeDef for use in section separator comments.
pub(crate) fn type_name_of(typedef: &TypeDef) -> &str {
    match typedef {
        TypeDef::Message(m) => m.name.as_str(),
        TypeDef::Enum(e) => e.name.as_str(),
        TypeDef::Flags(f) => f.name.as_str(),
        TypeDef::Union(u) => u.name.as_str(),
        TypeDef::Newtype(n) => n.name.as_str(),
        TypeDef::Config(c) => c.name.as_str(),
        TypeDef::Trait(t) => t.name.as_str(),
        _ => "Unknown", // non_exhaustive guard
    }
}

fn preflight_trait_functions(compiled: &CompiledSchema) -> Result<(), CodegenError> {
    for &type_id in &compiled.declarations {
        let Some(TypeDef::Trait(trait_def)) = compiled.registry.get(type_id) else {
            continue;
        };
        for function in vexil_lang::codegen::portable::trait_signatures(compiled, type_id)? {
            if trait_def
                .fields
                .iter()
                .any(|field| field.name == function.name)
            {
                return Err(CodegenError::IdentifierCollision {
                    name: function.name.to_string(),
                    context: "trait function conflicts with a generated field accessor".to_string(),
                });
            }
            reject_rust_keyword(function.name.as_str(), "trait function")?;
            for parameter in &function.params {
                reject_rust_keyword(parameter.name.as_str(), "function parameter")?;
            }
        }
    }

    let mut target_methods: HashMap<TypeId, Vec<String>> = HashMap::new();
    for (_, impl_def) in compiled.impls() {
        let functions = vexil_lang::codegen::portable::project_impl(compiled, impl_def)?;
        let (target_id, message) = match &impl_def.target_type {
            ResolvedType::Named(id) => match compiled.registry.get(*id) {
                Some(TypeDef::Message(message)) => (*id, message),
                _ => continue,
            },
            _ => continue,
        };
        for function in functions {
            if message
                .fields
                .iter()
                .any(|field| field.name == function.name)
                || matches!(function.name.as_str(), "pack" | "unpack")
            {
                return Err(CodegenError::IdentifierCollision {
                    name: function.name.to_string(),
                    context: "trait method conflicts with a generated Rust member".to_string(),
                });
            }
            reject_rust_keyword(function.name.as_str(), "trait method")?;
            let methods = target_methods.entry(target_id).or_default();
            if methods.iter().any(|name| name == function.name.as_str()) {
                return Err(CodegenError::IdentifierCollision {
                    name: function.name.to_string(),
                    context: "multiple implemented traits project the same Rust method".to_string(),
                });
            }
            methods.push(function.name.to_string());
            for parameter in &function.params {
                reject_rust_keyword(parameter.name.as_str(), "function parameter")?;
            }
            for statement in &function.statements {
                if let vexil_lang::codegen::portable::PortableStatement::Let { name, .. } =
                    statement
                {
                    reject_rust_keyword(name.as_str(), "local binding")?;
                }
            }
        }
    }
    Ok(())
}

fn reject_rust_keyword(name: &str, subject: &str) -> Result<(), CodegenError> {
    if is_rust_keyword(name) {
        Err(CodegenError::IdentifierCollision {
            name: name.to_string(),
            context: format!("{subject} is a reserved Rust keyword"),
        })
    } else {
        Ok(())
    }
}

fn is_rust_keyword(name: &str) -> bool {
    matches!(
        name,
        "as" | "async"
            | "await"
            | "break"
            | "const"
            | "continue"
            | "crate"
            | "dyn"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "union"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "abstract"
            | "become"
            | "box"
            | "do"
            | "final"
            | "macro"
            | "override"
            | "priv"
            | "typeof"
            | "unsized"
            | "virtual"
            | "yield"
            | "try"
    )
}

/// Returns true if any declaration in the schema uses a Map or Set type.
fn schema_uses_map(compiled: &CompiledSchema) -> bool {
    for &type_id in &compiled.declarations {
        if let Some(typedef) = compiled.registry.get(type_id) {
            if typedef_uses_map(typedef) {
                return true;
            }
        }
    }
    false
}

/// Returns true if a TypeDef contains a Map or Set field (recursively).
fn typedef_uses_map(typedef: &TypeDef) -> bool {
    match typedef {
        TypeDef::Message(msg) => msg
            .fields
            .iter()
            .any(|f| resolved_type_uses_map(&f.resolved_type)),
        TypeDef::Union(un) => un.variants.iter().any(|v| {
            v.fields
                .iter()
                .any(|f| resolved_type_uses_map(&f.resolved_type))
        }),
        TypeDef::Config(cfg) => cfg
            .fields
            .iter()
            .any(|f| resolved_type_uses_map(&f.resolved_type)),
        TypeDef::Newtype(nt) => resolved_type_uses_map(&nt.inner_type),
        _ => false,
    }
}

/// Returns true if a ResolvedType tree contains Map or Set.
fn resolved_type_uses_map(ty: &ResolvedType) -> bool {
    match ty {
        ResolvedType::Map(_, _) | ResolvedType::Set(_) => true,
        ResolvedType::Optional(inner) => resolved_type_uses_map(inner),
        ResolvedType::Array(inner) => resolved_type_uses_map(inner),
        ResolvedType::Result(ok, err) => resolved_type_uses_map(ok) || resolved_type_uses_map(err),
        _ => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_with_no_imports_matches_generate() {
        let result = vexil_lang::compile("namespace test.gen\nmessage Foo { x @0 : u32 }");
        let compiled = result.compiled.unwrap();
        let without = generate(&compiled).unwrap();
        let with = generate_with_imports(&compiled, None).unwrap();
        assert_eq!(without, with);
    }

    #[test]
    fn generate_with_imports_emits_use_statements() {
        let result = vexil_lang::compile("namespace test.gen\nmessage Foo { x @0 : u32 }");
        let compiled = result.compiled.unwrap();
        let foo_id = compiled.declarations[0];
        let mut paths = HashMap::new();
        paths.insert(foo_id, "crate::other::module::Bar".to_string());
        let code = generate_with_imports(&compiled, Some(&paths)).unwrap();
        assert!(code.contains("use crate::other::module::Bar;"));
    }

    #[test]
    fn generate_mod_file_produces_correct_output() {
        let output = generate_mod_file(&["foo", "bar"]);
        assert!(output.contains("// Code generated by vexilc. DO NOT EDIT."));
        assert!(output.contains("pub mod foo;"));
        assert!(output.contains("pub mod bar;"));
    }

    #[test]
    fn rust_backend_generate_matches_free_function() {
        use vexil_lang::codegen::CodegenBackend;
        let result = vexil_lang::compile("namespace test.backend\nmessage Foo { x @0 : u32 }");
        let compiled = result.compiled.unwrap();
        let free_fn = generate(&compiled).unwrap();
        let backend = crate::backend::RustBackend;
        let trait_fn = backend.generate(&compiled).unwrap();
        assert_eq!(free_fn, trait_fn);
    }

    #[test]
    fn generated_rust_avoids_lint_noise_and_preserves_field_docs() {
        let source = r#"
namespace test.lint
message Example {
    first @0 : u32
    @doc("second field")
    second @1 : u64 @varint
    text @2 : string
    values @3 : array<string>
}
config Settings {
    enabled : bool = true
}
"#;
        let compiled = vexil_lang::compile(source)
            .compiled
            .expect("schema compiles");
        let code = generate(&compiled).expect("code generation succeeds");

        assert!(!code.contains("use vexil_runtime::*;"));
        assert!(code.contains("/// second field\n    pub second: u64,"));
        assert!(code.contains("w.write_leb128(self.second);"));
        assert!(!code.contains("self.second as u64"));
        assert!(code.contains("w.write_string(self.text.as_str());"));
        assert!(code.contains("w.write_string(item.as_str());"));
    }

    #[test]
    fn config_only_output_has_no_runtime_import() {
        let compiled = vexil_lang::compile(
            "namespace test.config_only\nconfig Settings { enabled : bool = true }",
        )
        .compiled
        .expect("schema compiles");
        let code = generate(&compiled).expect("code generation succeeds");

        assert!(!code.contains("use vexil_runtime"));
    }

    #[test]
    fn nested_optional_presence_bits_are_contiguous() {
        let compiled = vexil_lang::compile(
            "namespace test.nested_optional\nmessage M { v @0 : optional<optional<u16>> }",
        )
        .compiled
        .expect("schema compiles");
        let code = generate(&compiled).expect("code generation succeeds");

        assert!(
            code.contains(
                "w.write_bool(self.v.is_some());\n        if let Some(ref inner_val) = self.v"
            ),
            "outer presence bit must not flush before the inner optional:\n{code}"
        );
        assert!(
            code.contains(
                "w.write_bool(inner_val.is_some());\n            if let Some(ref inner_val) = inner_val {\n                w.flush_to_byte_boundary();"
            ),
            "inner presence bit must flush only for a present u16 payload:\n{code}"
        );
        assert!(
            code.contains("let v_present = r.read_bool()?;\n        let v = if v_present"),
            "outer decode presence bit must not flush before the inner optional:\n{code}"
        );
    }

    #[test]
    fn generate_project_emits_cross_file_use_statements() {
        use vexil_lang::codegen::CodegenBackend;
        use vexil_lang::resolve::InMemoryLoader;
        let root_src = "namespace proj.root\nimport proj.dep\nmessage Foo { d @0 : Bar }";
        let dep_src = "namespace proj.dep\nmessage Bar { y @0 : string }";
        let mut loader = InMemoryLoader::new();
        loader.schemas.insert("proj.dep".into(), dep_src.into());
        let root_path = std::path::PathBuf::from("proj/root.vexil");
        let result = vexil_lang::compile_project(root_src, &root_path, &loader).unwrap();
        let backend = crate::backend::RustBackend;
        let files = backend.generate_project(&result).unwrap();
        // Find root.rs — it should contain a `use crate::proj::dep::Bar;` statement
        let root_code = files
            .iter()
            .find(|(p, _)| p.to_string_lossy().contains("root.rs"))
            .map(|(_, code)| code.as_str())
            .expect("missing root.rs");
        assert!(
            root_code.contains("use crate::proj::dep::Bar;"),
            "root.rs should contain cross-file use statement for Bar, got:\n{root_code}"
        );
    }

    #[test]
    fn rust_backend_generate_project_produces_files() {
        use vexil_lang::codegen::CodegenBackend;
        use vexil_lang::resolve::InMemoryLoader;
        let root_src = "namespace proj.root\nimport proj.dep\nmessage Foo { x @0 : u32 }";
        let dep_src = "namespace proj.dep\nmessage Bar { y @0 : string }";
        let mut loader = InMemoryLoader::new();
        loader.schemas.insert("proj.dep".into(), dep_src.into());
        let root_path = std::path::PathBuf::from("proj/root.vexil");
        let result = vexil_lang::compile_project(root_src, &root_path, &loader).unwrap();
        let backend = crate::backend::RustBackend;
        let files = backend.generate_project(&result).unwrap();
        // Should have schema files + mod.rs files
        assert!(
            files.len() >= 2,
            "expected at least 2 files, got {}",
            files.len()
        );
        // Should contain a .rs file for each namespace
        let has_root = files
            .keys()
            .any(|p| p.to_string_lossy().contains("root.rs"));
        let has_dep = files.keys().any(|p| p.to_string_lossy().contains("dep.rs"));
        assert!(
            has_root,
            "missing root.rs in output: {:?}",
            files.keys().collect::<Vec<_>>()
        );
        assert!(
            has_dep,
            "missing dep.rs in output: {:?}",
            files.keys().collect::<Vec<_>>()
        );
    }

    #[test]
    fn emits_function_bearing_traits() {
        let compiled = vexil_lang::compile(
            "namespace test.function_trait\ntrait Validatable {\n    fn validate() -> bool\n}",
        )
        .compiled
        .unwrap();
        let generated = generate(&compiled).expect("function signature generates");
        assert!(generated.contains("fn validate(&mut self) -> bool;"));
    }

    #[test]
    fn rejects_trait_function_member_collisions() {
        let compiled = vexil_lang::compile(
            "namespace test.collision\ntrait Conflicting { value @0 : i32 fn value() -> i32 }",
        )
        .compiled
        .unwrap();
        assert!(matches!(
            generate(&compiled),
            Err(CodegenError::IdentifierCollision { .. })
        ));
    }

    #[test]
    fn rejects_nonportable_calls_at_codegen_boundary() {
        let compiled = vexil_lang::compile(
            "namespace test.call\ntrait Validatable { fn validate() -> bool }\nmessage Event { value @0 : bool }\nimpl Validatable for Event { fn validate() -> bool { return helper() } }",
        )
        .compiled
        .unwrap();
        assert!(matches!(
            generate(&compiled),
            Err(CodegenError::PortableFunction(
                vexil_lang::codegen::portable::PortableFunctionError::UnsupportedCall { .. }
            ))
        ));
    }

    #[test]
    fn project_codegen_imports_trait_for_local_impl() {
        use vexil_lang::codegen::CodegenBackend;
        use vexil_lang::resolve::InMemoryLoader;

        let root_src = "namespace proj.root\nimport { Tagged } from proj.dep\nmessage Event { tag @0 : u64 }\nimpl Tagged<u64> for Event { fn retag(tag: u64) -> u64 { self.tag = tag return self.tag } }";
        let dep_src = "namespace proj.dep\ntrait Tagged<T> { tag @0 : T fn retag(tag: T) -> T }";
        let mut loader = InMemoryLoader::new();
        loader.schemas.insert("proj.dep".into(), dep_src.into());
        let result = vexil_lang::compile_project(
            root_src,
            &std::path::PathBuf::from("proj/root.vexil"),
            &loader,
        )
        .unwrap();
        assert!(result.diagnostics.is_empty(), "{:?}", result.diagnostics);

        let files = crate::backend::RustBackend
            .generate_project(&result)
            .unwrap();
        let root = files
            .iter()
            .find(|(path, _)| path.to_string_lossy().ends_with("root.rs"))
            .map(|(_, code)| code)
            .unwrap();
        assert!(root.contains("use crate::proj::dep::Tagged;"), "{root}");
        assert!(root.contains("impl Tagged<u64> for Event"), "{root}");
        assert!(
            root.contains("fn retag(&mut self, tag: u64) -> u64"),
            "{root}"
        );
    }
}
