// Code generated by vexilc. DO NOT EDIT.
// Source: test.message

import { BitReader, BitWriter } from '@vexil/runtime';

export const SCHEMA_HASH = new Uint8Array([0x97, 0xbc, 0xeb, 0x17, 0x56, 0x6b, 0xc1, 0xda, 0x25, 0x18, 0x59, 0x62, 0x39, 0x6c, 0xdf, 0x60, 0x32, 0x7b, 0xac, 0xce, 0x89, 0x7b, 0x85, 0xb7, 0x17, 0xfa, 0x73, 0xbd, 0xbe, 0xe5, 0x98, 0x01]);

// ── Empty ──
export interface Empty {
}

export function encodeEmpty(v: Empty, w: BitWriter): void {
  w.flushToByteBoundary();
}

export function decodeEmpty(r: BitReader): Empty {
  r.flushToByteBoundary();
  return {  };
}


// ── WithGaps ──
export interface WithGaps {
  first: number;
  third: number;
  tenth: string;
}

export function encodeWithGaps(v: WithGaps, w: BitWriter): void {
  w.writeU32(v.first);
  w.writeU32(v.third);
  w.writeString(v.tenth);
  w.flushToByteBoundary();
}

export function decodeWithGaps(r: BitReader): WithGaps {
  const first = r.readU32();
  const third = r.readU32();
  const tenth = r.readString();
  r.flushToByteBoundary();
  return { first, third, tenth };
}


// ── Annotated ──
export interface Annotated {
  version: number;
}

export function encodeAnnotated(v: Annotated, w: BitWriter): void {
  w.writeU8(v.version);
  w.flushToByteBoundary();
}

export function decodeAnnotated(r: BitReader): Annotated {
  const version = r.readU8();
  r.flushToByteBoundary();
  return { version };
}


// ── FieldAnnotations ──
export interface FieldAnnotations {
  a: number;
  b: bigint;
  c: string;
  d: number;
}

export function encodeFieldAnnotations(v: FieldAnnotations, w: BitWriter): void {
  w.writeU32(v.a);
  w.writeLeb128(BigInt(v.b));
  w.writeString(v.c);
  w.writeI32(v.d);
  w.flushToByteBoundary();
}

export function decodeFieldAnnotations(r: BitReader): FieldAnnotations {
  const a = r.readU32();
  const b = (r.readLeb128());
  const c = r.readString();
  const d = r.readI32();
  r.flushToByteBoundary();
  return { a, b, c, d };
}

