// Code generated by vexilc. DO NOT EDIT.
// Source: test.message

import { BitReader, BitWriter } from '@vexil-lang/runtime';

export const SCHEMA_HASH = new Uint8Array([0x97, 0xbc, 0xeb, 0x17, 0x56, 0x6b, 0xc1, 0xda, 0x25, 0x18, 0x59, 0x62, 0x39, 0x6c, 0xdf, 0x60, 0x32, 0x7b, 0xac, 0xce, 0x89, 0x7b, 0x85, 0xb7, 0x17, 0xfa, 0x73, 0xbd, 0xbe, 0xe5, 0x98, 0x01]);

// ── Empty ──
export interface Empty {
  _unknown: Uint8Array;
}

export function encodeEmpty(v: Empty, w: BitWriter): void {
  w.flushToByteBoundary();
  if (v._unknown.length > 0) {
    w.writeRawBytes(v._unknown);
  }
}

export function decodeEmpty(r: BitReader): Empty {
  r.flushToByteBoundary();
  const _unknown = r.readRemaining();
  return { _unknown };
}


// ── WithGaps ──
export interface WithGaps {
  first: number;
  third: number;
  tenth: string;
  _unknown: Uint8Array;
}

export function encodeWithGaps(v: WithGaps, w: BitWriter): void {
  w.writeU32(v.first);
  w.writeU32(v.third);
  w.writeString(v.tenth);
  w.flushToByteBoundary();
  if (v._unknown.length > 0) {
    w.writeRawBytes(v._unknown);
  }
}

export function decodeWithGaps(r: BitReader): WithGaps {
  const first = r.readU32();
  const third = r.readU32();
  const tenth = r.readString();
  r.flushToByteBoundary();
  const _unknown = r.readRemaining();
  return { first, third, tenth, _unknown };
}


// ── Annotated ──
export interface Annotated {
  version: number;
  _unknown: Uint8Array;
}

export function encodeAnnotated(v: Annotated, w: BitWriter): void {
  w.writeU8(v.version);
  w.flushToByteBoundary();
  if (v._unknown.length > 0) {
    w.writeRawBytes(v._unknown);
  }
}

export function decodeAnnotated(r: BitReader): Annotated {
  const version = r.readU8();
  r.flushToByteBoundary();
  const _unknown = r.readRemaining();
  return { version, _unknown };
}


// ── FieldAnnotations ──
export interface FieldAnnotations {
  a: number;
  b: bigint;
  c: string;
  d: number;
  _unknown: Uint8Array;
}

export function encodeFieldAnnotations(v: FieldAnnotations, w: BitWriter): void {
  w.writeU32(v.a);
  w.writeLeb12864(v.b);
  w.writeString(v.c);
  w.writeI32(v.d);
  w.flushToByteBoundary();
  if (v._unknown.length > 0) {
    w.writeRawBytes(v._unknown);
  }
}

export function decodeFieldAnnotations(r: BitReader): FieldAnnotations {
  const a = r.readU32();
  const b = r.readLeb12864();
  const c = r.readString();
  const d = r.readI32();
  r.flushToByteBoundary();
  const _unknown = r.readRemaining();
  return { a, b, c, d, _unknown };
}

export class FieldAnnotationsEncoder {
  private prevd: number = 0;

  encode(v: FieldAnnotations, w: BitWriter): void {
    w.writeU32(v.a);
    w.writeLeb12864(v.b);
    w.writeString(v.c);
    const delta_d = (v.d - this.prevd) | 0;
    w.writeI32(delta_d);
    this.prevd = v.d;
    w.flushToByteBoundary();
    if (v._unknown.length > 0) {
      w.writeRawBytes(v._unknown);
    }
  }

  reset(): void {
    this.prevd = 0;
  }
}

export class FieldAnnotationsDecoder {
  private prevd: number = 0;

  decode(r: BitReader): FieldAnnotations {
    const a = r.readU32();
    const b = r.readLeb12864();
    const c = r.readString();
    const delta_d = r.readI32();
    const d = (this.prevd + delta_d) | 0;
    this.prevd = d;
    r.flushToByteBoundary();
    const _unknown = r.readRemaining();
    return { a, b, c, d, _unknown };
  }

  reset(): void {
    this.prevd = 0;
  }
}

