// Code generated by vexilc. DO NOT EDIT.
// Source: test.enums

import { BitReader, BitWriter } from '@vexil-lang/runtime';

export const SCHEMA_HASH = new Uint8Array([0x8a, 0xc5, 0x25, 0xce, 0x0a, 0xec, 0xba, 0x7a, 0xf1, 0x28, 0xaf, 0x30, 0xbc, 0x21, 0x43, 0xe0, 0xfa, 0x59, 0x1b, 0x4a, 0x62, 0xf6, 0xd7, 0x19, 0x90, 0x74, 0xe9, 0xca, 0x84, 0x9e, 0x34, 0x68]);

// ── Direction ──
export type Direction = 'North' | 'South' | 'East' | 'West';
export const Direction = {
  North: 'North' as const,
  South: 'South' as const,
  East: 'East' as const,
  West: 'West' as const,
} as const;

export function encodeDirection(v: Direction, w: BitWriter): void {
  let disc: number;
  switch (v) {
    case 'North': disc = 0; break;
    case 'South': disc = 1; break;
    case 'East': disc = 2; break;
    case 'West': disc = 3; break;
    default: throw new Error(`Unknown Direction variant: ${v}`);
  }
  w.writeBits(disc, 2);
}

export function decodeDirection(r: BitReader): Direction {
  const disc = r.readBits(2);
  switch (disc) {
    case 0: return 'North';
    case 1: return 'South';
    case 2: return 'East';
    case 3: return 'West';
    default: throw new Error(`Unknown Direction discriminant: ${disc}`);
  }
}


// ── ClientKind ──
export type ClientKind = 'Renderer' | 'Agent' | 'Plugin' | 'Shell' | string;
export const ClientKind = {
  Renderer: 'Renderer' as const,
  Agent: 'Agent' as const,
  Plugin: 'Plugin' as const,
  Shell: 'Shell' as const,
} as const;

export function encodeClientKind(v: ClientKind, w: BitWriter): void {
  let disc: number;
  switch (v) {
    case 'Renderer': disc = 0; break;
    case 'Agent': disc = 1; break;
    case 'Plugin': disc = 2; break;
    case 'Shell': disc = 3; break;
    default: throw new Error(`Unknown ClientKind variant: ${v}`);
  }
  w.writeBits(disc, 8);
}

export function decodeClientKind(r: BitReader): ClientKind {
  const disc = r.readBits(8);
  switch (disc) {
    case 0: return 'Renderer';
    case 1: return 'Agent';
    case 2: return 'Plugin';
    case 3: return 'Shell';
    default: return `Unknown(${disc})`;
  }
}


// ── HardwareStatus ──
export type HardwareStatus = 'Ok' | 'Warn' | 'Fault';
export const HardwareStatus = {
  Ok: 'Ok' as const,
  Warn: 'Warn' as const,
  Fault: 'Fault' as const,
} as const;

export function encodeHardwareStatus(v: HardwareStatus, w: BitWriter): void {
  let disc: number;
  switch (v) {
    case 'Ok': disc = 0; break;
    case 'Warn': disc = 1; break;
    case 'Fault': disc = 2; break;
    default: throw new Error(`Unknown HardwareStatus variant: ${v}`);
  }
  w.writeBits(disc, 16);
}

export function decodeHardwareStatus(r: BitReader): HardwareStatus {
  const disc = r.readBits(16);
  switch (disc) {
    case 0: return 'Ok';
    case 1: return 'Warn';
    case 2: return 'Fault';
    default: throw new Error(`Unknown HardwareStatus discriminant: ${disc}`);
  }
}


// ── Sparse ──
export type Sparse = 'Low' | 'High';
export const Sparse = {
  Low: 'Low' as const,
  High: 'High' as const,
} as const;

export function encodeSparse(v: Sparse, w: BitWriter): void {
  let disc: number;
  switch (v) {
    case 'Low': disc = 0; break;
    case 'High': disc = 1000; break;
    default: throw new Error(`Unknown Sparse variant: ${v}`);
  }
  w.writeBits(disc, 32);
}

export function decodeSparse(r: BitReader): Sparse {
  const disc = r.readBits(32);
  switch (disc) {
    case 0: return 'Low';
    case 1000: return 'High';
    default: throw new Error(`Unknown Sparse discriminant: ${disc}`);
  }
}


// ── Lifecycle ──
export type Lifecycle = 'Active' | 'Pending';
export const Lifecycle = {
  Active: 'Active' as const,
  Pending: 'Pending' as const,
} as const;

export function encodeLifecycle(v: Lifecycle, w: BitWriter): void {
  let disc: number;
  switch (v) {
    case 'Active': disc = 0; break;
    case 'Pending': disc = 2; break;
    default: throw new Error(`Unknown Lifecycle variant: ${v}`);
  }
  w.writeBits(disc, 2);
}

export function decodeLifecycle(r: BitReader): Lifecycle {
  const disc = r.readBits(2);
  switch (disc) {
    case 0: return 'Active';
    case 2: return 'Pending';
    default: throw new Error(`Unknown Lifecycle discriminant: ${disc}`);
  }
}

