// Code generated by vexilc. DO NOT EDIT.
// Source: test.unions

import { BitReader, BitWriter } from '@vexil/runtime';

export const SCHEMA_HASH = new Uint8Array([0x2f, 0x63, 0x8f, 0x3e, 0x17, 0x8f, 0x50, 0x9c, 0x8f, 0x7b, 0xfb, 0x6d, 0x38, 0xa8, 0x56, 0x8f, 0x6e, 0x8c, 0xc9, 0xad, 0xe3, 0xf0, 0xa5, 0x06, 0x9a, 0x5c, 0x9d, 0x97, 0x97, 0x71, 0xa7, 0xb9]);

// ── Shape ──
export interface Shape_Circle {
  tag: 'Circle';
  radius: number;
}

export interface Shape_Rectangle {
  tag: 'Rectangle';
  width: number;
  height: number;
}

export interface Shape_Point {
  tag: 'Point';
}

export type Shape = Shape_Circle | Shape_Rectangle | Shape_Point;

export function encodeShape(v: Shape, w: BitWriter): void {
  w.flushToByteBoundary();
  switch (v.tag) {
    case 'Circle': {
      w.writeLeb128(BigInt(0));
      const payloadW = new BitWriter();
      payloadW.writeF32(v.radius);
      payloadW.flushToByteBoundary();
      const payload = payloadW.finish();
      w.writeLeb128(BigInt(payload.length));
      w.writeRawBytes(payload);
      break;
    }
    case 'Rectangle': {
      w.writeLeb128(BigInt(1));
      const payloadW = new BitWriter();
      payloadW.writeF32(v.width);
      payloadW.writeF32(v.height);
      payloadW.flushToByteBoundary();
      const payload = payloadW.finish();
      w.writeLeb128(BigInt(payload.length));
      w.writeRawBytes(payload);
      break;
    }
    case 'Point': {
      w.writeLeb128(BigInt(2));
      w.writeLeb128(0n);
      break;
    }
  }
}

export function decodeShape(r: BitReader): Shape {
  r.flushToByteBoundary();
  const disc = Number(r.readLeb128());
  const len = Number(r.readLeb128());
  switch (disc) {
    case 0: {
      const payloadBytes = r.readRawBytes(len);
      const pr = new BitReader(payloadBytes);
      const radius = pr.readF32();
      pr.flushToByteBoundary();
      return { tag: 'Circle' as const, radius };
    }
    case 1: {
      const payloadBytes = r.readRawBytes(len);
      const pr = new BitReader(payloadBytes);
      const width = pr.readF32();
      const height = pr.readF32();
      pr.flushToByteBoundary();
      return { tag: 'Rectangle' as const, width, height };
    }
    case 2: {
      r.readRawBytes(len);
      return { tag: 'Point' as const };
    }
    default: {
      throw new Error(`Unknown Shape discriminant: ${disc}`);
    }
  }
}


// ── Color ──
export interface Color_Ansi {
  tag: 'Ansi';
  code: number;
}

export interface Color_Rgb {
  tag: 'Rgb';
  r: number;
  g: number;
  b: number;
}

export interface Color_Reset {
  tag: 'Reset';
}

export interface Color_Unknown {
  tag: '__unknown';
  discriminant: number;
  data: Uint8Array;
}

export type Color = Color_Ansi | Color_Rgb | Color_Reset | Color_Unknown;

export function encodeColor(v: Color, w: BitWriter): void {
  w.flushToByteBoundary();
  switch (v.tag) {
    case 'Ansi': {
      w.writeLeb128(BigInt(0));
      const payloadW = new BitWriter();
      payloadW.writeU8(v.code);
      payloadW.flushToByteBoundary();
      const payload = payloadW.finish();
      w.writeLeb128(BigInt(payload.length));
      w.writeRawBytes(payload);
      break;
    }
    case 'Rgb': {
      w.writeLeb128(BigInt(1));
      const payloadW = new BitWriter();
      payloadW.writeU8(v.r);
      payloadW.writeU8(v.g);
      payloadW.writeU8(v.b);
      payloadW.flushToByteBoundary();
      const payload = payloadW.finish();
      w.writeLeb128(BigInt(payload.length));
      w.writeRawBytes(payload);
      break;
    }
    case 'Reset': {
      w.writeLeb128(BigInt(2));
      w.writeLeb128(0n);
      break;
    }
    case '__unknown': {
      w.writeLeb128(BigInt(v.discriminant));
      w.writeLeb128(BigInt(v.data.length));
      w.writeRawBytes(v.data);
      break;
    }
  }
}

export function decodeColor(r: BitReader): Color {
  r.flushToByteBoundary();
  const disc = Number(r.readLeb128());
  const len = Number(r.readLeb128());
  switch (disc) {
    case 0: {
      const payloadBytes = r.readRawBytes(len);
      const pr = new BitReader(payloadBytes);
      const code = pr.readU8();
      pr.flushToByteBoundary();
      return { tag: 'Ansi' as const, code };
    }
    case 1: {
      const payloadBytes = r.readRawBytes(len);
      const pr = new BitReader(payloadBytes);
      const r = pr.readU8();
      const g = pr.readU8();
      const b = pr.readU8();
      pr.flushToByteBoundary();
      return { tag: 'Rgb' as const, r, g, b };
    }
    case 2: {
      r.readRawBytes(len);
      return { tag: 'Reset' as const };
    }
    default: {
      const data = r.readRawBytes(len);
      return { tag: '__unknown' as const, discriminant: disc, data };
    }
  }
}


// ── Event ──
export interface Event_Click {
  tag: 'Click';
  x: number;
  y: number;
}

export interface Event_Scroll {
  tag: 'Scroll';
  delta: number;
}

export type Event = Event_Click | Event_Scroll;

export function encodeEvent(v: Event, w: BitWriter): void {
  w.flushToByteBoundary();
  switch (v.tag) {
    case 'Click': {
      w.writeLeb128(BigInt(0));
      const payloadW = new BitWriter();
      payloadW.writeU16(v.x);
      payloadW.writeU16(v.y);
      payloadW.flushToByteBoundary();
      const payload = payloadW.finish();
      w.writeLeb128(BigInt(payload.length));
      w.writeRawBytes(payload);
      break;
    }
    case 'Scroll': {
      w.writeLeb128(BigInt(2));
      const payloadW = new BitWriter();
      payloadW.writeI16(v.delta);
      payloadW.flushToByteBoundary();
      const payload = payloadW.finish();
      w.writeLeb128(BigInt(payload.length));
      w.writeRawBytes(payload);
      break;
    }
  }
}

export function decodeEvent(r: BitReader): Event {
  r.flushToByteBoundary();
  const disc = Number(r.readLeb128());
  const len = Number(r.readLeb128());
  switch (disc) {
    case 0: {
      const payloadBytes = r.readRawBytes(len);
      const pr = new BitReader(payloadBytes);
      const x = pr.readU16();
      const y = pr.readU16();
      pr.flushToByteBoundary();
      return { tag: 'Click' as const, x, y };
    }
    case 2: {
      const payloadBytes = r.readRawBytes(len);
      const pr = new BitReader(payloadBytes);
      const delta = pr.readI16();
      pr.flushToByteBoundary();
      return { tag: 'Scroll' as const, delta };
    }
    default: {
      throw new Error(`Unknown Event discriminant: ${disc}`);
    }
  }
}

