// Code generated by vexilc. DO NOT EDIT.
// Source: test.newtypes

import { BitReader, BitWriter } from '@vexil/runtime';

export const SCHEMA_HASH = new Uint8Array([0xc1, 0x54, 0xec, 0x4c, 0xc3, 0xc5, 0xab, 0x25, 0x76, 0xbb, 0x9e, 0x8b, 0x17, 0xea, 0x74, 0xd1, 0x1f, 0x81, 0x5e, 0x44, 0x18, 0x08, 0x3e, 0x3e, 0xa7, 0xe9, 0x7a, 0xc5, 0xdc, 0x0d, 0xbc, 0x17]);

// ── SessionId ──
export type SessionId = bigint;


// ── PaneId ──
export type PaneId = bigint;


// ── ExitCode ──
export type ExitCode = number;


// ── Name ──
export type Name = string;


// ── Payload ──
export type Payload = Uint8Array;


// ── Color ──
export type Color = [number, number, number];

