// Code generated by vexilc. DO NOT EDIT.
// Source: test.annotations

import { BitReader, BitWriter } from '@vexil-lang/runtime';

export const SCHEMA_HASH = new Uint8Array([0x79, 0x11, 0xcd, 0x44, 0x04, 0x6d, 0x10, 0x7a, 0xf1, 0xf1, 0x82, 0x9b, 0x7b, 0x72, 0x7b, 0x36, 0x1c, 0x74, 0xbf, 0x08, 0x23, 0xb7, 0x7d, 0xec, 0x49, 0x18, 0xe9, 0xd4, 0xe0, 0xb3, 0x05, 0x67]);
export const SCHEMA_VERSION = '1.2.0';

// ── OldMessage ──
export interface OldMessage {
  value: number;
  _unknown: Uint8Array;
}

export function encodeOldMessage(v: OldMessage, w: BitWriter): void {
  w.writeU32(v.value);
  w.flushToByteBoundary();
  if (v._unknown.length > 0) {
    w.writeRawBytes(v._unknown);
  }
}

export function decodeOldMessage(r: BitReader): OldMessage {
  const value = r.readU32();
  r.flushToByteBoundary();
  const _unknown = r.readRemaining();
  return { value, _unknown };
}


// ── Lifecycle ──
export interface Lifecycle {
  name: string;
  email: string;
  _unknown: Uint8Array;
}

export function encodeLifecycle(v: Lifecycle, w: BitWriter): void {
  w.writeString(v.name);
  w.writeString(v.email);
  w.flushToByteBoundary();
  if (v._unknown.length > 0) {
    w.writeRawBytes(v._unknown);
  }
}

export function decodeLifecycle(r: BitReader): Lifecycle {
  const name = r.readString();
  const email = r.readString();
  r.flushToByteBoundary();
  const _unknown = r.readRemaining();
  return { name, email, _unknown };
}


// ── Encoded ──
export interface Encoded {
  count: number;
  delta: number;
  offset: bigint;
  smooth: number;
  signed: bigint;
  _unknown: Uint8Array;
}

export function encodeEncoded(v: Encoded, w: BitWriter): void {
  w.writeLeb128(v.count);
  w.writeZigZag(v.delta, 32);
  w.writeU64(v.offset);
  w.writeLeb128(v.smooth);
  w.writeZigZag64(v.signed);
  w.flushToByteBoundary();
  if (v._unknown.length > 0) {
    w.writeRawBytes(v._unknown);
  }
}

export function decodeEncoded(r: BitReader): Encoded {
  const count = r.readLeb128();
  const delta = r.readZigZag(32);
  const offset = r.readU64();
  const smooth = r.readLeb128();
  const signed = r.readZigZag64();
  r.flushToByteBoundary();
  const _unknown = r.readRemaining();
  return { count, delta, offset, smooth, signed, _unknown };
}

export class EncodedEncoder {
  private prevoffset: bigint = 0n;
  private prevsmooth: number = 0;
  private prevsigned: bigint = 0n;

  encode(v: Encoded, w: BitWriter): void {
    w.writeLeb128(v.count);
    w.writeZigZag(v.delta, 32);
    const delta_offset = BigInt.asUintN(64, v.offset - this.prevoffset);
    w.writeU64(delta_offset);
    this.prevoffset = v.offset;
    const delta_smooth = (v.smooth - this.prevsmooth) >>> 0;
    w.writeLeb128(delta_smooth);
    this.prevsmooth = v.smooth;
    const delta_signed = v.signed - this.prevsigned;
    w.writeZigZag64(delta_signed);
    this.prevsigned = v.signed;
    w.flushToByteBoundary();
    if (v._unknown.length > 0) {
      w.writeRawBytes(v._unknown);
    }
  }

  reset(): void {
    this.prevoffset = 0n;
    this.prevsmooth = 0;
    this.prevsigned = 0n;
  }
}

export class EncodedDecoder {
  private prevoffset: bigint = 0n;
  private prevsmooth: number = 0;
  private prevsigned: bigint = 0n;

  decode(r: BitReader): Encoded {
    const count = r.readLeb128();
    const delta = r.readZigZag(32);
    const delta_offset = r.readU64();
    const offset = BigInt.asUintN(64, this.prevoffset + delta_offset);
    this.prevoffset = offset;
    const delta_smooth = r.readLeb128();
    const smooth = (this.prevsmooth + delta_smooth) >>> 0;
    this.prevsmooth = smooth;
    const delta_signed = r.readZigZag64();
    const signed = this.prevsigned + delta_signed;
    this.prevsigned = signed;
    r.flushToByteBoundary();
    const _unknown = r.readRemaining();
    return { count, delta, offset, smooth, signed, _unknown };
  }

  reset(): void {
    this.prevoffset = 0n;
    this.prevsmooth = 0;
    this.prevsigned = 0n;
  }
}


// ── Limited ──
export interface Limited {
  body: string;
  tags: string[];
  headers: Map<string, string>;
  data: Uint8Array;
  _unknown: Uint8Array;
}

export function encodeLimited(v: Limited, w: BitWriter): void {
  w.writeString(v.body);
  w.writeLeb128(v.tags.length);
  for (const item of v.tags) {
    w.writeString(item);
  }
  w.writeLeb128(v.headers.size);
  for (const [mapK, mapV] of v.headers) {
    w.writeString(mapK);
    w.writeString(mapV);
  }
  w.writeBytes(v.data);
  w.flushToByteBoundary();
  if (v._unknown.length > 0) {
    w.writeRawBytes(v._unknown);
  }
}

export function decodeLimited(r: BitReader): Limited {
  const body = r.readString();
  const tags_len = r.readLeb128();
  const tags: string[] = [];
  for (let i = 0; i < tags_len; i++) {
    const tags_item = r.readString();
    tags.push(tags_item);
  }
  const headers_len = r.readLeb128();
  const headers = new Map<string, string>();
  for (let i = 0; i < headers_len; i++) {
    const headers_k = r.readString();
    const headers_v = r.readString();
    headers.set(headers_k, headers_v);
  }
  const data = r.readBytes();
  r.flushToByteBoundary();
  const _unknown = r.readRemaining();
  return { body, tags, headers, data, _unknown };
}


// ── RenderCommand ──
export interface RenderCommand {
  op: number;
  _unknown: Uint8Array;
}

export function encodeRenderCommand(v: RenderCommand, w: BitWriter): void {
  w.writeU8(v.op);
  w.flushToByteBoundary();
  if (v._unknown.length > 0) {
    w.writeRawBytes(v._unknown);
  }
}

export function decodeRenderCommand(r: BitReader): RenderCommand {
  const op = r.readU8();
  r.flushToByteBoundary();
  const _unknown = r.readRemaining();
  return { op, _unknown };
}


// ── Documented ──
export interface Documented {
  value: number;
  _unknown: Uint8Array;
}

export function encodeDocumented(v: Documented, w: BitWriter): void {
  w.writeU32(v.value);
  w.flushToByteBoundary();
  if (v._unknown.length > 0) {
    w.writeRawBytes(v._unknown);
  }
}

export function decodeDocumented(r: BitReader): Documented {
  const value = r.readU32();
  r.flushToByteBoundary();
  const _unknown = r.readRemaining();
  return { value, _unknown };
}

