// Code generated by vexilc. DO NOT EDIT.
// Source: test.delta.message

import { BitReader, BitWriter } from '@vexil/runtime';

export const SCHEMA_HASH = new Uint8Array([0x07, 0x20, 0xc0, 0x79, 0x18, 0xe4, 0x24, 0xcf, 0xdb, 0xde, 0x48, 0xe0, 0xdb, 0x86, 0xb5, 0xb2, 0x2e, 0x55, 0x23, 0x7f, 0xf9, 0x9c, 0xe5, 0xd7, 0x95, 0x14, 0x35, 0x9e, 0x8f, 0xab, 0x99, 0x67]);

// ── Telemetry ──
export interface Telemetry {
  timestamp: bigint;
  value: number;
  label: string;
  count: number;
  _unknown: Uint8Array;
}

export function encodeTelemetry(v: Telemetry, w: BitWriter): void {
  w.writeZigZag64(v.timestamp);
  w.writeF32(v.value);
  w.writeString(v.label);
  w.writeLeb128(v.count);
  w.flushToByteBoundary();
  if (v._unknown.length > 0) {
    w.writeRawBytes(v._unknown);
  }
}

export function decodeTelemetry(r: BitReader): Telemetry {
  const timestamp = r.readZigZag64();
  const value = r.readF32();
  const label = r.readString();
  const count = r.readLeb128();
  r.flushToByteBoundary();
  const _unknown = r.readRemaining();
  return { timestamp, value, label, count, _unknown };
}

export class TelemetryEncoder {
  private prevtimestamp: bigint = 0n;
  private prevvalue: number = 0.0;
  private prevcount: number = 0;

  encode(v: Telemetry, w: BitWriter): void {
    const delta_timestamp = v.timestamp - this.prevtimestamp;
    w.writeZigZag64(delta_timestamp);
    this.prevtimestamp = v.timestamp;
    const delta_value = v.value - this.prevvalue;
    w.writeF32(delta_value);
    this.prevvalue = v.value;
    w.writeString(v.label);
    const delta_count = (v.count - this.prevcount) >>> 0;
    w.writeLeb128(delta_count);
    this.prevcount = v.count;
    w.flushToByteBoundary();
    if (v._unknown.length > 0) {
      w.writeRawBytes(v._unknown);
    }
  }

  reset(): void {
    this.prevtimestamp = 0n;
    this.prevvalue = 0.0;
    this.prevcount = 0;
  }
}

export class TelemetryDecoder {
  private prevtimestamp: bigint = 0n;
  private prevvalue: number = 0.0;
  private prevcount: number = 0;

  decode(r: BitReader): Telemetry {
    const delta_timestamp = r.readZigZag64();
    const timestamp = this.prevtimestamp + delta_timestamp;
    this.prevtimestamp = timestamp;
    const delta_value = r.readF32();
    const value = this.prevvalue + delta_value;
    this.prevvalue = value;
    const label = r.readString();
    const delta_count = r.readLeb128();
    const count = (this.prevcount + delta_count) >>> 0;
    this.prevcount = count;
    r.flushToByteBoundary();
    const _unknown = r.readRemaining();
    return { timestamp, value, label, count, _unknown };
  }

  reset(): void {
    this.prevtimestamp = 0n;
    this.prevvalue = 0.0;
    this.prevcount = 0;
  }
}

