// Code generated by vexilc. DO NOT EDIT.
// Source: test.typed.tombstone

import { BitReader, BitWriter } from '@vexil-lang/runtime';

export const SCHEMA_HASH = new Uint8Array([0x23, 0x9b, 0xc3, 0x16, 0x2d, 0xc1, 0xc8, 0x3d, 0x4a, 0x09, 0x6b, 0xb2, 0x03, 0xf1, 0xb3, 0x14, 0x3a, 0x4a, 0xbc, 0x27, 0xbb, 0xe4, 0x88, 0xee, 0x2b, 0x99, 0xf8, 0x68, 0x1f, 0x9b, 0x6e, 0x06]);

// ── Config ──
export interface Config {
  name: string;
  timeout_ms: bigint;
  _unknown: Uint8Array;
}

export function encodeConfig(v: Config, w: BitWriter): void {
  w.writeString(v.name);
  w.writeU64(v.timeout_ms);
  w.flushToByteBoundary();
  if (v._unknown.length > 0) {
    w.writeRawBytes(v._unknown);
  }
}

export function decodeConfig(r: BitReader): Config {
  const name = r.readString();
  // discard @removed ordinal 1
  r.readU32();
  const timeout_ms = r.readU64();
  r.flushToByteBoundary();
  const _unknown = new Uint8Array(0);
  return { name, timeout_ms, _unknown };
}

