// Code generated by vexilc. DO NOT EDIT.
// Source: test.trait_function_portable_body

import { BitReader, BitWriter } from '@vexil-lang/runtime';

export const SCHEMA_HASH = new Uint8Array([0xf0, 0x55, 0x8d, 0xce, 0xf6, 0x4f, 0x18, 0xb1, 0x08, 0xa4, 0x01, 0xc7, 0xba, 0xd5, 0x29, 0x8d, 0x06, 0x0b, 0xe3, 0x08, 0x48, 0xa3, 0xac, 0xab, 0x0c, 0xcc, 0x34, 0xfe, 0xc7, 0x42, 0xef, 0xb2]);

type _VexilAssertAssignable<T extends U, U> = T;

// ── Adjustable ──
export interface Adjustable<T> {
  readonly value: T;
  adjust(delta: T): T;
  reset(): void;
  snapshot(): Counter;
}

export function isAdjustable<T>(value: unknown): value is Adjustable<T> {
  return typeof value === 'object' && value !== null && 'value' in value && 'adjust' in value && typeof value.adjust === 'function' && 'reset' in value && typeof value.reset === 'function' && 'snapshot' in value && typeof value.snapshot === 'function';
}

// ── Counter ──
export interface Counter {
  value: number;
  _unknown: Uint8Array;
  adjust(delta: number): number;
  reset(): void;
  snapshot(): Counter;
}

export type CounterFields = Omit<Counter, 'adjust' | 'reset' | 'snapshot'>;
export function createCounter(fields: CounterFields): Counter {
  return {
    ...fields,
    adjust(delta: number): number {
      const previous: number = this.value;
      this.value = (this.value + delta);
      return previous;
    },
    reset(): void {
      this.value = 0;
      return;
    },
    snapshot(): Counter {
      return this;
    },
  };
}

export function encodeCounter(v: Counter, w: BitWriter): void {
  w.writeI32(v.value);
  w.flushToByteBoundary();
  if (v._unknown.length > 0) {
    w.writeRawBytes(v._unknown);
  }
}

export function decodeCounter(r: BitReader): Counter {
  const value = r.readI32();
  r.flushToByteBoundary();
  const _unknown = new Uint8Array(0);
  return createCounter({ value, _unknown });
}


type _CounterImplementsAdjustable = _VexilAssertAssignable<Counter, Adjustable<number>>;
