// Code generated by vexilc. DO NOT EDIT.
// Source: sensor.telemetry

use vexil_runtime::*;

pub const SCHEMA_HASH: [u8; 32] = [0xb1, 0x3d, 0xa4, 0x8d, 0x34, 0xbf, 0xd6, 0xc9, 0x4b, 0x13, 0xa3, 0x27, 0x52, 0x48, 0x5b, 0x9e, 0xf9, 0x6e, 0x6d, 0x16, 0x4d, 0x1c, 0xbc, 0x3f, 0x34, 0x8e, 0x34, 0x21, 0x37, 0x5f, 0x51, 0xa0];

// ── DeviceStatus ──
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u64)]
pub enum DeviceStatus {
    Online = 0_u64,
    Degraded = 1_u64,
    Offline = 2_u64,
    Error = 3_u64,
}

impl vexil_runtime::Pack for DeviceStatus {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        let disc: u64 = match self {
            Self::Online => 0_u64,
            Self::Degraded => 1_u64,
            Self::Offline => 2_u64,
            Self::Error => 3_u64,
        };
        w.write_bits(disc, 2_u8);
        Ok(())
    }
}

impl vexil_runtime::Unpack for DeviceStatus {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let disc = r.read_bits(2_u8)?;
        match disc {
            0_u64 => Ok(Self::Online),
            1_u64 => Ok(Self::Degraded),
            2_u64 => Ok(Self::Offline),
            3_u64 => Ok(Self::Error),
            _ => Err(vexil_runtime::DecodeError::UnknownEnumVariant { type_name: "DeviceStatus", value: disc }),
        }
    }
}


// ── SensorReading ──
#[derive(Debug, Clone, PartialEq)]
pub struct SensorReading {
    pub device_id: u32,
    pub battery: u8,
    pub signal: u8,
    pub status: DeviceStatus,
    pub temperature: f32,
    pub humidity: f32,
    pub label: String,
    pub gps_lat: Option<f64>,
    pub gps_lon: Option<f64>,
}

impl vexil_runtime::Pack for SensorReading {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_u32(self.device_id);
        w.write_bits(self.battery as u64, 7_u8);
        w.write_bits(self.signal as u64, 4_u8);
        w.enter_recursive()?;
        self.status.pack(w)?;
        w.leave_recursive();
        w.write_f32(self.temperature);
        w.write_f32(self.humidity);
        w.write_string(&self.label);
        w.write_bool(self.gps_lat.is_some());
        w.flush_to_byte_boundary();
        if let Some(ref inner_val) = self.gps_lat {
            w.write_f64(*inner_val);
        }
        w.write_bool(self.gps_lon.is_some());
        w.flush_to_byte_boundary();
        if let Some(ref inner_val) = self.gps_lon {
            w.write_f64(*inner_val);
        }
        w.flush_to_byte_boundary();
        Ok(())
    }
}

impl vexil_runtime::Unpack for SensorReading {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let device_id = r.read_u32()?;
        let battery = r.read_bits(7_u8)? as u8;
        let signal = r.read_bits(4_u8)? as u8;
        r.enter_recursive()?;
        let status = vexil_runtime::Unpack::unpack(r)?;
        r.leave_recursive();
        let temperature = r.read_f32()?;
        let humidity = r.read_f32()?;
        let label = r.read_string()?;
        let gps_lat_present = r.read_bool()?;
        r.flush_to_byte_boundary();
        let gps_lat = if gps_lat_present {
            let gps_lat_inner = r.read_f64()?;
            Some(gps_lat_inner)
        }
        else {
            None
        }
;
        let gps_lon_present = r.read_bool()?;
        r.flush_to_byte_boundary();
        let gps_lon = if gps_lon_present {
            let gps_lon_inner = r.read_f64()?;
            Some(gps_lon_inner)
        }
        else {
            None
        }
;
        r.flush_to_byte_boundary();
        Ok(Self {
            device_id,
            battery,
            signal,
            status,
            temperature,
            humidity,
            label,
            gps_lat,
            gps_lon,
        })
    }
}


// ── DeviceConfig ──
#[derive(Debug, Clone, PartialEq)]
pub struct DeviceConfig {
    pub device_id: u32,
    pub report_interval: u16,
    pub high_temp_alert: f32,
    pub low_temp_alert: f32,
    pub label: String,
}

impl vexil_runtime::Pack for DeviceConfig {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_u32(self.device_id);
        w.write_u16(self.report_interval);
        w.write_f32(self.high_temp_alert);
        w.write_f32(self.low_temp_alert);
        w.write_string(&self.label);
        w.flush_to_byte_boundary();
        Ok(())
    }
}

impl vexil_runtime::Unpack for DeviceConfig {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let device_id = r.read_u32()?;
        let report_interval = r.read_u16()?;
        let high_temp_alert = r.read_f32()?;
        let low_temp_alert = r.read_f32()?;
        let label = r.read_string()?;
        r.flush_to_byte_boundary();
        Ok(Self {
            device_id,
            report_interval,
            high_temp_alert,
            low_temp_alert,
            label,
        })
    }
}

