//! TypeScript code generation backend for the Vexil schema compiler.
//!
//! Generates TypeScript interfaces and encode/decode functions that use
//! the `@vexil-lang/runtime` npm package for wire I/O.

pub mod backend;
pub mod delta;
pub mod emit;
pub mod enum_gen;
pub mod flags;
pub mod message;
pub mod newtype;
pub mod types;
pub mod union_gen;

pub use backend::TypeScriptBackend;

use vexil_lang::ir::{CompiledSchema, TypeDef};

#[derive(Debug, Clone, PartialEq, thiserror::Error)]
pub enum CodegenError {
    #[error("unresolved type {type_id:?} referenced by {referenced_by}")]
    UnresolvedType {
        type_id: vexil_lang::ir::TypeId,
        referenced_by: String,
    },
}

/// Generate TypeScript code for a compiled schema (no cross-file imports).
pub fn generate(compiled: &CompiledSchema) -> Result<String, CodegenError> {
    generate_with_imports(compiled, None)
}

/// Generate TypeScript code for a compiled schema, with optional cross-file import statements.
///
/// `import_paths` maps type names to their module paths for cross-file imports.
pub(crate) fn generate_with_imports(
    compiled: &CompiledSchema,
    import_paths: Option<&std::collections::HashMap<String, String>>,
) -> Result<String, CodegenError> {
    let mut w = emit::CodeWriter::new();

    // Header
    w.line("// Code generated by vexilc. DO NOT EDIT.");
    let ns = compiled.namespace.join(".");
    w.line(&format!("// Source: {ns}"));
    w.blank();

    // Runtime import
    w.line("import { BitReader, BitWriter } from '@vexil-lang/runtime';");

    // Cross-file imports
    if let Some(paths) = import_paths {
        let mut imports: Vec<(&String, &String)> = paths.iter().collect();
        imports.sort_by_key(|(name, _)| (*name).clone());
        for (type_name, module_path) in imports {
            w.line(&format!(
                "import {{ {type_name}, encode{type_name}, decode{type_name} }} from '{module_path}';",
            ));
        }
    }
    w.blank();

    // Schema hash
    let hash = vexil_lang::canonical::schema_hash(compiled);
    let hash_str = hash
        .iter()
        .map(|b| format!("0x{b:02x}"))
        .collect::<Vec<_>>()
        .join(", ");
    w.line(&format!(
        "export const SCHEMA_HASH = new Uint8Array([{hash_str}]);"
    ));

    // Schema version
    if let Some(ref version) = compiled.annotations.version {
        w.line(&format!("export const SCHEMA_VERSION = '{version}';"));
    }

    // Emit each declared type
    for &type_id in &compiled.declarations {
        let typedef =
            compiled
                .registry
                .get(type_id)
                .ok_or_else(|| CodegenError::UnresolvedType {
                    type_id,
                    referenced_by: "declarations".to_string(),
                })?;

        w.blank();
        let type_name = type_name_of(typedef);
        w.line(&format!("// \u{2500}\u{2500} {type_name} \u{2500}\u{2500}"));

        match typedef {
            TypeDef::Message(msg) => {
                message::emit_message(&mut w, msg, &compiled.registry);
                delta::emit_delta(&mut w, msg, &compiled.registry);
            }
            TypeDef::Enum(en) => {
                enum_gen::emit_enum(&mut w, en, &compiled.registry);
            }
            TypeDef::Flags(fl) => {
                flags::emit_flags(&mut w, fl, &compiled.registry);
            }
            TypeDef::Union(un) => {
                union_gen::emit_union(&mut w, un, &compiled.registry);
            }
            TypeDef::Newtype(nt) => {
                newtype::emit_newtype(&mut w, nt, &compiled.registry);
            }
            TypeDef::Config(cfg) => {
                message::emit_config(&mut w, cfg, &compiled.registry);
            }
            _ => {} // non_exhaustive guard
        }
    }

    Ok(w.finish())
}

/// Returns the name of a TypeDef for use in section separator comments.
pub(crate) fn type_name_of(typedef: &TypeDef) -> &str {
    match typedef {
        TypeDef::Message(m) => m.name.as_str(),
        TypeDef::Enum(e) => e.name.as_str(),
        TypeDef::Flags(f) => f.name.as_str(),
        TypeDef::Union(u) => u.name.as_str(),
        TypeDef::Newtype(n) => n.name.as_str(),
        TypeDef::Config(c) => c.name.as_str(),
        _ => "Unknown",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_produces_output() {
        let result = vexil_lang::compile("namespace test.gen\nmessage Foo { x @0 : u32 }");
        let compiled = result.compiled.unwrap();
        let code = generate(&compiled).unwrap();
        assert!(code.contains("export interface Foo"));
        assert!(code.contains("export function encodeFoo"));
        assert!(code.contains("export function decodeFoo"));
        assert!(code.contains("import { BitReader, BitWriter } from '@vexil-lang/runtime'"));
    }

    #[test]
    fn generate_with_no_imports_matches_generate() {
        let result = vexil_lang::compile("namespace test.gen\nmessage Foo { x @0 : u32 }");
        let compiled = result.compiled.unwrap();
        let without = generate(&compiled).unwrap();
        let with = generate_with_imports(&compiled, None).unwrap();
        assert_eq!(without, with);
    }

    #[test]
    fn ts_backend_generate_matches_free_function() {
        use vexil_lang::codegen::CodegenBackend;
        let result = vexil_lang::compile("namespace test.backend\nmessage Foo { x @0 : u32 }");
        let compiled = result.compiled.unwrap();
        let free_fn = generate(&compiled).unwrap();
        let backend = crate::backend::TypeScriptBackend;
        let trait_fn = backend.generate(&compiled).unwrap();
        assert_eq!(free_fn, trait_fn);
    }
}
