name: Publish @vexil-lang/runtime to npm

on:
  push:
    tags:
      - "vexil-runtime-ts-v*"

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'vexil-lang/vexil'
    defaults:
      run:
        working-directory: packages/runtime-ts
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "22.22.2"
          registry-url: 'https://registry.npmjs.org'

      - run: npm install --global npm@11.19.0
      - run: npm version "${GITHUB_REF#refs/tags/vexil-runtime-ts-v}" --no-git-tag-version --allow-same-version
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: NODE_AUTH_TOKEN="" npm publish --access public --provenance
