// Code generated by vexilc. DO NOT EDIT.
// Source: cmd.protocol

use vexil_runtime::*;

pub const SCHEMA_HASH: [u8; 32] = [0x84, 0x71, 0x4f, 0x91, 0x71, 0x45, 0x32, 0x82, 0xd6, 0x84, 0x1b, 0xec, 0x66, 0x29, 0xf7, 0x3e, 0x69, 0xd2, 0x53, 0xb9, 0x1d, 0xe7, 0x6b, 0x4c, 0xdc, 0x5e, 0x90, 0xa0, 0x48, 0xc6, 0x76, 0x3e];

// ── Permissions ──
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Permissions(pub u64);

impl Permissions {
    pub const READ: Self = Self(1_u64 << 0_u32);
    pub const WRITE: Self = Self(1_u64 << 1_u32);
    pub const EXECUTE: Self = Self(1_u64 << 2_u32);
    pub const ADMIN: Self = Self(1_u64 << 3_u32);

    pub const fn contains(self, other: Self) -> bool { self.0 & other.0 == other.0 }
    pub const fn is_empty(self) -> bool { self.0 == 0 }
    pub const fn empty() -> Self { Self(0) }
}

impl std::ops::BitOr for Permissions {
    type Output = Self;
    fn bitor(self, rhs: Self) -> Self {
        Self(self.0 | rhs.0)
    }
}

impl std::ops::BitAnd for Permissions {
    type Output = Self;
    fn bitand(self, rhs: Self) -> Self {
        Self(self.0 & rhs.0)
    }
}

impl std::ops::Not for Permissions {
    type Output = Self;
    fn not(self) -> Self {
        Self(!self.0)
    }
}

impl vexil_runtime::Pack for Permissions {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_u8(self.0 as u8);
        Ok(())
    }
}

impl vexil_runtime::Unpack for Permissions {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let raw = r.read_u8()? as u64;
        Ok(Self(raw))
    }
}


// ── Status ──
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u64)]
pub enum Status {
    Ok = 0_u64,
    Error = 1_u64,
    Pending = 2_u64,
}

impl vexil_runtime::Pack for Status {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        let disc: u64 = match self {
            Self::Ok => 0_u64,
            Self::Error => 1_u64,
            Self::Pending => 2_u64,
        };
        w.write_bits(disc, 8_u8);
        Ok(())
    }
}

impl vexil_runtime::Unpack for Status {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let disc = r.read_bits(8_u8)?;
        match disc {
            0_u64 => Ok(Self::Ok),
            1_u64 => Ok(Self::Error),
            2_u64 => Ok(Self::Pending),
            _ => Err(vexil_runtime::DecodeError::UnknownEnumVariant { type_name: "Status", value: disc }),
        }
    }
}


// ── Command ──
#[derive(Debug, Clone, PartialEq)]
pub enum Command {
    Ping {},
    Auth { token: String, perms: Permissions },
    Query { table: String, limit: u32, offset: u32 },
}

impl vexil_runtime::Pack for Command {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.flush_to_byte_boundary();
        match self {
            Self::Ping {} => {
                w.write_leb128(0_u64);
                w.write_leb128(0_u64);
            }
            Self::Auth { token, perms } => {
                w.write_leb128(1_u64);
                let mut payload_w = vexil_runtime::BitWriter::new();
                if (token).len() as u64 > 256_u64 { return Err(vexil_runtime::EncodeError::LimitExceeded { field: "token", limit: 256_u64, actual: (token).len() as u64 }); }
                payload_w.write_string(&token);
                perms.pack(&mut payload_w)?;
                payload_w.flush_to_byte_boundary();
                let payload = payload_w.finish();
                w.write_leb128(payload.len() as u64);
                w.write_raw_bytes(&payload);
            }
            Self::Query { table, limit, offset } => {
                w.write_leb128(2_u64);
                let mut payload_w = vexil_runtime::BitWriter::new();
                if (table).len() as u64 > 128_u64 { return Err(vexil_runtime::EncodeError::LimitExceeded { field: "table", limit: 128_u64, actual: (table).len() as u64 }); }
                payload_w.write_string(&table);
                payload_w.write_leb128(*limit as u64);
                payload_w.write_leb128(*offset as u64);
                payload_w.flush_to_byte_boundary();
                let payload = payload_w.finish();
                w.write_leb128(payload.len() as u64);
                w.write_raw_bytes(&payload);
            }
        }
        Ok(())
    }
}

impl vexil_runtime::Unpack for Command {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        r.flush_to_byte_boundary();
        let disc = r.read_leb128(10_u8)?;
        let len = r.read_leb128(10_u8)? as usize;
        match disc {
            0_u64 => {
                let _skip = r.read_raw_bytes(len)?;
                Ok(Self::Ping {})
            }
            1_u64 => {
                let payload = r.read_raw_bytes(len)?;
                let mut pr = vexil_runtime::BitReader::new(&payload);
                let token = pr.read_string()?;
                if token.len() as u64 > 256_u64 { return Err(vexil_runtime::DecodeError::LimitExceeded { field: "token", limit: 256_u64, actual: token.len() as u64 }); }
                pr.enter_recursive()?;
                let perms = vexil_runtime::Unpack::unpack(&mut pr)?;
                pr.leave_recursive();
                pr.flush_to_byte_boundary();
                Ok(Self::Auth { token, perms })
            }
            2_u64 => {
                let payload = r.read_raw_bytes(len)?;
                let mut pr = vexil_runtime::BitReader::new(&payload);
                let table = pr.read_string()?;
                if table.len() as u64 > 128_u64 { return Err(vexil_runtime::DecodeError::LimitExceeded { field: "table", limit: 128_u64, actual: table.len() as u64 }); }
                let limit_raw = pr.read_leb128(10_u8)?;
                let limit: u32 = limit_raw as u32;
                let offset_raw = pr.read_leb128(10_u8)?;
                let offset: u32 = offset_raw as u32;
                pr.flush_to_byte_boundary();
                Ok(Self::Query { table, limit, offset })
            }
            _ => {
                let _skip = r.read_raw_bytes(len)?;
                Err(vexil_runtime::DecodeError::UnknownUnionVariant { type_name: "Command", discriminant: disc })
            }
        }
    }
}


// ── Request ──
#[derive(Debug, Clone, PartialEq)]
pub struct Request {
    pub id: u64,
    pub command: Command,
}

impl vexil_runtime::Pack for Request {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_leb128(self.id as u64);
        self.command.pack(w)?;
        w.flush_to_byte_boundary();
        Ok(())
    }
}

impl vexil_runtime::Unpack for Request {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let id_raw = r.read_leb128(10_u8)?;
        let id: u64 = id_raw as u64;
        r.enter_recursive()?;
        let command = vexil_runtime::Unpack::unpack(r)?;
        r.leave_recursive();
        r.flush_to_byte_boundary();
        Ok(Self {
            id,
            command,
        })
    }
}


// ── Response ──
#[derive(Debug, Clone, PartialEq)]
pub struct Response {
    pub id: u64,
    pub status: Status,
    pub body: Vec<u8>,
}

impl vexil_runtime::Pack for Response {
    fn pack(&self, w: &mut vexil_runtime::BitWriter) -> Result<(), vexil_runtime::EncodeError> {
        w.write_leb128(self.id as u64);
        self.status.pack(w)?;
        if (self.body).len() as u64 > 65536_u64 { return Err(vexil_runtime::EncodeError::LimitExceeded { field: "body", limit: 65536_u64, actual: (self.body).len() as u64 }); }
        w.write_bytes(&self.body);
        w.flush_to_byte_boundary();
        Ok(())
    }
}

impl vexil_runtime::Unpack for Response {
    fn unpack(r: &mut vexil_runtime::BitReader<'_>) -> Result<Self, vexil_runtime::DecodeError> {
        let id_raw = r.read_leb128(10_u8)?;
        let id: u64 = id_raw as u64;
        r.enter_recursive()?;
        let status = vexil_runtime::Unpack::unpack(r)?;
        r.leave_recursive();
        let body = r.read_bytes()?;
        if body.len() as u64 > 65536_u64 { return Err(vexil_runtime::DecodeError::LimitExceeded { field: "body", limit: 65536_u64, actual: body.len() as u64 }); }
        r.flush_to_byte_boundary();
        Ok(Self {
            id,
            status,
            body,
        })
    }
}

